const musicTerminology = [
    // 1. Tempo (Hız) Terimleri
    { term: "Grave", meaning: "Çok yavaş, ağırbaşlı", category: "Tempo" },
    { term: "Largo", meaning: "Çok yavaş ve geniş", category: "Tempo" },
    { term: "Lento", meaning: "Yavaş", category: "Tempo" },
    { term: "Adagio", meaning: "Yavaş ve rahat", category: "Tempo" },
    { term: "Andante", meaning: "Yürüme hızında, orta yavaş", category: "Tempo" },
    { term: "Moderato", meaning: "Orta hızda", category: "Tempo" },
    { term: "Allegretto", meaning: "Orta hızdan biraz daha hızlı", category: "Tempo" },
    { term: "Allegro", meaning: "Hızlı, neşeli", category: "Tempo" },
    { term: "Vivace", meaning: "Canlı ve hızlı", category: "Tempo" },
    { term: "Presto", meaning: "Çok hızlı", category: "Tempo" },
    { term: "Prestissimo", meaning: "Mümkün olduğunca hızlı", category: "Tempo" },
    { term: "Accelerando (accel.)", meaning: "Giderek hızlanarak", category: "Tempo" },
    { term: "Ritardando (rit.)", meaning: "Giderek yavaşlayarak", category: "Tempo" },
    { term: "Rallentando (rall.)", meaning: "Giderek yavaşlayarak (genişleyerek)", category: "Tempo" },
    { term: "Ritenuto (riten.)", meaning: "Aniden yavaşlayarak (tutarak)", category: "Tempo" },
    { term: "A tempo", meaning: "Önceki (orijinal) tempoya dönüş", category: "Tempo" },
    { term: "Rubato", meaning: "Tempoda serbestlik (esnek tempo)", category: "Tempo" },
    { term: "Stringendo", meaning: "Hızlanarak ve gerilimi artırarak", category: "Tempo" },
    { term: "Più mosso", meaning: "Daha hareketli, daha hızlı", category: "Tempo" },
    { term: "Meno mosso", meaning: "Daha az hareketli, daha yavaş", category: "Tempo" },

    // 2. Dinamik (Nüans / Ses Gürlüğü) Terimleri
    { term: "Pianissimo (pp)", meaning: "Çok hafif sesle", category: "Dinamik" },
    { term: "Piano (p)", meaning: "Hafif sesle", category: "Dinamik" },
    { term: "Mezzo-piano (mp)", meaning: "Orta hafiflikte", category: "Dinamik" },
    { term: "Mezzo-forte (mf)", meaning: "Orta gürlükte", category: "Dinamik" },
    { term: "Forte (f)", meaning: "Güçlü, gür sesle", category: "Dinamik" },
    { term: "Fortissimo (ff)", meaning: "Çok güçlü, çok gür sesle", category: "Dinamik" },
    { term: "Crescendo (cresc.)", meaning: "Sesi giderek gürleştirerek", category: "Dinamik" },
    { term: "Decrescendo (decresc.)", meaning: "Sesi giderek hafifleterek", category: "Dinamik" },
    { term: "Diminuendo (dim.)", meaning: "Sesi giderek hafifleterek (azaltarak)", category: "Dinamik" },
    { term: "Sforzando (sfz / sf)", meaning: "Aniden ve çok kuvvetli vurgu yaparak", category: "Dinamik" },
    { term: "Forte-piano (fp)", meaning: "Önce güçlü, hemen ardından hafif sesle", category: "Dinamik" },

    // 3. Artikülasyon (Çalım Teknikleri) Terimleri
    { term: "Staccato", meaning: "Notaları kısa, kesik kesik çalma", category: "Artikülasyon" },
    { term: "Legato", meaning: "Notaları birbirine bağlayarak (kesintisiz) çalma", category: "Artikülasyon" },
    { term: "Tenuto", meaning: "Notayı tam süresince, ağırlığını hissettirerek çalma", category: "Artikülasyon" },
    { term: "Marcato", meaning: "Her bir notayı belirgin ve vurgulu çalma", category: "Artikülasyon" },
    { term: "Accent", meaning: "Notaya özel bir vurgu yapma", category: "Artikülasyon" },
    { term: "Glissando", meaning: "İki nota arasında kayarak çalma", category: "Artikülasyon" },
    { term: "Pizzicato (pizz.)", meaning: "Yaylı çalgılarda telleri parmakla çekerek çalma", category: "Artikülasyon" },
    { term: "Arco", meaning: "Yaylı çalgılarda telleri yay ile çalma (Pizzicato'yu iptal eder)", category: "Artikülasyon" },
    { term: "Tremolo", meaning: "Bir notayı veya akoru çok hızlı bir şekilde tekrar etme", category: "Artikülasyon" },
    { term: "Trill (Tril)", meaning: "Bir nota ile üstündeki nota arasında hızlıca gidip gelme", category: "Artikülasyon" },
    { term: "Fermata (Korona)", meaning: "Notayı veya es'i kendi değerinden daha uzun tutma", category: "Artikülasyon" },

    // 4. İfade (Duygu / Karakter) Terimleri
    { term: "Dolce", meaning: "Tatlı ve yumuşak", category: "İfade" },
    { term: "Cantabile", meaning: "Şarkı söyler gibi", category: "İfade" },
    { term: "Espressivo (espress.)", meaning: "İfadeli, duygulu", category: "İfade" },
    { term: "Grazioso", meaning: "Zarif, ince", category: "İfade" },
    { term: "Maestoso", meaning: "Görkemli, haşmetli", category: "İfade" },
    { term: "Agitato", meaning: "Telaşlı, heyecanlı, çalkantılı", category: "İfade" },
    { term: "Animato", meaning: "Canlı, hareketli", category: "İfade" },
    { term: "Con brio", meaning: "Canlılık ve ateşle", category: "İfade" },
    { term: "Con moto", meaning: "Hareketli", category: "İfade" },
    { term: "Scherzando", meaning: "Şakacı bir tarzda", category: "İfade" },
    { term: "Tranquillo", meaning: "Sakin, huzurlu", category: "İfade" },
    { term: "Appassionato", meaning: "Tutkulu", category: "İfade" },
    { term: "Brillante", meaning: "Parlak, gösterişli", category: "İfade" },
    { term: "Pesante", meaning: "Ağır, basarak", category: "İfade" },
    { term: "Sostenuto", meaning: "Notaların sürelerini tam tutarak, destekli", category: "İfade" },
    { term: "Leggiero", meaning: "Hafif, çevik", category: "İfade" }
];
