const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'js', 'data_world_stars.js');
let content = fs.readFileSync(filePath, 'utf8');

// Yeni 100 oyuncu listesi (Gerçek hayattan güncel/genç yetenekler)
const newPlayers = [
    {name:"Lamine Yamal",position:"Sağ Açık",age:17,teamId:"barcelona",value:150,role:"winger",trait:"playmaker"},
    {name:"Erling Haaland",position:"Santrafor",age:24,teamId:"mancity",value:180,role:"target_man",trait:"aggressive"},
    {name:"Phil Foden",position:"10 Numara",age:24,teamId:"mancity",value:130,role:"inside_forward",trait:"playmaker"},
    {name:"Rodri",position:"Ön Libero",age:28,teamId:"mancity",value:110,role:"anchor",trait:"maestro"},
    {name:"Aurelien Tchouameni",position:"Ön Libero",age:24,teamId:"realmadrid",value:100,role:"anchor",trait:"stopper"},
    {name:"Eduardo Camavinga",position:"Merkez Orta Saha",age:21,teamId:"realmadrid",value:100,role:"box_to_box",trait:"elite"},
    {name:"Rafael Leão",position:"Sol Açık",age:25,teamId:"milan",value:90,role:"winger",trait:"aggressive"},
    {name:"Victor Osimhen",position:"Santrafor",age:25,teamId:"napoli",value:110,role:"poacher",trait:"aggressive"},
    {name:"Gavi",position:"Merkez Orta Saha",age:20,teamId:"barcelona",value:90,role:"box_to_box",trait:"aggressive"},
    {name:"Ronald Araujo",position:"Stoper",age:25,teamId:"barcelona",value:75,role:"stopper",trait:"aggressive"},
    {name:"Trent Alexander-Arnold",position:"Sağ Bek",age:26,teamId:"liverpool",value:70,role:"wing_back",trait:"playmaker"},
    {name:"Bruno Guimarães",position:"Ön Libero",age:26,teamId:"newcastle",value:85,role:"playmaker",trait:"aggressive"},
    {name:"Alexander Isak",position:"Santrafor",age:25,teamId:"newcastle",value:75,role:"poacher",trait:"elite"},
    {name:"Sven Botman",position:"Stoper",age:24,teamId:"newcastle",value:45,role:"stopper",trait:"stopper"},
    {name:"Marcus Rashford",position:"Sol Açık",age:26,teamId:"manutd",value:60,role:"inside_forward",trait:"winger"},
    {name:"Bruno Fernandes",position:"10 Numara",age:30,teamId:"manutd",value:70,role:"playmaker",trait:"maestro"},
    {name:"Lisandro Martinez",position:"Stoper",age:26,teamId:"manutd",value:45,role:"stopper",trait:"aggressive"},
    {name:"Martin Odegaard",position:"10 Numara",age:25,teamId:"arsenal",value:110,role:"maestro",trait:"playmaker"},
    {name:"Gabriel Martinelli",position:"Sol Açık",age:23,teamId:"arsenal",value:80,role:"winger",trait:"aggressive"},
    {name:"Gabriel Magalhaes",position:"Stoper",age:26,teamId:"arsenal",value:65,role:"stopper",trait:"stopper"},
    {name:"Bernardo Silva",position:"Merkez Orta Saha",age:30,teamId:"mancity",value:70,role:"playmaker",trait:"maestro"},
    {name:"Ruben Dias",position:"Stoper",age:27,teamId:"mancity",value:80,role:"stopper",trait:"elite"},
    {name:"Kevin De Bruyne",position:"10 Numara",age:33,teamId:"mancity",value:60,role:"maestro",trait:"playmaker"},
    {name:"Luis Diaz",position:"Sol Açık",age:27,teamId:"liverpool",value:75,role:"winger",trait:"aggressive"},
    {name:"Alexis Mac Allister",position:"Merkez Orta Saha",age:25,teamId:"liverpool",value:75,role:"playmaker",trait:"elite"},
    {name:"Virgil van Dijk",position:"Stoper",age:33,teamId:"liverpool",value:30,role:"stopper",trait:"leader"},
    {name:"Alisson",position:"Kaleci",age:32,teamId:"liverpool",value:30,role:"sweeper_keeper",trait:"elite"},
    {name:"Ederson",position:"Kaleci",age:31,teamId:"mancity",value:40,role:"sweeper_keeper",trait:"elite"},
    {name:"Thibaut Courtois",position:"Kaleci",age:32,teamId:"realmadrid",value:30,role:"sweeper_keeper",trait:"elite"},
    {name:"Jan Oblak",position:"Kaleci",age:31,teamId:"atleticomadrid",value:30,role:"sweeper_keeper",trait:"elite"},
    {name:"Mike Maignan",position:"Kaleci",age:29,teamId:"milan",value:40,role:"sweeper_keeper",trait:"elite"},
    {name:"Alessandro Bastoni",position:"Stoper",age:25,teamId:"inter",value:70,role:"stopper",trait:"playmaker"},
    {name:"Nicolo Barella",position:"Merkez Orta Saha",age:27,teamId:"inter",value:80,role:"box_to_box",trait:"elite"},
    {name:"Federico Dimarco",position:"Sol Bek",age:26,teamId:"inter",value:50,role:"wing_back",trait:"aggressive"},
    {name:"Theo Hernandez",position:"Sol Bek",age:27,teamId:"milan",value:60,role:"wing_back",trait:"aggressive"},
    {name:"Fikayo Tomori",position:"Stoper",age:26,teamId:"milan",value:40,role:"stopper",trait:"stopper"},
    {name:"Dusan Vlahovic",position:"Santrafor",age:24,teamId:"juventus",value:65,role:"target_man",trait:"poacher"},
    {name:"Federico Chiesa",position:"Sağ Açık",age:26,teamId:"juventus",value:40,role:"winger",trait:"aggressive"},
    {name:"Gleison Bremer",position:"Stoper",age:27,teamId:"juventus",value:60,role:"stopper",trait:"stopper"},
    {name:"Manuel Locatelli",position:"Ön Libero",age:26,teamId:"juventus",value:30,role:"anchor",trait:"playmaker"},
    {name:"Lois Openda",position:"Santrafor",age:24,teamId:"rbleipzig",value:60,role:"poacher",trait:"aggressive"},
    {name:"Xavi Simons",position:"10 Numara",age:21,teamId:"rbleipzig",value:80,role:"playmaker",trait:"elite"},
    {name:"Dani Olmo",position:"10 Numara",age:26,teamId:"rbleipzig",value:50,role:"maestro",trait:"playmaker"},
    {name:"Benjamin Sesko",position:"Santrafor",age:21,teamId:"rbleipzig",value:50,role:"target_man",trait:"poacher"},
    {name:"Harry Kane",position:"Santrafor",age:31,teamId:"bayern",value:100,role:"target_man",trait:"playmaker"},
    {name:"Leroy Sane",position:"Sağ Açık",age:28,teamId:"bayern",value:70,role:"inside_forward",trait:"winger"},
    {name:"Alphonso Davies",position:"Sol Bek",age:23,teamId:"bayern",value:50,role:"wing_back",trait:"aggressive"},
    {name:"Dayot Upamecano",position:"Stoper",age:26,teamId:"bayern",value:45,role:"stopper",trait:"stopper"},
    {name:"Mathys Tel",position:"Santrafor",age:19,teamId:"bayern",value:40,role:"poacher",trait:"elite"},
    {name:"Jeremie Frimpong",position:"Sağ Bek",age:23,teamId:"leverkusen",value:50,role:"wing_back",trait:"aggressive"},
    {name:"Victor Boniface",position:"Santrafor",age:23,teamId:"leverkusen",value:40,role:"target_man",trait:"poacher"},
    {name:"Alex Grimaldo",position:"Sol Bek",age:29,teamId:"leverkusen",value:45,role:"wing_back",trait:"playmaker"},
    {name:"Exequiel Palacios",position:"Merkez Orta Saha",age:26,teamId:"leverkusen",value:40,role:"box_to_box",trait:"playmaker"},
    {name:"Marquinhos",position:"Stoper",age:30,teamId:"psg",value:50,role:"stopper",trait:"leader"},
    {name:"Gianluigi Donnarumma",position:"Kaleci",age:25,teamId:"psg",value:40,role:"sweeper_keeper",trait:"elite"},
    {name:"Randal Kolo Muani",position:"Santrafor",age:25,teamId:"psg",value:45,role:"poacher",trait:"aggressive"},
    {name:"Ousmane Dembele",position:"Sağ Açık",age:27,teamId:"psg",value:60,role:"winger",trait:"playmaker"},
    {name:"Manuel Ugarte",position:"Ön Libero",age:23,teamId:"psg",value:45,role:"anchor",trait:"stopper"},
    {name:"Evan Ferguson",position:"Santrafor",age:19,teamId:"brighton",value:50,role:"target_man",trait:"elite"},
    {name:"Kaoru Mitoma",position:"Sol Açık",age:27,teamId:"brighton",value:45,role:"winger",trait:"aggressive"},
    {name:"Pervis Estupinan",position:"Sol Bek",age:26,teamId:"brighton",value:35,role:"wing_back",trait:"aggressive"},
    {name:"Joao Pedro",position:"Santrafor",age:23,teamId:"brighton",value:35,role:"poacher",trait:"playmaker"},
    {name:"Mohammed Kudus",position:"Sağ Açık",age:24,teamId:"westham",value:50,role:"inside_forward",trait:"aggressive"},
    {name:"Lucas Paqueta",position:"10 Numara",age:27,teamId:"westham",value:65,role:"playmaker",trait:"maestro"},
    {name:"Jarrod Bowen",position:"Sağ Açık",age:27,teamId:"westham",value:50,role:"inside_forward",trait:"poacher"},
    {name:"Edson Alvarez",position:"Ön Libero",age:26,teamId:"westham",value:35,role:"anchor",trait:"stopper"},
    {name:"Eberechi Eze",position:"10 Numara",age:26,teamId:"crystalpalace",value:55,role:"playmaker",trait:"maestro"},
    {name:"Marc Guehi",position:"Stoper",age:24,teamId:"crystalpalace",value:38,role:"stopper",trait:"stopper"},
    {name:"Michael Olise",position:"Sağ Açık",age:22,teamId:"crystalpalace",value:55,role:"inside_forward",trait:"playmaker"},
    {name:"Dominic Solanke",position:"Santrafor",age:27,teamId:"bournemouth",value:40,role:"target_man",trait:"poacher"},
    {name:"Milos Kerkez",position:"Sol Bek",age:20,teamId:"bournemouth",value:20,role:"wing_back",trait:"aggressive"},
    {name:"Bryan Mbeumo",position:"Sağ Açık",age:25,teamId:"brentford",value:40,role:"inside_forward",trait:"playmaker"},
    {name:"Ivan Toney",position:"Santrafor",age:28,teamId:"brentford",value:50,role:"target_man",trait:"poacher"},
    {name:"Ollie Watkins",position:"Santrafor",age:28,teamId:"astonvilla",value:65,role:"poacher",trait:"aggressive"},
    {name:"Douglas Luiz",position:"Merkez Orta Saha",age:26,teamId:"astonvilla",value:70,role:"box_to_box",trait:"playmaker"},
    {name:"Moussa Diaby",position:"Sağ Açık",age:25,teamId:"astonvilla",value:55,role:"winger",trait:"aggressive"},
    {name:"Pau Torres",position:"Stoper",age:27,teamId:"astonvilla",value:45,role:"stopper",trait:"playmaker"},
    {name:"Pedro Neto",position:"Sol Açık",age:24,teamId:"wolves",value:55,role:"winger",trait:"aggressive"},
    {name:"Matheus Cunha",position:"Santrafor",age:25,teamId:"wolves",value:45,role:"poacher",trait:"playmaker"},
    {name:"Joao Gomes",position:"Ön Libero",age:23,teamId:"wolves",value:35,role:"anchor",trait:"stopper"},
    {name:"Hwang Hee-chan",position:"Santrafor",age:28,teamId:"wolves",value:25,role:"poacher",trait:"aggressive"},
    {name:"Antonee Robinson",position:"Sol Bek",age:27,teamId:"fulham",value:20,role:"wing_back",trait:"aggressive"},
    {name:"Joao Palhinha",position:"Ön Libero",age:29,teamId:"fulham",value:55,role:"anchor",trait:"stopper"},
    {name:"Alex Iwobi",position:"Merkez Orta Saha",age:28,teamId:"fulham",value:25,role:"box_to_box",trait:"playmaker"},
    {name:"Jarrad Branthwaite",position:"Stoper",age:22,teamId:"everton",value:42,role:"stopper",trait:"stopper"},
    {name:"Amadou Onana",position:"Ön Libero",age:23,teamId:"everton",value:50,role:"anchor",trait:"stopper"},
    {name:"Dwight McNeil",position:"Sol Açık",age:24,teamId:"everton",value:22,role:"winger",trait:"playmaker"},
    {name:"Anthony Gordon",position:"Sol Açık",age:23,teamId:"newcastle",value:60,role:"inside_forward",trait:"aggressive"},
    {name:"Kieran Trippier",position:"Sağ Bek",age:34,teamId:"newcastle",value:10,role:"wing_back",trait:"playmaker"},
    {name:"Morgan Gibbs-White",position:"10 Numara",age:24,teamId:"nottmforest",value:40,role:"playmaker",trait:"maestro"},
    {name:"Murillo",position:"Stoper",age:22,teamId:"nottmforest",value:35,role:"stopper",trait:"stopper"},
    {name:"Taiwo Awoniyi",position:"Santrafor",age:27,teamId:"nottmforest",value:28,role:"target_man",trait:"poacher"},
    {name:"Enes Ünal",position:"Santrafor",age:27,teamId:"bournemouth",value:18,role:"target_man",trait:"poacher"},
    {name:"Çağlar Söyüncü",position:"Stoper",age:28,teamId:"fenerbahce",value:15,role:"stopper",trait:"aggressive"},
    {name:"Orkun Kökçü",position:"Merkez Orta Saha",age:23,teamId:"benfica",value:27,role:"playmaker",trait:"maestro"},
    {name:"Kerem Aktürkoğlu",position:"Sol Açık",age:25,teamId:"galatasaray",value:15,role:"inside_forward",trait:"aggressive"},
    {name:"Barış Alper Yılmaz",position:"Sağ Açık",age:24,teamId:"galatasaray",value:20,role:"winger",trait:"elite"},
    {name:"İsmail Yüksek",position:"Ön Libero",age:25,teamId:"fenerbahce",value:14,role:"anchor",trait:"stopper"},
    {name:"Sebastian Szymanski",position:"10 Numara",age:25,teamId:"fenerbahce",value:19,role:"playmaker",trait:"maestro"},
    {name:"Mauro Icardi",position:"Santrafor",age:31,teamId:"galatasaray",value:17,role:"poacher",trait:"elite"}
];

let formattedPlayers = newPlayers.map(p => `    ${JSON.stringify(p)}`).join(",\n");

// worldStarsRaw dizisinin sonuna ekleyeceğiz
content = content.replace(/(];)/, `,\n${formattedPlayers}\n$1`);

fs.writeFileSync(filePath, content, 'utf8');
console.log("100 Transfermarkt players added to data_world_stars.js!");
