// js/data_premier.js
// GERCEK 2026/2027 PREMIER LIG VERILERI
window.leagueData = window.leagueData || { teams: [], players: [] };
window.leagueData.teams = window.leagueData.teams.filter(t => t.leagueId !== 'premier');
const premierTeams = [
    {
        "id": "mancity",
        "name": "Manchester City",
        "budget": 95,
        "leagueId": "premier"
    },
    {
        "id": "liverpool",
        "name": "Liverpool",
        "budget": 85,
        "leagueId": "premier"
    },
    {
        "id": "arsenal",
        "name": "Arsenal",
        "budget": 85,
        "leagueId": "premier"
    },
    {
        "id": "chelsea",
        "name": "Chelsea",
        "budget": 90,
        "leagueId": "premier"
    },
    {
        "id": "manutd",
        "name": "Manchester United",
        "budget": 85,
        "leagueId": "premier"
    },
    {
        "id": "tottenham",
        "name": "Tottenham Hotspur",
        "budget": 80,
        "leagueId": "premier"
    },
    {
        "id": "newcastle",
        "name": "Newcastle United",
        "budget": 80,
        "leagueId": "premier"
    },
    {
        "id": "astonvilla",
        "name": "Aston Villa",
        "budget": 75,
        "leagueId": "premier"
    }
];
premierTeams.forEach(t => window.leagueData.teams.push(t));
window.leagueData.players = window.leagueData.players.filter(p => !premierTeams.some(t => t.id === p.teamId));
const premierPlayers = [
    {
        "id": "ederson_mancity",
        "name": "Ederson",
        "position": "Kaleci",
        "power": 89,
        "speed": 5,
        "age": 21,
        "teamId": "mancity",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "rubendias_mancity",
        "name": "Ruben Dias",
        "position": "Stoper",
        "power": 88,
        "speed": 8,
        "age": 22,
        "teamId": "mancity",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "johnstones_mancity",
        "name": "John Stones",
        "position": "Stoper",
        "power": 86,
        "speed": 7,
        "age": 31,
        "teamId": "mancity",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "joskogvardiol_mancity",
        "name": "Josko Gvardiol",
        "position": "Sağ Bek",
        "power": 84,
        "speed": 9,
        "age": 33,
        "teamId": "mancity",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "kylewalker_mancity",
        "name": "Kyle Walker",
        "position": "Sağ Bek",
        "power": 87,
        "speed": 5,
        "age": 29,
        "teamId": "mancity",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "rodri_mancity",
        "name": "Rodri",
        "position": "Ön Libero",
        "power": 95,
        "speed": 6,
        "age": 25,
        "teamId": "mancity",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "kevindebruyne_mancity",
        "name": "Kevin De Bruyne",
        "position": "Merkez Orta Saha",
        "power": 93,
        "speed": 7,
        "age": 33,
        "teamId": "mancity",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "philfoden_mancity",
        "name": "Phil Foden",
        "position": "Forvet Arkası",
        "power": 84,
        "speed": 8,
        "age": 21,
        "teamId": "mancity",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "bernardosilva_mancity",
        "name": "Bernardo Silva",
        "position": "Sağ Kanat",
        "power": 88,
        "speed": 8,
        "age": 28,
        "teamId": "mancity",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "erlinghaaland_mancity",
        "name": "Erling Haaland",
        "position": "Santrfor",
        "power": 88,
        "speed": 4.7,
        "age": 26,
        "teamId": "mancity",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "jeremydoku_mancity",
        "name": "Jeremy Doku",
        "position": "Forvet",
        "power": 84,
        "speed": 8,
        "age": 22,
        "teamId": "mancity",
        "tacticalRole": "target_man",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "nathanake_mancity",
        "name": "Nathan Ake",
        "position": "Forvet",
        "power": 83,
        "speed": 9,
        "age": 22,
        "teamId": "mancity",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "manuelakanji_mancity",
        "name": "Manuel Akanji",
        "position": "Orta Saha",
        "power": 84,
        "speed": 6,
        "age": 23,
        "teamId": "mancity",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "mateokovacic_mancity",
        "name": "Mateo Kovacic",
        "position": "Stoper",
        "power": 84,
        "speed": 8,
        "age": 26,
        "teamId": "mancity",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "jackgrealish_mancity",
        "name": "Jack Grealish",
        "position": "Sol Bek",
        "power": 82,
        "speed": 5,
        "age": 28,
        "teamId": "mancity",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "savio_mancity",
        "name": "Savio",
        "position": "Ön Libero",
        "power": 86,
        "speed": 5,
        "age": 28,
        "teamId": "mancity",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "oscarbobb_mancity",
        "name": "Oscar Bobb",
        "position": "Sağ Kanat",
        "power": 83,
        "speed": 9,
        "age": 25,
        "teamId": "mancity",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "alisson_liverpool",
        "name": "Alisson",
        "position": "Kaleci",
        "power": 81,
        "speed": 6,
        "age": 23,
        "teamId": "liverpool",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "virgilvandijk_liverpool",
        "name": "Virgil van Dijk",
        "position": "Stoper",
        "power": 88,
        "speed": 6,
        "age": 22,
        "teamId": "liverpool",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "ibrahimakonate_liverpool",
        "name": "Ibrahima Konate",
        "position": "Stoper",
        "power": 78,
        "speed": 5,
        "age": 34,
        "teamId": "liverpool",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "trentalexanderarnold_liverpool",
        "name": "Trent Alexander-Arnold",
        "position": "Sağ Bek",
        "power": 79,
        "speed": 9,
        "age": 26,
        "teamId": "liverpool",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "andyrobertson_liverpool",
        "name": "Andy Robertson",
        "position": "Sol Bek",
        "power": 79,
        "speed": 7,
        "age": 25,
        "teamId": "liverpool",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "alexismacallister_liverpool",
        "name": "Alexis Mac Allister",
        "position": "Ön Libero",
        "power": 80,
        "speed": 5,
        "age": 21,
        "teamId": "liverpool",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "ryangravenberch_liverpool",
        "name": "Ryan Gravenberch",
        "position": "Merkez Orta Saha",
        "power": 78,
        "speed": 8,
        "age": 25,
        "teamId": "liverpool",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "dominikszoboszlai_liverpool",
        "name": "Dominik Szoboszlai",
        "position": "Forvet Arkası",
        "power": 83,
        "speed": 9,
        "age": 23,
        "teamId": "liverpool",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "mohamedsalah_liverpool",
        "name": "Mohamed Salah",
        "position": "Sağ Kanat",
        "power": 88,
        "speed": 9,
        "age": 29,
        "teamId": "liverpool",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "luisdiaz_liverpool",
        "name": "Luis Diaz",
        "position": "Sol Kanat",
        "power": 83,
        "speed": 6,
        "age": 28,
        "teamId": "liverpool",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "diogojota_liverpool",
        "name": "Diogo Jota",
        "position": "Forvet",
        "power": 82,
        "speed": 6,
        "age": 33,
        "teamId": "liverpool",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "darwinnunez_liverpool",
        "name": "Darwin Nunez",
        "position": "Forvet",
        "power": 83,
        "speed": 6,
        "age": 28,
        "teamId": "liverpool",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "codygakpo_liverpool",
        "name": "Cody Gakpo",
        "position": "Orta Saha",
        "power": 82,
        "speed": 5,
        "age": 31,
        "teamId": "liverpool",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "harveyelliott_liverpool",
        "name": "Harvey Elliott",
        "position": "Stoper",
        "power": 83,
        "speed": 7,
        "age": 34,
        "teamId": "liverpool",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "federicochiesa_liverpool",
        "name": "Federico Chiesa",
        "position": "Sol Bek",
        "power": 84,
        "speed": 7,
        "age": 34,
        "teamId": "liverpool",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "conorbradley_liverpool",
        "name": "Conor Bradley",
        "position": "Ön Libero",
        "power": 85,
        "speed": 8,
        "age": 32,
        "teamId": "liverpool",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "davidraya_arsenal",
        "name": "David Raya",
        "position": "Kaleci",
        "power": 81,
        "speed": 6,
        "age": 29,
        "teamId": "arsenal",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "williamsaliba_arsenal",
        "name": "William Saliba",
        "position": "Stoper",
        "power": 83,
        "speed": 9,
        "age": 33,
        "teamId": "arsenal",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "gabrielmagalhaes_arsenal",
        "name": "Gabriel Magalhaes",
        "position": "Stoper",
        "power": 84,
        "speed": 9,
        "age": 28,
        "teamId": "arsenal",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "benwhite_arsenal",
        "name": "Ben White",
        "position": "Sağ Bek",
        "power": 83,
        "speed": 6,
        "age": 21,
        "teamId": "arsenal",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "riccardocalafiori_arsenal",
        "name": "Riccardo Calafiori",
        "position": "Sol Bek",
        "power": 85,
        "speed": 8,
        "age": 21,
        "teamId": "arsenal",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "declanrice_arsenal",
        "name": "Declan Rice",
        "position": "Ön Libero",
        "power": 80,
        "speed": 5,
        "age": 27,
        "teamId": "arsenal",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "martinodegaard_arsenal",
        "name": "Martin Odegaard",
        "position": "Merkez Orta Saha",
        "power": 88,
        "speed": 7,
        "age": 30,
        "teamId": "arsenal",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "mikelmerino_arsenal",
        "name": "Mikel Merino",
        "position": "Forvet Arkası",
        "power": 80,
        "speed": 7,
        "age": 33,
        "teamId": "arsenal",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "bukayosaka_arsenal",
        "name": "Bukayo Saka",
        "position": "Sağ Kanat",
        "power": 88,
        "speed": 7,
        "age": 24,
        "teamId": "arsenal",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "gabrielmartinelli_arsenal",
        "name": "Gabriel Martinelli",
        "position": "Sol Kanat",
        "power": 79,
        "speed": 7,
        "age": 31,
        "teamId": "arsenal",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "kaihavertz_arsenal",
        "name": "Kai Havertz",
        "position": "Forvet",
        "power": 85,
        "speed": 6,
        "age": 32,
        "teamId": "arsenal",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "jurrientimber_arsenal",
        "name": "Jurrien Timber",
        "position": "Forvet",
        "power": 80,
        "speed": 9,
        "age": 25,
        "teamId": "arsenal",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "thomaspartey_arsenal",
        "name": "Thomas Partey",
        "position": "Orta Saha",
        "power": 82,
        "speed": 7,
        "age": 29,
        "teamId": "arsenal",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "raheemsterling_arsenal",
        "name": "Raheem Sterling",
        "position": "Stoper",
        "power": 78,
        "speed": 5,
        "age": 21,
        "teamId": "arsenal",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "gabrieljesus_arsenal",
        "name": "Gabriel Jesus",
        "position": "Sol Bek",
        "power": 80,
        "speed": 7,
        "age": 30,
        "teamId": "arsenal",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "robertsanchez_chelsea",
        "name": "Robert Sanchez",
        "position": "Kaleci",
        "power": 87,
        "speed": 5,
        "age": 22,
        "teamId": "chelsea",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "levicolwill_chelsea",
        "name": "Levi Colwill",
        "position": "Stoper",
        "power": 89,
        "speed": 5,
        "age": 21,
        "teamId": "chelsea",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "wesleyfofana_chelsea",
        "name": "Wesley Fofana",
        "position": "Stoper",
        "power": 83,
        "speed": 5,
        "age": 28,
        "teamId": "chelsea",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "malogusto_chelsea",
        "name": "Malo Gusto",
        "position": "Sağ Bek",
        "power": 85,
        "speed": 8,
        "age": 34,
        "teamId": "chelsea",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "marccucurella_chelsea",
        "name": "Marc Cucurella",
        "position": "Sol Bek",
        "power": 82,
        "speed": 7,
        "age": 21,
        "teamId": "chelsea",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "moisescaicedo_chelsea",
        "name": "Moises Caicedo",
        "position": "Ön Libero",
        "power": 88,
        "speed": 8,
        "age": 21,
        "teamId": "chelsea",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "enzofernandez_chelsea",
        "name": "Enzo Fernandez",
        "position": "Merkez Orta Saha",
        "power": 83,
        "speed": 6,
        "age": 32,
        "teamId": "chelsea",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "colepalmer_chelsea",
        "name": "Cole Palmer",
        "position": "Forvet Arkası",
        "power": 93,
        "speed": 8,
        "age": 23,
        "teamId": "chelsea",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "christophernkunku_chelsea",
        "name": "Christopher Nkunku",
        "position": "Sağ Kanat",
        "power": 82,
        "speed": 5,
        "age": 23,
        "teamId": "chelsea",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "nonimadueke_chelsea",
        "name": "Noni Madueke",
        "position": "Sol Kanat",
        "power": 85,
        "speed": 6,
        "age": 25,
        "teamId": "chelsea",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "nicolasjackson_chelsea",
        "name": "Nicolas Jackson",
        "position": "Forvet",
        "power": 82,
        "speed": 6,
        "age": 32,
        "teamId": "chelsea",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "jadonsancho_chelsea",
        "name": "Jadon Sancho",
        "position": "Forvet",
        "power": 85,
        "speed": 5,
        "age": 33,
        "teamId": "chelsea",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "pedroneto_chelsea",
        "name": "Pedro Neto",
        "position": "Orta Saha",
        "power": 86,
        "speed": 6,
        "age": 23,
        "teamId": "chelsea",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "joaofelix_chelsea",
        "name": "Joao Felix",
        "position": "Stoper",
        "power": 88,
        "speed": 8,
        "age": 25,
        "teamId": "chelsea",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "romeolavia_chelsea",
        "name": "Romeo Lavia",
        "position": "Sol Bek",
        "power": 87,
        "speed": 9,
        "age": 26,
        "teamId": "chelsea",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "reecejames_chelsea",
        "name": "Reece James",
        "position": "Ön Libero",
        "power": 89,
        "speed": 8,
        "age": 33,
        "teamId": "chelsea",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "andreonana_manutd",
        "name": "Andre Onana",
        "position": "Kaleci",
        "power": 85,
        "speed": 8,
        "age": 25,
        "teamId": "manutd",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "lisandromartinez_manutd",
        "name": "Lisandro Martinez",
        "position": "Stoper",
        "power": 78,
        "speed": 7,
        "age": 23,
        "teamId": "manutd",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "matthijsdeligt_manutd",
        "name": "Matthijs de Ligt",
        "position": "Stoper",
        "power": 83,
        "speed": 6,
        "age": 22,
        "teamId": "manutd",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "diogodalot_manutd",
        "name": "Diogo Dalot",
        "position": "Sağ Bek",
        "power": 82,
        "speed": 7,
        "age": 25,
        "teamId": "manutd",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "noussairmazraoui_manutd",
        "name": "Noussair Mazraoui",
        "position": "Sol Bek",
        "power": 84,
        "speed": 6,
        "age": 21,
        "teamId": "manutd",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "kobbiemainoo_manutd",
        "name": "Kobbie Mainoo",
        "position": "Ön Libero",
        "power": 82,
        "speed": 5,
        "age": 29,
        "teamId": "manutd",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "manuelugarte_manutd",
        "name": "Manuel Ugarte",
        "position": "Merkez Orta Saha",
        "power": 83,
        "speed": 7,
        "age": 31,
        "teamId": "manutd",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "brunofernandes_manutd",
        "name": "Bruno Fernandes",
        "position": "Forvet Arkası",
        "power": 80,
        "speed": 7,
        "age": 22,
        "teamId": "manutd",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "alejandrogarnacho_manutd",
        "name": "Alejandro Garnacho",
        "position": "Sağ Kanat",
        "power": 80,
        "speed": 6,
        "age": 33,
        "teamId": "manutd",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "marcusrashford_manutd",
        "name": "Marcus Rashford",
        "position": "Sol Kanat",
        "power": 80,
        "speed": 9,
        "age": 34,
        "teamId": "manutd",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "rasmushojlund_manutd",
        "name": "Rasmus Hojlund",
        "position": "Forvet",
        "power": 82,
        "speed": 5,
        "age": 30,
        "teamId": "manutd",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "joshuazirkzee_manutd",
        "name": "Joshua Zirkzee",
        "position": "Forvet",
        "power": 84,
        "speed": 6,
        "age": 26,
        "teamId": "manutd",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "amaddiallo_manutd",
        "name": "Amad Diallo",
        "position": "Orta Saha",
        "power": 84,
        "speed": 6,
        "age": 27,
        "teamId": "manutd",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "lenyyoro_manutd",
        "name": "Leny Yoro",
        "position": "Stoper",
        "power": 84,
        "speed": 5,
        "age": 31,
        "teamId": "manutd",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "harrymaguire_manutd",
        "name": "Harry Maguire",
        "position": "Ön Libero",
        "power": 85,
        "speed": 7,
        "age": 23,
        "teamId": "manutd",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "guglielmovicario_tottenham",
        "name": "Guglielmo Vicario",
        "position": "Kaleci",
        "power": 78,
        "speed": 7,
        "age": 24,
        "teamId": "tottenham",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "cristianromero_tottenham",
        "name": "Cristian Romero",
        "position": "Stoper",
        "power": 83,
        "speed": 9,
        "age": 25,
        "teamId": "tottenham",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "mickyvandeven_tottenham",
        "name": "Micky van de Ven",
        "position": "Stoper",
        "power": 83,
        "speed": 6,
        "age": 23,
        "teamId": "tottenham",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "pedroporro_tottenham",
        "name": "Pedro Porro",
        "position": "Sağ Bek",
        "power": 78,
        "speed": 6,
        "age": 21,
        "teamId": "tottenham",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "destinyudogie_tottenham",
        "name": "Destiny Udogie",
        "position": "Sol Bek",
        "power": 78,
        "speed": 9,
        "age": 25,
        "teamId": "tottenham",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "yvesbissouma_tottenham",
        "name": "Yves Bissouma",
        "position": "Ön Libero",
        "power": 79,
        "speed": 6,
        "age": 23,
        "teamId": "tottenham",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "papematarsarr_tottenham",
        "name": "Pape Matar Sarr",
        "position": "Merkez Orta Saha",
        "power": 80,
        "speed": 7,
        "age": 27,
        "teamId": "tottenham",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "jamesmaddison_tottenham",
        "name": "James Maddison",
        "position": "Forvet Arkası",
        "power": 83,
        "speed": 5,
        "age": 31,
        "teamId": "tottenham",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "dejankulusevski_tottenham",
        "name": "Dejan Kulusevski",
        "position": "Sağ Kanat",
        "power": 85,
        "speed": 7,
        "age": 26,
        "teamId": "tottenham",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "sonheungmin_tottenham",
        "name": "Son Heung-min",
        "position": "Sol Kanat",
        "power": 88,
        "speed": 7,
        "age": 27,
        "teamId": "tottenham",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "dominicsolanke_tottenham",
        "name": "Dominic Solanke",
        "position": "Forvet",
        "power": 80,
        "speed": 8,
        "age": 31,
        "teamId": "tottenham",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "brennanjohnson_tottenham",
        "name": "Brennan Johnson",
        "position": "Forvet",
        "power": 82,
        "speed": 6,
        "age": 33,
        "teamId": "tottenham",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "richarlison_tottenham",
        "name": "Richarlison",
        "position": "Orta Saha",
        "power": 82,
        "speed": 5,
        "age": 21,
        "teamId": "tottenham",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "radudragusin_tottenham",
        "name": "Radu Dragusin",
        "position": "Stoper",
        "power": 85,
        "speed": 9,
        "age": 25,
        "teamId": "tottenham",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "lucasbergvall_tottenham",
        "name": "Lucas Bergvall",
        "position": "Sol Bek",
        "power": 81,
        "speed": 6,
        "age": 33,
        "teamId": "tottenham",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "nickpope_newcastle",
        "name": "Nick Pope",
        "position": "Kaleci",
        "power": 81,
        "speed": 7,
        "age": 22,
        "teamId": "newcastle",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "svenbotman_newcastle",
        "name": "Sven Botman",
        "position": "Stoper",
        "power": 82,
        "speed": 7,
        "age": 34,
        "teamId": "newcastle",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "fabianschar_newcastle",
        "name": "Fabian Schar",
        "position": "Stoper",
        "power": 85,
        "speed": 9,
        "age": 33,
        "teamId": "newcastle",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "kierantrippier_newcastle",
        "name": "Kieran Trippier",
        "position": "Sağ Bek",
        "power": 79,
        "speed": 6,
        "age": 24,
        "teamId": "newcastle",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "lewishall_newcastle",
        "name": "Lewis Hall",
        "position": "Sol Bek",
        "power": 83,
        "speed": 8,
        "age": 21,
        "teamId": "newcastle",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "brunoguimaraes_newcastle",
        "name": "Bruno Guimaraes",
        "position": "Ön Libero",
        "power": 83,
        "speed": 7,
        "age": 31,
        "teamId": "newcastle",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "sandrotonali_newcastle",
        "name": "Sandro Tonali",
        "position": "Merkez Orta Saha",
        "power": 81,
        "speed": 7,
        "age": 33,
        "teamId": "newcastle",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "joelinton_newcastle",
        "name": "Joelinton",
        "position": "Forvet Arkası",
        "power": 84,
        "speed": 6,
        "age": 30,
        "teamId": "newcastle",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "anthonygordon_newcastle",
        "name": "Anthony Gordon",
        "position": "Sağ Kanat",
        "power": 84,
        "speed": 6,
        "age": 31,
        "teamId": "newcastle",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "alexanderisak_newcastle",
        "name": "Alexander Isak",
        "position": "Sol Kanat",
        "power": 78,
        "speed": 7,
        "age": 25,
        "teamId": "newcastle",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "harveybarnes_newcastle",
        "name": "Harvey Barnes",
        "position": "Forvet",
        "power": 85,
        "speed": 6,
        "age": 27,
        "teamId": "newcastle",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "jacobmurphy_newcastle",
        "name": "Jacob Murphy",
        "position": "Forvet",
        "power": 83,
        "speed": 9,
        "age": 33,
        "teamId": "newcastle",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "joewillock_newcastle",
        "name": "Joe Willock",
        "position": "Orta Saha",
        "power": 84,
        "speed": 5,
        "age": 28,
        "teamId": "newcastle",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "lloydkelly_newcastle",
        "name": "Lloyd Kelly",
        "position": "Stoper",
        "power": 84,
        "speed": 6,
        "age": 33,
        "teamId": "newcastle",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "callumwilson_newcastle",
        "name": "Callum Wilson",
        "position": "Sol Bek",
        "power": 84,
        "speed": 9,
        "age": 24,
        "teamId": "newcastle",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "emilianomartinez_astonvilla",
        "name": "Emiliano Martinez",
        "position": "Kaleci",
        "power": 79,
        "speed": 6,
        "age": 21,
        "teamId": "astonvilla",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "pautorres_astonvilla",
        "name": "Pau Torres",
        "position": "Stoper",
        "power": 76,
        "speed": 6,
        "age": 29,
        "teamId": "astonvilla",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "ezrikonsa_astonvilla",
        "name": "Ezri Konsa",
        "position": "Stoper",
        "power": 79,
        "speed": 8,
        "age": 27,
        "teamId": "astonvilla",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "mattycash_astonvilla",
        "name": "Matty Cash",
        "position": "Sağ Bek",
        "power": 79,
        "speed": 8,
        "age": 32,
        "teamId": "astonvilla",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "lucasdigne_astonvilla",
        "name": "Lucas Digne",
        "position": "Sol Bek",
        "power": 83,
        "speed": 6,
        "age": 34,
        "teamId": "astonvilla",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "amadouonana_astonvilla",
        "name": "Amadou Onana",
        "position": "Ön Libero",
        "power": 80,
        "speed": 6,
        "age": 21,
        "teamId": "astonvilla",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "youritielemans_astonvilla",
        "name": "Youri Tielemans",
        "position": "Merkez Orta Saha",
        "power": 81,
        "speed": 8,
        "age": 34,
        "teamId": "astonvilla",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "johnmcginn_astonvilla",
        "name": "John McGinn",
        "position": "Forvet Arkası",
        "power": 83,
        "speed": 8,
        "age": 22,
        "teamId": "astonvilla",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "leonbailey_astonvilla",
        "name": "Leon Bailey",
        "position": "Sağ Kanat",
        "power": 82,
        "speed": 7,
        "age": 31,
        "teamId": "astonvilla",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "olliewatkins_astonvilla",
        "name": "Ollie Watkins",
        "position": "Sol Kanat",
        "power": 82,
        "speed": 6,
        "age": 33,
        "teamId": "astonvilla",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "jhonduran_astonvilla",
        "name": "Jhon Duran",
        "position": "Forvet",
        "power": 79,
        "speed": 8,
        "age": 30,
        "teamId": "astonvilla",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "morganrogers_astonvilla",
        "name": "Morgan Rogers",
        "position": "Forvet",
        "power": 81,
        "speed": 8,
        "age": 21,
        "teamId": "astonvilla",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "ianmaatsen_astonvilla",
        "name": "Ian Maatsen",
        "position": "Orta Saha",
        "power": 79,
        "speed": 6,
        "age": 31,
        "teamId": "astonvilla",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "rossbarkley_astonvilla",
        "name": "Ross Barkley",
        "position": "Stoper",
        "power": 80,
        "speed": 9,
        "age": 22,
        "teamId": "astonvilla",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "diegocarlos_astonvilla",
        "name": "Diego Carlos",
        "position": "Sol Bek",
        "power": 77,
        "speed": 5,
        "age": 24,
        "teamId": "astonvilla",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    }
];;
premierPlayers.forEach(p => window.leagueData.players.push(p));
