// js/data_portekiz.js
// GERCEK PORTEKIZ VERILERI
window.leagueData = window.leagueData || { teams: [], players: [] };
const portekizTeams = [
    {
        "id": "benfica",
        "name": "SL Benfica",
        "budget": 75,
        "leagueId": "portekiz"
    },
    {
        "id": "porto",
        "name": "FC Porto",
        "budget": 70,
        "leagueId": "portekiz"
    },
    {
        "id": "sporting",
        "name": "Sporting CP",
        "budget": 70,
        "leagueId": "portekiz"
    },
    {
        "id": "braga",
        "name": "SC Braga",
        "budget": 45,
        "leagueId": "portekiz"
    },
    {
        "id": "vitoria_guimaraes",
        "name": "Vitoria Guimaraes",
        "budget": 30,
        "leagueId": "portekiz"
    },
    {
        "id": "boavista",
        "name": "Boavista",
        "budget": 20,
        "leagueId": "portekiz"
    },
    {
        "id": "famalicao",
        "name": "Famalicao",
        "budget": 25,
        "leagueId": "portekiz"
    },
    {
        "id": "moreirense",
        "name": "Moreirense",
        "budget": 15,
        "leagueId": "portekiz"
    },
    {
        "id": "arouca",
        "name": "Arouca",
        "budget": 15,
        "leagueId": "portekiz"
    },
    {
        "id": "gil_vicente",
        "name": "Gil Vicente",
        "budget": 15,
        "leagueId": "portekiz"
    }
];
portekizTeams.forEach(t => window.leagueData.teams.push(t));
const portekizPlayers = [
    {
        "id": "anatoliytrubin_benfica",
        "name": "Anatoliy Trubin",
        "position": "Kaleci",
        "power": 75,
        "speed": 8,
        "age": 22,
        "teamId": "benfica",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "antoniosilva_benfica",
        "name": "Antonio Silva",
        "position": "Stoper",
        "power": 75,
        "speed": 6,
        "age": 21,
        "teamId": "benfica",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "nicolasotamendi_benfica",
        "name": "Nicolas Otamendi",
        "position": "Stoper",
        "power": 76,
        "speed": 7,
        "age": 25,
        "teamId": "benfica",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "alexanderbah_benfica",
        "name": "Alexander Bah",
        "position": "Stoper",
        "power": 80,
        "speed": 9,
        "age": 22,
        "teamId": "benfica",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "fredrikaursnes_benfica",
        "name": "Fredrik Aursnes",
        "position": "Sağ Bek",
        "power": 75,
        "speed": 9,
        "age": 30,
        "teamId": "benfica",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "joaoneves_benfica",
        "name": "Joao Neves",
        "position": "Sol Bek",
        "power": 77,
        "speed": 5,
        "age": 19,
        "teamId": "benfica",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "florentinoluis_benfica",
        "name": "Florentino Luis",
        "position": "Ön Libero",
        "power": 74,
        "speed": 7,
        "age": 19,
        "teamId": "benfica",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "orkunkokcu_benfica",
        "name": "Orkun Kokcu",
        "position": "Merkez Orta Saha",
        "power": 76,
        "speed": 7,
        "age": 21,
        "teamId": "benfica",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "keremakturkoglu_benfica",
        "name": "Kerem Akturkoglu",
        "position": "Orta Saha",
        "power": 75,
        "speed": 6,
        "age": 19,
        "teamId": "benfica",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "vangelispavlidis_benfica",
        "name": "Vangelis Pavlidis",
        "position": "Forvet Arkası",
        "power": 74,
        "speed": 5,
        "age": 31,
        "teamId": "benfica",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "angeldimaria_benfica",
        "name": "Angel Di Maria",
        "position": "Maestro",
        "power": 79,
        "speed": 8,
        "age": 29,
        "teamId": "benfica",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "arthurcabral_benfica",
        "name": "Arthur Cabral",
        "position": "Sağ Kanat",
        "power": 80,
        "speed": 7,
        "age": 28,
        "teamId": "benfica",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "marcosleonardo_benfica",
        "name": "Marcos Leonardo",
        "position": "Sol Kanat",
        "power": 80,
        "speed": 8,
        "age": 32,
        "teamId": "benfica",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "davidneres_benfica",
        "name": "David Neres",
        "position": "Forvet",
        "power": 77,
        "speed": 9,
        "age": 25,
        "teamId": "benfica",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "tomasaraujo_benfica",
        "name": "Tomas Araujo",
        "position": "Forvet",
        "power": 76,
        "speed": 8,
        "age": 31,
        "teamId": "benfica",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "diogocosta_porto",
        "name": "Diogo Costa",
        "position": "Kaleci",
        "power": 78,
        "speed": 9,
        "age": 30,
        "teamId": "porto",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "pepe_porto",
        "name": "Pepe",
        "position": "Stoper",
        "power": 80,
        "speed": 5,
        "age": 24,
        "teamId": "porto",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "otavio_porto",
        "name": "Otavio",
        "position": "Stoper",
        "power": 73,
        "speed": 5,
        "age": 25,
        "teamId": "porto",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "joaomario_porto",
        "name": "Joao Mario",
        "position": "Stoper",
        "power": 78,
        "speed": 6,
        "age": 31,
        "teamId": "porto",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "wendell_porto",
        "name": "Wendell",
        "position": "Sağ Bek",
        "power": 79,
        "speed": 9,
        "age": 25,
        "teamId": "porto",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "alanvarela_porto",
        "name": "Alan Varela",
        "position": "Sol Bek",
        "power": 78,
        "speed": 6,
        "age": 27,
        "teamId": "porto",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "nicogonzalez_porto",
        "name": "Nico Gonzalez",
        "position": "Ön Libero",
        "power": 73,
        "speed": 6,
        "age": 30,
        "teamId": "porto",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "stepheneustaquio_porto",
        "name": "Stephen Eustaquio",
        "position": "Merkez Orta Saha",
        "power": 76,
        "speed": 7,
        "age": 28,
        "teamId": "porto",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "galeno_porto",
        "name": "Galeno",
        "position": "Orta Saha",
        "power": 73,
        "speed": 6,
        "age": 30,
        "teamId": "porto",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "franciscoconceicao_porto",
        "name": "Francisco Conceicao",
        "position": "Forvet Arkası",
        "power": 76,
        "speed": 6,
        "age": 25,
        "teamId": "porto",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "evanilson_porto",
        "name": "Evanilson",
        "position": "Maestro",
        "power": 79,
        "speed": 7,
        "age": 21,
        "teamId": "porto",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "mehditaremi_porto",
        "name": "Mehdi Taremi",
        "position": "Sağ Kanat",
        "power": 75,
        "speed": 6,
        "age": 28,
        "teamId": "porto",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "pepeaquino_porto",
        "name": "Pepe Aquino",
        "position": "Sol Kanat",
        "power": 75,
        "speed": 5,
        "age": 25,
        "teamId": "porto",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "ivanjaime_porto",
        "name": "Ivan Jaime",
        "position": "Forvet",
        "power": 78,
        "speed": 7,
        "age": 19,
        "teamId": "porto",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "markogrujic_porto",
        "name": "Marko Grujic",
        "position": "Forvet",
        "power": 76,
        "speed": 6,
        "age": 27,
        "teamId": "porto",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "antonioadan_sporting",
        "name": "Antonio Adan",
        "position": "Kaleci",
        "power": 77,
        "speed": 9,
        "age": 23,
        "teamId": "sporting",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "goncaloinacio_sporting",
        "name": "Goncalo Inacio",
        "position": "Stoper",
        "power": 79,
        "speed": 8,
        "age": 29,
        "teamId": "sporting",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "ousmanediomande_sporting",
        "name": "Ousmane Diomande",
        "position": "Stoper",
        "power": 73,
        "speed": 9,
        "age": 25,
        "teamId": "sporting",
        "tacticalRole": "target_man",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "sebastiancoates_sporting",
        "name": "Sebastian Coates",
        "position": "Stoper",
        "power": 77,
        "speed": 7,
        "age": 26,
        "teamId": "sporting",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "mortenhjulmand_sporting",
        "name": "Morten Hjulmand",
        "position": "Sağ Bek",
        "power": 76,
        "speed": 6,
        "age": 20,
        "teamId": "sporting",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "hidemasamorita_sporting",
        "name": "Hidemasa Morita",
        "position": "Sol Bek",
        "power": 77,
        "speed": 9,
        "age": 30,
        "teamId": "sporting",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "nunosantos_sporting",
        "name": "Nuno Santos",
        "position": "Ön Libero",
        "power": 79,
        "speed": 8,
        "age": 19,
        "teamId": "sporting",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "pedrogoncalves_sporting",
        "name": "Pedro Goncalves",
        "position": "Merkez Orta Saha",
        "power": 79,
        "speed": 6,
        "age": 19,
        "teamId": "sporting",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "marcusedwards_sporting",
        "name": "Marcus Edwards",
        "position": "Orta Saha",
        "power": 76,
        "speed": 6,
        "age": 21,
        "teamId": "sporting",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "viktorgyokeres_sporting",
        "name": "Viktor Gyokeres",
        "position": "Forvet Arkası",
        "power": 74,
        "speed": 9,
        "age": 25,
        "teamId": "sporting",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "paulinho_sporting",
        "name": "Paulinho",
        "position": "Maestro",
        "power": 77,
        "speed": 6,
        "age": 19,
        "teamId": "sporting",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "matheusreis_sporting",
        "name": "Matheus Reis",
        "position": "Sağ Kanat",
        "power": 79,
        "speed": 9,
        "age": 20,
        "teamId": "sporting",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "ricardoesgaio_sporting",
        "name": "Ricardo Esgaio",
        "position": "Sol Kanat",
        "power": 76,
        "speed": 5,
        "age": 26,
        "teamId": "sporting",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "danielbraganca_sporting",
        "name": "Daniel Braganca",
        "position": "Forvet",
        "power": 77,
        "speed": 6,
        "age": 24,
        "teamId": "sporting",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "jeremiahstjuste_sporting",
        "name": "Jeremiah St. Juste",
        "position": "Forvet",
        "power": 78,
        "speed": 8,
        "age": 32,
        "teamId": "sporting",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "matheus_braga",
        "name": "Matheus",
        "position": "Kaleci",
        "power": 69,
        "speed": 8,
        "age": 25,
        "teamId": "braga",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "sikouniakate_braga",
        "name": "Sikou Niakate",
        "position": "Stoper",
        "power": 68,
        "speed": 6,
        "age": 23,
        "teamId": "braga",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "serdarsaatci_braga",
        "name": "Serdar Saatci",
        "position": "Stoper",
        "power": 70,
        "speed": 6,
        "age": 23,
        "teamId": "braga",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "victorgomez_braga",
        "name": "Victor Gomez",
        "position": "Stoper",
        "power": 73,
        "speed": 8,
        "age": 32,
        "teamId": "braga",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "cristianborja_braga",
        "name": "Cristian Borja",
        "position": "Sağ Bek",
        "power": 69,
        "speed": 7,
        "age": 27,
        "teamId": "braga",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "rodrigozalazar_braga",
        "name": "Rodrigo Zalazar",
        "position": "Sol Bek",
        "power": 73,
        "speed": 9,
        "age": 22,
        "teamId": "braga",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "joaomoutinho_braga",
        "name": "Joao Moutinho",
        "position": "Ön Libero",
        "power": 70,
        "speed": 6,
        "age": 26,
        "teamId": "braga",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "vitorcarvalho_braga",
        "name": "Vitor Carvalho",
        "position": "Merkez Orta Saha",
        "power": 75,
        "speed": 7,
        "age": 20,
        "teamId": "braga",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "ricardohorta_braga",
        "name": "Ricardo Horta",
        "position": "Orta Saha",
        "power": 69,
        "speed": 7,
        "age": 23,
        "teamId": "braga",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "bruma_braga",
        "name": "Bruma",
        "position": "Forvet Arkası",
        "power": 75,
        "speed": 9,
        "age": 20,
        "teamId": "braga",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "simonbanza_braga",
        "name": "Simon Banza",
        "position": "Maestro",
        "power": 70,
        "speed": 6,
        "age": 23,
        "teamId": "braga",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "abelruiz_braga",
        "name": "Abel Ruiz",
        "position": "Sağ Kanat",
        "power": 70,
        "speed": 9,
        "age": 21,
        "teamId": "braga",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "alvarodjalo_braga",
        "name": "Alvaro Djalo",
        "position": "Sol Kanat",
        "power": 68,
        "speed": 6,
        "age": 24,
        "teamId": "braga",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "ronylopes_braga",
        "name": "Rony Lopes",
        "position": "Forvet",
        "power": 70,
        "speed": 9,
        "age": 31,
        "teamId": "braga",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "paulooliveira_braga",
        "name": "Paulo Oliveira",
        "position": "Forvet",
        "power": 70,
        "speed": 5,
        "age": 30,
        "teamId": "braga",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "brunovarela_vitoria_guimaraes",
        "name": "Bruno Varela",
        "position": "Kaleci",
        "power": 62,
        "speed": 8,
        "age": 31,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "toniborevkovic_vitoria_guimaraes",
        "name": "Toni Borevkovic",
        "position": "Stoper",
        "power": 65,
        "speed": 8,
        "age": 23,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "jorgefernandes_vitoria_guimaraes",
        "name": "Jorge Fernandes",
        "position": "Stoper",
        "power": 68,
        "speed": 5,
        "age": 27,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "tomasribeiro_vitoria_guimaraes",
        "name": "Tomas Ribeiro",
        "position": "Stoper",
        "power": 66,
        "speed": 5,
        "age": 26,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "tiagosilva_vitoria_guimaraes",
        "name": "Tiago Silva",
        "position": "Sağ Bek",
        "power": 61,
        "speed": 5,
        "age": 28,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "tomashandel_vitoria_guimaraes",
        "name": "Tomas Handel",
        "position": "Sol Bek",
        "power": 68,
        "speed": 5,
        "age": 22,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "target_man",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "andreandre_vitoria_guimaraes",
        "name": "Andre Andre",
        "position": "Ön Libero",
        "power": 65,
        "speed": 7,
        "age": 31,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "ricardomangas_vitoria_guimaraes",
        "name": "Ricardo Mangas",
        "position": "Merkez Orta Saha",
        "power": 62,
        "speed": 8,
        "age": 29,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "target_man",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "brunogaspar_vitoria_guimaraes",
        "name": "Bruno Gaspar",
        "position": "Orta Saha",
        "power": 62,
        "speed": 9,
        "age": 22,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "jotasilva_vitoria_guimaraes",
        "name": "Jota Silva",
        "position": "Forvet Arkası",
        "power": 61,
        "speed": 5,
        "age": 19,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "nlsonoliveira_vitoria_guimaraes",
        "name": "Nélson Oliveira",
        "position": "Maestro",
        "power": 68,
        "speed": 6,
        "age": 32,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "kaiocsar_vitoria_guimaraes",
        "name": "Kaio César",
        "position": "Sağ Kanat",
        "power": 67,
        "speed": 5,
        "age": 30,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "mikelvillanueva_vitoria_guimaraes",
        "name": "Mikel Villanueva",
        "position": "Sol Kanat",
        "power": 65,
        "speed": 6,
        "age": 25,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "zecarlos_vitoria_guimaraes",
        "name": "Ze Carlos",
        "position": "Forvet",
        "power": 62,
        "speed": 6,
        "age": 26,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "telmoarcanjo_vitoria_guimaraes",
        "name": "Telmo Arcanjo",
        "position": "Forvet",
        "power": 68,
        "speed": 8,
        "age": 20,
        "teamId": "vitoria_guimaraes",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "joaogoncalves_boavista",
        "name": "Joao Goncalves",
        "position": "Kaleci",
        "power": 62,
        "speed": 6,
        "age": 28,
        "teamId": "boavista",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "chidozieawaziem_boavista",
        "name": "Chidozie Awaziem",
        "position": "Stoper",
        "power": 62,
        "speed": 7,
        "age": 26,
        "teamId": "boavista",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "rodrigoabascal_boavista",
        "name": "Rodrigo Abascal",
        "position": "Stoper",
        "power": 63,
        "speed": 9,
        "age": 32,
        "teamId": "boavista",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "pedromalheiro_boavista",
        "name": "Pedro Malheiro",
        "position": "Stoper",
        "power": 68,
        "speed": 6,
        "age": 25,
        "teamId": "boavista",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "brunoonyemaechi_boavista",
        "name": "Bruno Onyemaechi",
        "position": "Sağ Bek",
        "power": 63,
        "speed": 7,
        "age": 26,
        "teamId": "boavista",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "sebastianperez_boavista",
        "name": "Sebastian Perez",
        "position": "Sol Bek",
        "power": 62,
        "speed": 9,
        "age": 29,
        "teamId": "boavista",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "gaiusmakouta_boavista",
        "name": "Gaius Makouta",
        "position": "Ön Libero",
        "power": 65,
        "speed": 9,
        "age": 23,
        "teamId": "boavista",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "ilijavukotic_boavista",
        "name": "Ilija Vukotic",
        "position": "Merkez Orta Saha",
        "power": 62,
        "speed": 7,
        "age": 28,
        "teamId": "boavista",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "migueltavares_boavista",
        "name": "Miguel Tavares",
        "position": "Orta Saha",
        "power": 62,
        "speed": 8,
        "age": 26,
        "teamId": "boavista",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "salvadoragra_boavista",
        "name": "Salvador Agra",
        "position": "Forvet Arkası",
        "power": 65,
        "speed": 7,
        "age": 19,
        "teamId": "boavista",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "robertbozenik_boavista",
        "name": "Robert Bozenik",
        "position": "Maestro",
        "power": 62,
        "speed": 5,
        "age": 27,
        "teamId": "boavista",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "masakiwatai_boavista",
        "name": "Masaki Watai",
        "position": "Sağ Kanat",
        "power": 61,
        "speed": 8,
        "age": 27,
        "teamId": "boavista",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "vincentsasso_boavista",
        "name": "Vincent Sasso",
        "position": "Sol Kanat",
        "power": 64,
        "speed": 5,
        "age": 22,
        "teamId": "boavista",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "bernardosilva_boavista",
        "name": "Bernardo Silva",
        "position": "Forvet",
        "power": 67,
        "speed": 9,
        "age": 26,
        "teamId": "boavista",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "joelsilva_boavista",
        "name": "Joel Silva",
        "position": "Forvet",
        "power": 65,
        "speed": 9,
        "age": 22,
        "teamId": "boavista",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "luizjunior_famalicao",
        "name": "Luiz Junior",
        "position": "Kaleci",
        "power": 65,
        "speed": 5,
        "age": 31,
        "teamId": "famalicao",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "riccieli_famalicao",
        "name": "Riccieli",
        "position": "Stoper",
        "power": 61,
        "speed": 5,
        "age": 32,
        "teamId": "famalicao",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "eneamihaj_famalicao",
        "name": "Enea Mihaj",
        "position": "Stoper",
        "power": 65,
        "speed": 7,
        "age": 20,
        "teamId": "famalicao",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "nathan_famalicao",
        "name": "Nathan",
        "position": "Stoper",
        "power": 67,
        "speed": 7,
        "age": 26,
        "teamId": "famalicao",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "franciscomoura_famalicao",
        "name": "Francisco Moura",
        "position": "Sağ Bek",
        "power": 61,
        "speed": 9,
        "age": 19,
        "teamId": "famalicao",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "zaydouyoussouf_famalicao",
        "name": "Zaydou Youssouf",
        "position": "Sol Bek",
        "power": 68,
        "speed": 6,
        "age": 24,
        "teamId": "famalicao",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "mirkotopic_famalicao",
        "name": "Mirko Topic",
        "position": "Ön Libero",
        "power": 67,
        "speed": 8,
        "age": 23,
        "teamId": "famalicao",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "gustavoassuncao_famalicao",
        "name": "Gustavo Assuncao",
        "position": "Merkez Orta Saha",
        "power": 62,
        "speed": 7,
        "age": 31,
        "teamId": "famalicao",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "pumarodriguez_famalicao",
        "name": "Puma Rodriguez",
        "position": "Orta Saha",
        "power": 63,
        "speed": 8,
        "age": 29,
        "teamId": "famalicao",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "sorriso_famalicao",
        "name": "Sorriso",
        "position": "Forvet Arkası",
        "power": 65,
        "speed": 9,
        "age": 21,
        "teamId": "famalicao",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "jhondercadiz_famalicao",
        "name": "Jhonder Cadiz",
        "position": "Maestro",
        "power": 65,
        "speed": 5,
        "age": 19,
        "teamId": "famalicao",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "oscararanda_famalicao",
        "name": "Oscar Aranda",
        "position": "Sağ Kanat",
        "power": 68,
        "speed": 7,
        "age": 19,
        "teamId": "famalicao",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "chiquinho_famalicao",
        "name": "Chiquinho",
        "position": "Sol Kanat",
        "power": 65,
        "speed": 9,
        "age": 22,
        "teamId": "famalicao",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "martinaguirregabiria_famalicao",
        "name": "Martin Aguirregabiria",
        "position": "Forvet",
        "power": 67,
        "speed": 8,
        "age": 22,
        "teamId": "famalicao",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "filipesoares_famalicao",
        "name": "Filipe Soares",
        "position": "Forvet",
        "power": 64,
        "speed": 7,
        "age": 29,
        "teamId": "famalicao",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "kewin_moreirense",
        "name": "Kewin",
        "position": "Kaleci",
        "power": 66,
        "speed": 7,
        "age": 28,
        "teamId": "moreirense",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "marcelo_moreirense",
        "name": "Marcelo",
        "position": "Stoper",
        "power": 64,
        "speed": 9,
        "age": 21,
        "teamId": "moreirense",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "maracas_moreirense",
        "name": "Maracas",
        "position": "Stoper",
        "power": 61,
        "speed": 7,
        "age": 19,
        "teamId": "moreirense",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "fabiano_moreirense",
        "name": "Fabiano",
        "position": "Stoper",
        "power": 67,
        "speed": 5,
        "age": 21,
        "teamId": "moreirense",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "godfriedfrimpong_moreirense",
        "name": "Godfried Frimpong",
        "position": "Sağ Bek",
        "power": 67,
        "speed": 9,
        "age": 22,
        "teamId": "moreirense",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "goncalofranco_moreirense",
        "name": "Goncalo Franco",
        "position": "Sol Bek",
        "power": 67,
        "speed": 6,
        "age": 27,
        "teamId": "moreirense",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "lawrenceofori_moreirense",
        "name": "Lawrence Ofori",
        "position": "Ön Libero",
        "power": 67,
        "speed": 8,
        "age": 29,
        "teamId": "moreirense",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "alan_moreirense",
        "name": "Alan",
        "position": "Merkez Orta Saha",
        "power": 67,
        "speed": 8,
        "age": 26,
        "teamId": "moreirense",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "madson_moreirense",
        "name": "Madson",
        "position": "Orta Saha",
        "power": 62,
        "speed": 5,
        "age": 28,
        "teamId": "moreirense",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "joaocamacho_moreirense",
        "name": "Joao Camacho",
        "position": "Forvet Arkası",
        "power": 67,
        "speed": 6,
        "age": 23,
        "teamId": "moreirense",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "matheusaias_moreirense",
        "name": "Matheus Aias",
        "position": "Maestro",
        "power": 68,
        "speed": 5,
        "age": 20,
        "teamId": "moreirense",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "kobamelokodisang_moreirense",
        "name": "Kobamelo Kodisang",
        "position": "Sağ Kanat",
        "power": 67,
        "speed": 8,
        "age": 20,
        "teamId": "moreirense",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "dinispinto_moreirense",
        "name": "Dinis Pinto",
        "position": "Sol Kanat",
        "power": 67,
        "speed": 9,
        "age": 26,
        "teamId": "moreirense",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "alanzinho_moreirense",
        "name": "Alanzinho",
        "position": "Forvet",
        "power": 62,
        "speed": 6,
        "age": 30,
        "teamId": "moreirense",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "jeremyantonisse_moreirense",
        "name": "Jeremy Antonisse",
        "position": "Forvet",
        "power": 63,
        "speed": 7,
        "age": 24,
        "teamId": "moreirense",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "ignaciodearruabarrena_arouca",
        "name": "Ignacio de Arruabarrena",
        "position": "Kaleci",
        "power": 65,
        "speed": 7,
        "age": 19,
        "teamId": "arouca",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "matiasrocha_arouca",
        "name": "Matias Rocha",
        "position": "Stoper",
        "power": 66,
        "speed": 9,
        "age": 23,
        "teamId": "arouca",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "javimontero_arouca",
        "name": "Javi Montero",
        "position": "Stoper",
        "power": 61,
        "speed": 6,
        "age": 19,
        "teamId": "arouca",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "bogdanmilovanov_arouca",
        "name": "Bogdan Milovanov",
        "position": "Stoper",
        "power": 62,
        "speed": 9,
        "age": 32,
        "teamId": "arouca",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "weverson_arouca",
        "name": "Weverson",
        "position": "Sağ Bek",
        "power": 62,
        "speed": 9,
        "age": 22,
        "teamId": "arouca",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "davidsimao_arouca",
        "name": "David Simao",
        "position": "Sol Bek",
        "power": 62,
        "speed": 5,
        "age": 25,
        "teamId": "arouca",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "morlayesylla_arouca",
        "name": "Morlaye Sylla",
        "position": "Ön Libero",
        "power": 64,
        "speed": 9,
        "age": 31,
        "teamId": "arouca",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "pedrosantos_arouca",
        "name": "Pedro Santos",
        "position": "Merkez Orta Saha",
        "power": 65,
        "speed": 5,
        "age": 23,
        "teamId": "arouca",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "jason_arouca",
        "name": "Jason",
        "position": "Orta Saha",
        "power": 61,
        "speed": 9,
        "age": 29,
        "teamId": "arouca",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "cristogonzalez_arouca",
        "name": "Cristo Gonzalez",
        "position": "Forvet Arkası",
        "power": 65,
        "speed": 8,
        "age": 21,
        "teamId": "arouca",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "rafamujica_arouca",
        "name": "Rafa Mujica",
        "position": "Maestro",
        "power": 61,
        "speed": 6,
        "age": 20,
        "teamId": "arouca",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "alfonsotrezza_arouca",
        "name": "Alfonso Trezza",
        "position": "Sağ Kanat",
        "power": 63,
        "speed": 7,
        "age": 22,
        "teamId": "arouca",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "ebouekouassi_arouca",
        "name": "Eboue Kouassi",
        "position": "Sol Kanat",
        "power": 67,
        "speed": 7,
        "age": 25,
        "teamId": "arouca",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "tiagoesgaio_arouca",
        "name": "Tiago Esgaio",
        "position": "Forvet",
        "power": 68,
        "speed": 9,
        "age": 30,
        "teamId": "arouca",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "ninogalovic_arouca",
        "name": "Nino Galovic",
        "position": "Forvet",
        "power": 63,
        "speed": 5,
        "age": 29,
        "teamId": "arouca",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "andrew_gil_vicente",
        "name": "Andrew",
        "position": "Kaleci",
        "power": 67,
        "speed": 7,
        "age": 29,
        "teamId": "gil_vicente",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "gabrielpereira_gil_vicente",
        "name": "Gabriel Pereira",
        "position": "Stoper",
        "power": 64,
        "speed": 6,
        "age": 28,
        "teamId": "gil_vicente",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "rubenfernandes_gil_vicente",
        "name": "Ruben Fernandes",
        "position": "Stoper",
        "power": 63,
        "speed": 7,
        "age": 28,
        "teamId": "gil_vicente",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "alexpinto_gil_vicente",
        "name": "Alex Pinto",
        "position": "Stoper",
        "power": 63,
        "speed": 7,
        "age": 24,
        "teamId": "gil_vicente",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": "leonardobuta_gil_vicente",
        "name": "Leonardo Buta",
        "position": "Sağ Bek",
        "power": 61,
        "speed": 9,
        "age": 26,
        "teamId": "gil_vicente",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "kanyafujimoto_gil_vicente",
        "name": "Kanya Fujimoto",
        "position": "Sol Bek",
        "power": 63,
        "speed": 6,
        "age": 32,
        "teamId": "gil_vicente",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "pedrotiba_gil_vicente",
        "name": "Pedro Tiba",
        "position": "Ön Libero",
        "power": 61,
        "speed": 7,
        "age": 30,
        "teamId": "gil_vicente",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "morygbane_gil_vicente",
        "name": "Mory Gbane",
        "position": "Merkez Orta Saha",
        "power": 66,
        "speed": 9,
        "age": 22,
        "teamId": "gil_vicente",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "felixcorreia_gil_vicente",
        "name": "Felix Correia",
        "position": "Orta Saha",
        "power": 61,
        "speed": 9,
        "age": 29,
        "teamId": "gil_vicente",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "murilo_gil_vicente",
        "name": "Murilo",
        "position": "Forvet Arkası",
        "power": 66,
        "speed": 9,
        "age": 32,
        "teamId": "gil_vicente",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "alialipour_gil_vicente",
        "name": "Ali Alipour",
        "position": "Maestro",
        "power": 61,
        "speed": 9,
        "age": 22,
        "teamId": "gil_vicente",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "rokobaturina_gil_vicente",
        "name": "Roko Baturina",
        "position": "Sağ Kanat",
        "power": 62,
        "speed": 7,
        "age": 25,
        "teamId": "gil_vicente",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": "zecarlos_gil_vicente",
        "name": "Ze Carlos",
        "position": "Sol Kanat",
        "power": 66,
        "speed": 9,
        "age": 27,
        "teamId": "gil_vicente",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": "maximedominguez_gil_vicente",
        "name": "Maxime Dominguez",
        "position": "Forvet",
        "power": 63,
        "speed": 7,
        "age": 22,
        "teamId": "gil_vicente",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": "tidjanytour_gil_vicente",
        "name": "Tidjany Touré",
        "position": "Forvet",
        "power": 66,
        "speed": 5,
        "age": 28,
        "teamId": "gil_vicente",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    }
];
portekizPlayers.forEach(p => window.leagueData.players.push(p));
