// js/data_ligue1.js
// GERCEK LIGUE 1 VERILERI (2026/2027)

window.leagueData = window.leagueData || { teams: [], players: [] };

const ligue1Teams = [
    {
        "id": "psg",
        "name": "Paris Saint-Germain",
        "budget": 95,
        "leagueId": "ligue1"
    },
    {
        "id": "monaco",
        "name": "AS Monaco",
        "budget": 75,
        "leagueId": "ligue1"
    },
    {
        "id": "marseille",
        "name": "Olympique Marseille",
        "budget": 70,
        "leagueId": "ligue1"
    },
    {
        "id": "lille",
        "name": "LOSC Lille",
        "budget": 65,
        "leagueId": "ligue1"
    },
    {
        "id": "lyon",
        "name": "Olympique Lyon",
        "budget": 65,
        "leagueId": "ligue1"
    },
    {
        "id": "lens",
        "name": "RC Lens",
        "budget": 60,
        "leagueId": "ligue1"
    },
    {
        "id": "nice",
        "name": "OGC Nice",
        "budget": 60,
        "leagueId": "ligue1"
    },
    {
        "id": "rennes",
        "name": "Stade Rennais",
        "budget": 60,
        "leagueId": "ligue1"
    },
    {
        "id": "reims",
        "name": "Stade de Reims",
        "budget": 50,
        "leagueId": "ligue1"
    },
    {
        "id": "toulouse",
        "name": "Toulouse FC",
        "budget": 45,
        "leagueId": "ligue1"
    },
    {
        "id": "montpellier",
        "name": "Montpellier HSC",
        "budget": 40,
        "leagueId": "ligue1"
    },
    {
        "id": "strasbourg",
        "name": "RC Strasbourg",
        "budget": 40,
        "leagueId": "ligue1"
    },
    {
        "id": "nantes",
        "name": "FC Nantes",
        "budget": 35,
        "leagueId": "ligue1"
    },
    {
        "id": "lehavre",
        "name": "Le Havre AC",
        "budget": 30,
        "leagueId": "ligue1"
    },
    {
        "id": "brest",
        "name": "Stade Brestois",
        "budget": 50,
        "leagueId": "ligue1"
    }
];
ligue1Teams.forEach(t => window.leagueData.teams.push(t));

const ligue1Players = [
    {
        "id": 730821,
        "name": "Gianluigi Donnarumma",
        "position": "Kaleci",
        "power": 83,
        "speed": 6,
        "age": 21,
        birthplace: "Strasbourg, Fransa", "teamId": "psg",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 601309,
        "name": "Marquinhos",
        "position": "Stoper",
        "power": 87,
        "speed": 9,
        "age": 31,
        birthplace: "Nice, Fransa", "teamId": "psg",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 775658,
        "name": "Milan Skriniar",
        "position": "Stoper",
        "power": 83,
        "speed": 7,
        "age": 21,
        birthplace: "Bordeaux, Fransa", "teamId": "psg",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 379916,
        "name": "Lucas Hernandez",
        "position": "Stoper",
        "power": 87,
        "speed": 6,
        "age": 27,
        birthplace: "Lyon, Fransa", "teamId": "psg",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 798584,
        "name": "Achraf Hakimi",
        "position": "Sağ Bek",
        "power": 86,
        "speed": 6,
        "age": 24,
        birthplace: "Paris, Fransa", "teamId": "psg",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 995474,
        "name": "Nuno Mendes",
        "position": "Sol Bek",
        "power": 84,
        "speed": 9,
        "age": 28,
        birthplace: "Nantes, Fransa", "teamId": "psg",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 175575,
        "name": "Warren Zaire-Emery",
        "position": "Ön Libero",
        "power": 85,
        "speed": 6,
        "age": 29,
        birthplace: "Paris, Fransa", "teamId": "psg",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 452930,
        "name": "Vitinha",
        "position": "Merkez Orta Saha",
        "power": 87,
        "speed": 6,
        "age": 29,
        birthplace: "Paris, Fransa", "teamId": "psg",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 391979,
        "name": "Fabian Ruiz",
        "position": "Orta Saha",
        "power": 81,
        "speed": 9,
        "age": 28,
        birthplace: "Marseille, Fransa", "teamId": "psg",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 201247,
        "name": "Ousmane Dembele",
        "position": "Forvet Arkası",
        "power": 82,
        "speed": 6,
        "age": 24,
        birthplace: "Marseille, Fransa", "teamId": "psg",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 863945,
        "name": "Bradley Barcola",
        "position": "Maestro",
        "power": 81,
        "speed": 7,
        "age": 21,
        birthplace: "Nice, Fransa", "teamId": "psg",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 793392,
        "name": "Goncalo Ramos",
        "position": "Sağ Kanat",
        "power": 80,
        "speed": 7,
        "age": 31,
        birthplace: "Lyon, Fransa", "teamId": "psg",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 110485,
        "name": "Randal Kolo Muani",
        "position": "Sol Kanat",
        "power": 84,
        "speed": 5,
        "age": 22,
        birthplace: "Nice, Fransa", "teamId": "psg",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 468092,
        "name": "Lucas Beraldo",
        "position": "Forvet",
        "power": 81,
        "speed": 7,
        "age": 27,
        birthplace: "Bordeaux, Fransa", "teamId": "psg",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 102005,
        "name": "Marco Asensio",
        "position": "Forvet",
        "power": 80,
        "speed": 5,
        "age": 32,
        birthplace: "Strasbourg, Fransa", "teamId": "psg",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 227368,
        "name": "Radoslaw Majecki",
        "position": "Kaleci",
        "power": 78,
        "speed": 9,
        "age": 24,
        birthplace: "Toulouse, Fransa", "teamId": "monaco",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 838213,
        "name": "Guillermo Maripan",
        "position": "Stoper",
        "power": 79,
        "speed": 9,
        "age": 31,
        birthplace: "Montpellier, Fransa", "teamId": "monaco",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 333998,
        "name": "Mohammed Salisu",
        "position": "Stoper",
        "power": 78,
        "speed": 6,
        "age": 28,
        birthplace: "Lille, Fransa", "teamId": "monaco",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 254207,
        "name": "Thilo Kehrer",
        "position": "Stoper",
        "power": 80,
        "speed": 8,
        "age": 27,
        birthplace: "Toulouse, Fransa", "teamId": "monaco",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 470030,
        "name": "Vanderson",
        "position": "Sağ Bek",
        "power": 73,
        "speed": 9,
        "age": 32,
        birthplace: "Lyon, Fransa", "teamId": "monaco",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 672776,
        "name": "Youssouf Fofana",
        "position": "Sol Bek",
        "power": 78,
        "speed": 6,
        "age": 26,
        birthplace: "Montpellier, Fransa", "teamId": "monaco",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 819899,
        "name": "Denis Zakaria",
        "position": "Ön Libero",
        "power": 76,
        "speed": 7,
        "age": 25,
        birthplace: "Montpellier, Fransa", "teamId": "monaco",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 252529,
        "name": "Aleksandr Golovin",
        "position": "Merkez Orta Saha",
        "power": 80,
        "speed": 9,
        "age": 31,
        birthplace: "Nantes, Fransa", "teamId": "monaco",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 415974,
        "name": "Takumi Minamino",
        "position": "Orta Saha",
        "power": 74,
        "speed": 6,
        "age": 30,
        birthplace: "Paris, Fransa", "teamId": "monaco",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 260071,
        "name": "Wissam Ben Yedder",
        "position": "Forvet Arkası",
        "power": 78,
        "speed": 6,
        "age": 32,
        birthplace: "Paris, Fransa", "teamId": "monaco",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 146895,
        "name": "Folarin Balogun",
        "position": "Maestro",
        "power": 78,
        "speed": 5,
        "age": 32,
        birthplace: "Paris, Fransa", "teamId": "monaco",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 506987,
        "name": "Maghnes Akliouche",
        "position": "Sağ Kanat",
        "power": 77,
        "speed": 7,
        "age": 25,
        birthplace: "Paris, Fransa", "teamId": "monaco",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 953272,
        "name": "Eliesse Ben Seghir",
        "position": "Sol Kanat",
        "power": 76,
        "speed": 8,
        "age": 20,
        birthplace: "Paris, Fransa", "teamId": "monaco",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 930103,
        "name": "Ismail Jakobs",
        "position": "Forvet",
        "power": 78,
        "speed": 8,
        "age": 32,
        birthplace: "Nice, Fransa", "teamId": "monaco",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 947455,
        "name": "Breel Embolo",
        "position": "Forvet",
        "power": 77,
        "speed": 6,
        "age": 27,
        birthplace: "Strasbourg, Fransa", "teamId": "monaco",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 479255,
        "name": "Pau Lopez",
        "position": "Kaleci",
        "power": 80,
        "speed": 7,
        "age": 22,
        birthplace: "Marseille, Fransa", "teamId": "marseille",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 571028,
        "name": "Chancel Mbemba",
        "position": "Stoper",
        "power": 77,
        "speed": 5,
        "age": 31,
        birthplace: "Marseille, Fransa", "teamId": "marseille",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 529116,
        "name": "Leonardo Balerdi",
        "position": "Stoper",
        "power": 75,
        "speed": 8,
        "age": 23,
        birthplace: "Toulouse, Fransa", "teamId": "marseille",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 669850,
        "name": "Samuel Gigot",
        "position": "Stoper",
        "power": 80,
        "speed": 7,
        "age": 31,
        birthplace: "Strasbourg, Fransa", "teamId": "marseille",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 756962,
        "name": "Jonathan Clauss",
        "position": "Sağ Bek",
        "power": 74,
        "speed": 5,
        "age": 23,
        birthplace: "Nantes, Fransa", "teamId": "marseille",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 842409,
        "name": "Jordan Veretout",
        "position": "Sol Bek",
        "power": 75,
        "speed": 7,
        "age": 28,
        birthplace: "Nice, Fransa", "teamId": "marseille",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 449932,
        "name": "Geoffrey Kondogbia",
        "position": "Ön Libero",
        "power": 78,
        "speed": 9,
        "age": 22,
        birthplace: "Nantes, Fransa", "teamId": "marseille",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 936671,
        "name": "Valentin Rongier",
        "position": "Merkez Orta Saha",
        "power": 79,
        "speed": 9,
        "age": 21,
        birthplace: "Bordeaux, Fransa", "teamId": "marseille",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 952525,
        "name": "Amine Harit",
        "position": "Orta Saha",
        "power": 79,
        "speed": 8,
        "age": 19,
        birthplace: "Nantes, Fransa", "teamId": "marseille",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 133358,
        "name": "Pierre-Emerick Aubameyang",
        "position": "Forvet Arkası",
        "power": 77,
        "speed": 5,
        "age": 25,
        birthplace: "Strasbourg, Fransa", "teamId": "marseille",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 796603,
        "name": "Iliman Ndiaye",
        "position": "Maestro",
        "power": 75,
        "speed": 6,
        "age": 31,
        birthplace: "Nice, Fransa", "teamId": "marseille",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 523877,
        "name": "Ismaila Sarr",
        "position": "Sağ Kanat",
        "power": 76,
        "speed": 6,
        "age": 27,
        birthplace: "Lyon, Fransa", "teamId": "marseille",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 339034,
        "name": "Faris Moumbagna",
        "position": "Sol Kanat",
        "power": 76,
        "speed": 6,
        "age": 25,
        birthplace: "Bordeaux, Fransa", "teamId": "marseille",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 542981,
        "name": "Quentin Merlin",
        "position": "Forvet",
        "power": 76,
        "speed": 5,
        "age": 28,
        birthplace: "Strasbourg, Fransa", "teamId": "marseille",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 200765,
        "name": "Ulisses Garcia",
        "position": "Forvet",
        "power": 78,
        "speed": 5,
        "age": 20,
        birthplace: "Lille, Fransa", "teamId": "marseille",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 235078,
        "name": "Lucas Chevalier",
        "position": "Kaleci",
        "power": 71,
        "speed": 7,
        "age": 32,
        birthplace: "Nice, Fransa", "teamId": "lille",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 407126,
        "name": "Leny Yoro",
        "position": "Stoper",
        "power": 70,
        "speed": 9,
        "age": 22,
        birthplace: "Paris, Fransa", "teamId": "lille",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 593124,
        "name": "Alexsandro",
        "position": "Stoper",
        "power": 72,
        "speed": 8,
        "age": 26,
        birthplace: "Toulouse, Fransa", "teamId": "lille",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 634775,
        "name": "Bafode Diakite",
        "position": "Stoper",
        "power": 70,
        "speed": 5,
        "age": 21,
        birthplace: "Strasbourg, Fransa", "teamId": "lille",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 283982,
        "name": "Ismaily",
        "position": "Sağ Bek",
        "power": 70,
        "speed": 7,
        "age": 26,
        birthplace: "Nice, Fransa", "teamId": "lille",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 399822,
        "name": "Benjamin Andre",
        "position": "Sol Bek",
        "power": 73,
        "speed": 6,
        "age": 22,
        birthplace: "Marseille, Fransa", "teamId": "lille",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 971269,
        "name": "Nabil Bentaleb",
        "position": "Ön Libero",
        "power": 71,
        "speed": 9,
        "age": 23,
        birthplace: "Toulouse, Fransa", "teamId": "lille",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 404138,
        "name": "Angel Gomes",
        "position": "Merkez Orta Saha",
        "power": 68,
        "speed": 6,
        "age": 30,
        birthplace: "Paris, Fransa", "teamId": "lille",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 597570,
        "name": "Edon Zhegrova",
        "position": "Orta Saha",
        "power": 73,
        "speed": 7,
        "age": 28,
        birthplace: "Strasbourg, Fransa", "teamId": "lille",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 937289,
        "name": "Jonathan David",
        "position": "Forvet Arkası",
        "power": 74,
        "speed": 8,
        "age": 28,
        birthplace: "Nantes, Fransa", "teamId": "lille",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 530761,
        "name": "Hakon Arnar Haraldsson",
        "position": "Maestro",
        "power": 69,
        "speed": 5,
        "age": 21,
        birthplace: "Toulouse, Fransa", "teamId": "lille",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 702260,
        "name": "Remy Cabella",
        "position": "Sağ Kanat",
        "power": 74,
        "speed": 9,
        "age": 21,
        birthplace: "Nice, Fransa", "teamId": "lille",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 181218,
        "name": "Tiago Santos",
        "position": "Sol Kanat",
        "power": 70,
        "speed": 5,
        "age": 26,
        birthplace: "Bordeaux, Fransa", "teamId": "lille",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 551310,
        "name": "Ivan Cavaleiro",
        "position": "Forvet",
        "power": 70,
        "speed": 9,
        "age": 22,
        birthplace: "Paris, Fransa", "teamId": "lille",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 209003,
        "name": "Gudmundsson",
        "position": "Forvet",
        "power": 71,
        "speed": 6,
        "age": 24,
        birthplace: "Paris, Fransa", "teamId": "lille",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 706427,
        "name": "Anthony Lopes",
        "position": "Kaleci",
        "power": 70,
        "speed": 9,
        "age": 22,
        birthplace: "Toulouse, Fransa", "teamId": "lyon",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 820818,
        "name": "Jake O'Brien",
        "position": "Stoper",
        "power": 75,
        "speed": 5,
        "age": 30,
        birthplace: "Toulouse, Fransa", "teamId": "lyon",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 337219,
        "name": "Duje Caleta-Car",
        "position": "Stoper",
        "power": 74,
        "speed": 8,
        "age": 24,
        birthplace: "Nice, Fransa", "teamId": "lyon",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 180768,
        "name": "Clinton Mata",
        "position": "Stoper",
        "power": 73,
        "speed": 5,
        "age": 26,
        birthplace: "Nantes, Fransa", "teamId": "lyon",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 982607,
        "name": "Nicolas Tagliafico",
        "position": "Sağ Bek",
        "power": 70,
        "speed": 9,
        "age": 32,
        birthplace: "Montpellier, Fransa", "teamId": "lyon",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 134710,
        "name": "Nemanja Matic",
        "position": "Sol Bek",
        "power": 70,
        "speed": 8,
        "age": 24,
        birthplace: "Paris, Fransa", "teamId": "lyon",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 657238,
        "name": "Maxence Caqueret",
        "position": "Ön Libero",
        "power": 69,
        "speed": 9,
        "age": 30,
        birthplace: "Toulouse, Fransa", "teamId": "lyon",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 820289,
        "name": "Corentin Tolisso",
        "position": "Merkez Orta Saha",
        "power": 71,
        "speed": 9,
        "age": 27,
        birthplace: "Paris, Fransa", "teamId": "lyon",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 945296,
        "name": "Said Benrahma",
        "position": "Orta Saha",
        "power": 70,
        "speed": 7,
        "age": 20,
        birthplace: "Lille, Fransa", "teamId": "lyon",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 812550,
        "name": "Alexandre Lacazette",
        "position": "Forvet Arkası",
        "power": 72,
        "speed": 8,
        "age": 23,
        birthplace: "Nice, Fransa", "teamId": "lyon",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 605179,
        "name": "Ernest Nuamah",
        "position": "Maestro",
        "power": 69,
        "speed": 8,
        "age": 25,
        birthplace: "Montpellier, Fransa", "teamId": "lyon",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 645225,
        "name": "Gift Orban",
        "position": "Sağ Kanat",
        "power": 69,
        "speed": 9,
        "age": 30,
        birthplace: "Lyon, Fransa", "teamId": "lyon",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 605360,
        "name": "Rayan Cherki",
        "position": "Sol Kanat",
        "power": 71,
        "speed": 5,
        "age": 31,
        birthplace: "Montpellier, Fransa", "teamId": "lyon",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 878846,
        "name": "Maitland-Niles",
        "position": "Forvet",
        "power": 75,
        "speed": 9,
        "age": 24,
        birthplace: "Nice, Fransa", "teamId": "lyon",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 430546,
        "name": "Orel Mangala",
        "position": "Forvet",
        "power": 68,
        "speed": 7,
        "age": 30,
        birthplace: "Toulouse, Fransa", "teamId": "lyon",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 522844,
        "name": "Brice Samba",
        "position": "Kaleci",
        "power": 68,
        "speed": 9,
        "age": 30,
        birthplace: "Marseille, Fransa", "teamId": "lens",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 321753,
        "name": "Kevin Danso",
        "position": "Stoper",
        "power": 75,
        "speed": 6,
        "age": 21,
        birthplace: "Strasbourg, Fransa", "teamId": "lens",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 774153,
        "name": "Facundo Medina",
        "position": "Stoper",
        "power": 71,
        "speed": 6,
        "age": 28,
        birthplace: "Paris, Fransa", "teamId": "lens",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 283253,
        "name": "Jonathan Gradit",
        "position": "Stoper",
        "power": 68,
        "speed": 6,
        "age": 23,
        birthplace: "Strasbourg, Fransa", "teamId": "lens",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 963818,
        "name": "Przemyslaw Frankowski",
        "position": "Sağ Bek",
        "power": 72,
        "speed": 6,
        "age": 26,
        birthplace: "Toulouse, Fransa", "teamId": "lens",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 410976,
        "name": "Salis Abdul Samed",
        "position": "Sol Bek",
        "power": 74,
        "speed": 9,
        "age": 26,
        birthplace: "Montpellier, Fransa", "teamId": "lens",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 684657,
        "name": "Nampalys Mendy",
        "position": "Ön Libero",
        "power": 74,
        "speed": 6,
        "age": 29,
        birthplace: "Lille, Fransa", "teamId": "lens",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 591083,
        "name": "David Pereira da Costa",
        "position": "Merkez Orta Saha",
        "power": 72,
        "speed": 9,
        "age": 31,
        birthplace: "Lyon, Fransa", "teamId": "lens",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 561201,
        "name": "Florian Sotoca",
        "position": "Orta Saha",
        "power": 74,
        "speed": 7,
        "age": 24,
        birthplace: "Strasbourg, Fransa", "teamId": "lens",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 251491,
        "name": "Elye Wahi",
        "position": "Forvet Arkası",
        "power": 69,
        "speed": 5,
        "age": 29,
        birthplace: "Lille, Fransa", "teamId": "lens",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 716836,
        "name": "Wesley Said",
        "position": "Maestro",
        "power": 72,
        "speed": 8,
        "age": 28,
        birthplace: "Toulouse, Fransa", "teamId": "lens",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 613737,
        "name": "Deiver Machado",
        "position": "Sağ Kanat",
        "power": 68,
        "speed": 5,
        "age": 30,
        birthplace: "Paris, Fransa", "teamId": "lens",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 677332,
        "name": "Ruben Aguilar",
        "position": "Sol Kanat",
        "power": 71,
        "speed": 7,
        "age": 28,
        birthplace: "Marseille, Fransa", "teamId": "lens",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 767705,
        "name": "Adrien Thomasson",
        "position": "Forvet",
        "power": 71,
        "speed": 6,
        "age": 29,
        birthplace: "Bordeaux, Fransa", "teamId": "lens",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 836561,
        "name": "Angelo Fulgini",
        "position": "Forvet",
        "power": 68,
        "speed": 9,
        "age": 22,
        birthplace: "Montpellier, Fransa", "teamId": "lens",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 544955,
        "name": "Marcin Bulka",
        "position": "Kaleci",
        "power": 69,
        "speed": 5,
        "age": 32,
        birthplace: "Montpellier, Fransa", "teamId": "nice",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 815919,
        "name": "Jean-Clair Todibo",
        "position": "Stoper",
        "power": 70,
        "speed": 8,
        "age": 31,
        birthplace: "Marseille, Fransa", "teamId": "nice",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 306334,
        "name": "Dante",
        "position": "Stoper",
        "power": 69,
        "speed": 9,
        "age": 26,
        birthplace: "Nice, Fransa", "teamId": "nice",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 261253,
        "name": "Melvin Bard",
        "position": "Stoper",
        "power": 71,
        "speed": 9,
        "age": 28,
        birthplace: "Lyon, Fransa", "teamId": "nice",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 641428,
        "name": "Jordan Lotomba",
        "position": "Sağ Bek",
        "power": 70,
        "speed": 7,
        "age": 27,
        birthplace: "Toulouse, Fransa", "teamId": "nice",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 989896,
        "name": "Khephren Thuram",
        "position": "Sol Bek",
        "power": 72,
        "speed": 8,
        "age": 28,
        birthplace: "Lille, Fransa", "teamId": "nice",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 954074,
        "name": "Morgan Sanson",
        "position": "Ön Libero",
        "power": 75,
        "speed": 8,
        "age": 26,
        birthplace: "Nantes, Fransa", "teamId": "nice",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 289577,
        "name": "Hicham Boudaoui",
        "position": "Merkez Orta Saha",
        "power": 70,
        "speed": 8,
        "age": 22,
        birthplace: "Marseille, Fransa", "teamId": "nice",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 948290,
        "name": "Jeremie Boga",
        "position": "Orta Saha",
        "power": 68,
        "speed": 8,
        "age": 24,
        birthplace: "Montpellier, Fransa", "teamId": "nice",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 107071,
        "name": "Terem Moffi",
        "position": "Forvet Arkası",
        "power": 74,
        "speed": 7,
        "age": 32,
        birthplace: "Marseille, Fransa", "teamId": "nice",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 191165,
        "name": "Gaetan Laborde",
        "position": "Maestro",
        "power": 72,
        "speed": 9,
        "age": 24,
        birthplace: "Bordeaux, Fransa", "teamId": "nice",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 950438,
        "name": "Evann Guessand",
        "position": "Sağ Kanat",
        "power": 70,
        "speed": 7,
        "age": 26,
        birthplace: "Bordeaux, Fransa", "teamId": "nice",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 207409,
        "name": "Youssouf Ndayishimiye",
        "position": "Sol Kanat",
        "power": 71,
        "speed": 5,
        "age": 31,
        birthplace: "Bordeaux, Fransa", "teamId": "nice",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 402290,
        "name": "Tom Louchet",
        "position": "Forvet",
        "power": 74,
        "speed": 8,
        "age": 31,
        birthplace: "Nantes, Fransa", "teamId": "nice",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 752479,
        "name": "Valentin Rosier",
        "position": "Forvet",
        "power": 69,
        "speed": 9,
        "age": 32,
        birthplace: "Nantes, Fransa", "teamId": "nice",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 931808,
        "name": "Steve Mandanda",
        "position": "Kaleci",
        "power": 68,
        "speed": 7,
        "age": 20,
        birthplace: "Montpellier, Fransa", "teamId": "rennes",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 361507,
        "name": "Arthur Theate",
        "position": "Stoper",
        "power": 70,
        "speed": 5,
        "age": 19,
        birthplace: "Bordeaux, Fransa", "teamId": "rennes",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 288528,
        "name": "Warmed Omari",
        "position": "Stoper",
        "power": 72,
        "speed": 5,
        "age": 27,
        birthplace: "Paris, Fransa", "teamId": "rennes",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 640351,
        "name": "Adrien Truffert",
        "position": "Stoper",
        "power": 71,
        "speed": 5,
        "age": 29,
        birthplace: "Nice, Fransa", "teamId": "rennes",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 934597,
        "name": "Guela Doue",
        "position": "Sağ Bek",
        "power": 70,
        "speed": 6,
        "age": 22,
        birthplace: "Lyon, Fransa", "teamId": "rennes",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 543282,
        "name": "Baptiste Santamaria",
        "position": "Sol Bek",
        "power": 74,
        "speed": 7,
        "age": 24,
        birthplace: "Toulouse, Fransa", "teamId": "rennes",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 297186,
        "name": "Benjamin Bourigeaud",
        "position": "Ön Libero",
        "power": 71,
        "speed": 9,
        "age": 30,
        birthplace: "Marseille, Fransa", "teamId": "rennes",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 636437,
        "name": "Enzo Le Fee",
        "position": "Merkez Orta Saha",
        "power": 71,
        "speed": 7,
        "age": 22,
        birthplace: "Paris, Fransa", "teamId": "rennes",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 646788,
        "name": "Desire Doue",
        "position": "Orta Saha",
        "power": 73,
        "speed": 6,
        "age": 31,
        birthplace: "Marseille, Fransa", "teamId": "rennes",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 573656,
        "name": "Martin Terrier",
        "position": "Forvet Arkası",
        "power": 68,
        "speed": 8,
        "age": 25,
        birthplace: "Lille, Fransa", "teamId": "rennes",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 528811,
        "name": "Amine Gouiri",
        "position": "Maestro",
        "power": 68,
        "speed": 9,
        "age": 26,
        birthplace: "Marseille, Fransa", "teamId": "rennes",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 204401,
        "name": "Arnaud Kalimuendo",
        "position": "Sağ Kanat",
        "power": 72,
        "speed": 9,
        "age": 22,
        birthplace: "Montpellier, Fransa", "teamId": "rennes",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 206123,
        "name": "Ludovic Blas",
        "position": "Sol Kanat",
        "power": 68,
        "speed": 8,
        "age": 29,
        birthplace: "Bordeaux, Fransa", "teamId": "rennes",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 772274,
        "name": "Azor Matusiwa",
        "position": "Forvet",
        "power": 71,
        "speed": 9,
        "age": 20,
        birthplace: "Nantes, Fransa", "teamId": "rennes",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 902387,
        "name": "Christopher Wooh",
        "position": "Forvet",
        "power": 71,
        "speed": 7,
        "age": 32,
        birthplace: "Montpellier, Fransa", "teamId": "rennes",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 612723,
        "name": "Yehvann Diouf",
        "position": "Kaleci",
        "power": 67,
        "speed": 6,
        "age": 23,
        birthplace: "Marseille, Fransa", "teamId": "reims",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 903640,
        "name": "Yunis Abdelhamid",
        "position": "Stoper",
        "power": 65,
        "speed": 7,
        "age": 24,
        birthplace: "Nantes, Fransa", "teamId": "reims",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },

    {
        "id": 790245,
        "name": "Thomas Foket",
        "position": "Stoper",
        "power": 67,
        "speed": 8,
        "age": 32,
        birthplace: "Toulouse, Fransa", "teamId": "reims",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 228117,
        "name": "Thibault De Smet",
        "position": "Sağ Bek",
        "power": 65,
        "speed": 7,
        "age": 31,
        birthplace: "Marseille, Fransa", "teamId": "reims",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 718509,
        "name": "Marshall Munetsi",
        "position": "Sol Bek",
        "power": 66,
        "speed": 7,
        "age": 28,
        birthplace: "Paris, Fransa", "teamId": "reims",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 341757,
        "name": "Teddy Teuma",
        "position": "Ön Libero",
        "power": 62,
        "speed": 5,
        "age": 28,
        birthplace: "Nantes, Fransa", "teamId": "reims",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 375998,
        "name": "Amir Richardson",
        "position": "Merkez Orta Saha",
        "power": 66,
        "speed": 9,
        "age": 22,
        birthplace: "Marseille, Fransa", "teamId": "reims",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 380756,
        "name": "Junya Ito",
        "position": "Orta Saha",
        "power": 67,
        "speed": 9,
        "age": 24,
        birthplace: "Montpellier, Fransa", "teamId": "reims",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 727855,
        "name": "Oumar Diakite",
        "position": "Forvet Arkası",
        "power": 63,
        "speed": 7,
        "age": 22,
        birthplace: "Lyon, Fransa", "teamId": "reims",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 134574,
        "name": "Keito Nakamura",
        "position": "Maestro",
        "power": 64,
        "speed": 8,
        "age": 24,
        birthplace: "Paris, Fransa", "teamId": "reims",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 568988,
        "name": "Reda Khadra",
        "position": "Sağ Kanat",
        "power": 62,
        "speed": 7,
        "age": 32,
        birthplace: "Nice, Fransa", "teamId": "reims",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 564326,
        "name": "Valentin Atangana",
        "position": "Sol Kanat",
        "power": 61,
        "speed": 5,
        "age": 27,
        birthplace: "Montpellier, Fransa", "teamId": "reims",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 526269,
        "name": "Sergio Akieme",
        "position": "Forvet",
        "power": 61,
        "speed": 5,
        "age": 32,
        birthplace: "Paris, Fransa", "teamId": "reims",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 830754,
        "name": "Joseph Okumu",
        "position": "Forvet",
        "power": 62,
        "speed": 5,
        "age": 32,
        birthplace: "Lille, Fransa", "teamId": "reims",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 199177,
        "name": "Guillaume Restes",
        "position": "Kaleci",
        "power": 65,
        "speed": 7,
        "age": 21,
        birthplace: "Lyon, Fransa", "teamId": "toulouse",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 274016,
        "name": "Rasmus Nicolaisen",
        "position": "Stoper",
        "power": 64,
        "speed": 6,
        "age": 21,
        birthplace: "Montpellier, Fransa", "teamId": "toulouse",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 270603,
        "name": "Logan Costa",
        "position": "Stoper",
        "power": 65,
        "speed": 8,
        "age": 29,
        birthplace: "Nice, Fransa", "teamId": "toulouse",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 539697,
        "name": "Christian Mawissa",
        "position": "Stoper",
        "power": 64,
        "speed": 6,
        "age": 32,
        birthplace: "Strasbourg, Fransa", "teamId": "toulouse",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 473331,
        "name": "Mikkel Desler",
        "position": "Sağ Bek",
        "power": 66,
        "speed": 5,
        "age": 22,
        birthplace: "Montpellier, Fransa", "teamId": "toulouse",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 208218,
        "name": "Vincent Sierro",
        "position": "Sol Bek",
        "power": 63,
        "speed": 9,
        "age": 27,
        birthplace: "Strasbourg, Fransa", "teamId": "toulouse",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 769154,
        "name": "Cristian Casseres",
        "position": "Ön Libero",
        "power": 61,
        "speed": 5,
        "age": 30,
        birthplace: "Toulouse, Fransa", "teamId": "toulouse",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 652012,
        "name": "Stijn Spierings",
        "position": "Merkez Orta Saha",
        "power": 66,
        "speed": 5,
        "age": 25,
        birthplace: "Toulouse, Fransa", "teamId": "toulouse",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 968003,
        "name": "Yann Gboho",
        "position": "Orta Saha",
        "power": 66,
        "speed": 5,
        "age": 23,
        birthplace: "Nice, Fransa", "teamId": "toulouse",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 721715,
        "name": "Thijs Dallinga",
        "position": "Forvet Arkası",
        "power": 66,
        "speed": 7,
        "age": 19,
        birthplace: "Nice, Fransa", "teamId": "toulouse",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 853876,
        "name": "Aron Donnum",
        "position": "Maestro",
        "power": 66,
        "speed": 5,
        "age": 25,
        birthplace: "Nice, Fransa", "teamId": "toulouse",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 540644,
        "name": "Zakaria Aboukhlal",
        "position": "Sağ Kanat",
        "power": 65,
        "speed": 5,
        "age": 25,
        birthplace: "Toulouse, Fransa", "teamId": "toulouse",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 146757,
        "name": "Gabriel Suazo",
        "position": "Sol Kanat",
        "power": 68,
        "speed": 7,
        "age": 20,
        birthplace: "Nice, Fransa", "teamId": "toulouse",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 260178,
        "name": "Moussa Diarra",
        "position": "Forvet",
        "power": 67,
        "speed": 6,
        "age": 30,
        birthplace: "Toulouse, Fransa", "teamId": "toulouse",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 986312,
        "name": "Shavy Babicka",
        "position": "Forvet",
        "power": 63,
        "speed": 9,
        "age": 24,
        birthplace: "Bordeaux, Fransa", "teamId": "toulouse",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 920710,
        "name": "Benjamin Lecomte",
        "position": "Kaleci",
        "power": 65,
        "speed": 5,
        "age": 27,
        birthplace: "Nice, Fransa", "teamId": "montpellier",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 568206,
        "name": "Becir Omeragic",
        "position": "Stoper",
        "power": 62,
        "speed": 7,
        "age": 29,
        birthplace: "Nice, Fransa", "teamId": "montpellier",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 320894,
        "name": "Kiki Kouyate",
        "position": "Stoper",
        "power": 61,
        "speed": 7,
        "age": 22,
        birthplace: "Bordeaux, Fransa", "teamId": "montpellier",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 866131,
        "name": "Modibo Sagnan",
        "position": "Stoper",
        "power": 63,
        "speed": 9,
        "age": 25,
        birthplace: "Nantes, Fransa", "teamId": "montpellier",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 756206,
        "name": "Issiaga Sylla",
        "position": "Sağ Bek",
        "power": 66,
        "speed": 8,
        "age": 23,
        birthplace: "Montpellier, Fransa", "teamId": "montpellier",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 922733,
        "name": "Joris Chotard",
        "position": "Sol Bek",
        "power": 62,
        "speed": 9,
        "age": 20,
        birthplace: "Nice, Fransa", "teamId": "montpellier",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 341246,
        "name": "Jordan Ferri",
        "position": "Ön Libero",
        "power": 61,
        "speed": 5,
        "age": 23,
        birthplace: "Nice, Fransa", "teamId": "montpellier",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 753961,
        "name": "Teji Savanier",
        "position": "Merkez Orta Saha",
        "power": 68,
        "speed": 5,
        "age": 24,
        birthplace: "Marseille, Fransa", "teamId": "montpellier",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 470163,
        "name": "Arnaud Nordin",
        "position": "Orta Saha",
        "power": 64,
        "speed": 6,
        "age": 29,
        birthplace: "Toulouse, Fransa", "teamId": "montpellier",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 768641,
        "name": "Akor Adams",
        "position": "Forvet Arkası",
        "power": 64,
        "speed": 5,
        "age": 23,
        birthplace: "Bordeaux, Fransa", "teamId": "montpellier",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 739674,
        "name": "Musa Al-Taamari",
        "position": "Maestro",
        "power": 67,
        "speed": 8,
        "age": 27,
        birthplace: "Nantes, Fransa", "teamId": "montpellier",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 447531,
        "name": "Wahbi Khazri",
        "position": "Sağ Kanat",
        "power": 61,
        "speed": 5,
        "age": 28,
        birthplace: "Nantes, Fransa", "teamId": "montpellier",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 530097,
        "name": "Lucas Mincarelli",
        "position": "Sol Kanat",
        "power": 67,
        "speed": 7,
        "age": 21,
        birthplace: "Nantes, Fransa", "teamId": "montpellier",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 234511,
        "name": "Silvan Hefti",
        "position": "Forvet",
        "power": 62,
        "speed": 5,
        "age": 21,
        birthplace: "Montpellier, Fransa", "teamId": "montpellier",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 943731,
        "name": "Karamoh",
        "position": "Forvet",
        "power": 67,
        "speed": 7,
        "age": 27,
        birthplace: "Nantes, Fransa", "teamId": "montpellier",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 238320,
        "name": "Alaa Bellaarouch",
        "position": "Kaleci",
        "power": 65,
        "speed": 5,
        "age": 29,
        birthplace: "Marseille, Fransa", "teamId": "strasbourg",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 598097,
        "name": "Lucas Perrin",
        "position": "Stoper",
        "power": 64,
        "speed": 8,
        "age": 27,
        birthplace: "Nice, Fransa", "teamId": "strasbourg",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 625364,
        "name": "Abakar Sylla",
        "position": "Stoper",
        "power": 68,
        "speed": 9,
        "age": 27,
        birthplace: "Paris, Fransa", "teamId": "strasbourg",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 756792,
        "name": "Frederic Guilbert",
        "position": "Stoper",
        "power": 64,
        "speed": 9,
        "age": 19,
        birthplace: "Lille, Fransa", "teamId": "strasbourg",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 613862,
        "name": "Thomas Delaine",
        "position": "Sağ Bek",
        "power": 65,
        "speed": 6,
        "age": 21,
        birthplace: "Paris, Fransa", "teamId": "strasbourg",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 220936,
        "name": "Ismael Doukoure",
        "position": "Sol Bek",
        "power": 68,
        "speed": 7,
        "age": 28,
        birthplace: "Bordeaux, Fransa", "teamId": "strasbourg",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 697244,
        "name": "Andrey Santos",
        "position": "Ön Libero",
        "power": 61,
        "speed": 5,
        "age": 32,
        birthplace: "Paris, Fransa", "teamId": "strasbourg",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 672074,
        "name": "Habib Diarra",
        "position": "Merkez Orta Saha",
        "power": 62,
        "speed": 8,
        "age": 22,
        birthplace: "Nantes, Fransa", "teamId": "strasbourg",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 531468,
        "name": "Dilane Bakwa",
        "position": "Orta Saha",
        "power": 68,
        "speed": 7,
        "age": 22,
        birthplace: "Marseille, Fransa", "teamId": "strasbourg",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 796594,
        "name": "Emanuel Emegha",
        "position": "Forvet Arkası",
        "power": 66,
        "speed": 6,
        "age": 22,
        birthplace: "Lille, Fransa", "teamId": "strasbourg",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 560137,
        "name": "Kevin Gameiro",
        "position": "Maestro",
        "power": 63,
        "speed": 7,
        "age": 29,
        birthplace: "Strasbourg, Fransa", "teamId": "strasbourg",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 672698,
        "name": "Marvin Senaya",
        "position": "Sağ Kanat",
        "power": 66,
        "speed": 8,
        "age": 21,
        birthplace: "Marseille, Fransa", "teamId": "strasbourg",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 879590,
        "name": "Jessy Deminguet",
        "position": "Sol Kanat",
        "power": 61,
        "speed": 9,
        "age": 22,
        birthplace: "Marseille, Fransa", "teamId": "strasbourg",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 423524,
        "name": "Junior Mwanga",
        "position": "Forvet",
        "power": 64,
        "speed": 8,
        "age": 27,
        birthplace: "Lyon, Fransa", "teamId": "strasbourg",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 969030,
        "name": "Moise Sahi Dion",
        "position": "Forvet",
        "power": 66,
        "speed": 7,
        "age": 21,
        birthplace: "Nantes, Fransa", "teamId": "strasbourg",
        "tacticalRole": "target_man",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 714910,
        "name": "Alban Lafont",
        "position": "Kaleci",
        "power": 62,
        "speed": 9,
        "age": 26,
        birthplace: "Paris, Fransa", "teamId": "nantes",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 969988,
        "name": "Jean-Charles Castelletto",
        "position": "Stoper",
        "power": 65,
        "speed": 9,
        "age": 19,
        birthplace: "Nantes, Fransa", "teamId": "nantes",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 868392,
        "name": "Nicolas Pallois",
        "position": "Stoper",
        "power": 64,
        "speed": 5,
        "age": 19,
        birthplace: "Montpellier, Fransa", "teamId": "nantes",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 678590,
        "name": "Eray Comert",
        "position": "Stoper",
        "power": 61,
        "speed": 5,
        "age": 32,
        birthplace: "Lyon, Fransa", "teamId": "nantes",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 102366,
        "name": "Kelvin Amian",
        "position": "Sağ Bek",
        "power": 66,
        "speed": 5,
        "age": 31,
        birthplace: "Marseille, Fransa", "teamId": "nantes",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 545782,
        "name": "Pedro Chirivella",
        "position": "Sol Bek",
        "power": 67,
        "speed": 7,
        "age": 22,
        birthplace: "Nice, Fransa", "teamId": "nantes",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 900697,
        "name": "Douglas Augusto",
        "position": "Ön Libero",
        "power": 64,
        "speed": 6,
        "age": 30,
        birthplace: "Montpellier, Fransa", "teamId": "nantes",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 398421,
        "name": "Moussa Sissoko",
        "position": "Merkez Orta Saha",
        "power": 65,
        "speed": 8,
        "age": 22,
        birthplace: "Strasbourg, Fransa", "teamId": "nantes",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 447222,
        "name": "Florent Mollet",
        "position": "Orta Saha",
        "power": 65,
        "speed": 7,
        "age": 22,
        birthplace: "Bordeaux, Fransa", "teamId": "nantes",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 475882,
        "name": "Mostafa Mohamed",
        "position": "Forvet Arkası",
        "power": 62,
        "speed": 5,
        "age": 25,
        birthplace: "Strasbourg, Fransa", "teamId": "nantes",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 712051,
        "name": "Moses Simon",
        "position": "Maestro",
        "power": 64,
        "speed": 7,
        "age": 21,
        birthplace: "Strasbourg, Fransa", "teamId": "nantes",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 498072,
        "name": "Matthis Abline",
        "position": "Sağ Kanat",
        "power": 66,
        "speed": 7,
        "age": 22,
        birthplace: "Marseille, Fransa", "teamId": "nantes",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 784549,
        "name": "Tino Kadewere",
        "position": "Sol Kanat",
        "power": 63,
        "speed": 6,
        "age": 24,
        birthplace: "Nantes, Fransa", "teamId": "nantes",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 185899,
        "name": "Marcus Coco",
        "position": "Forvet",
        "power": 61,
        "speed": 9,
        "age": 19,
        birthplace: "Marseille, Fransa", "teamId": "nantes",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 733164,
        "name": "Samuel Moutoussamy",
        "position": "Forvet",
        "power": 62,
        "speed": 6,
        "age": 23,
        birthplace: "Marseille, Fransa", "teamId": "nantes",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 367152,
        "name": "Arthur Desmas",
        "position": "Kaleci",
        "power": 63,
        "speed": 6,
        "age": 26,
        birthplace: "Bordeaux, Fransa", "teamId": "lehavre",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 247282,
        "name": "Gautier Lloris",
        "position": "Stoper",
        "power": 62,
        "speed": 8,
        "age": 19,
        birthplace: "Nantes, Fransa", "teamId": "lehavre",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 326496,
        "name": "Arouna Sangante",
        "position": "Stoper",
        "power": 64,
        "speed": 5,
        "age": 26,
        birthplace: "Montpellier, Fransa", "teamId": "lehavre",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 732544,
        "name": "Youté Kinkoue",
        "position": "Stoper",
        "power": 63,
        "speed": 7,
        "age": 20,
        birthplace: "Montpellier, Fransa", "teamId": "lehavre",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 496464,
        "name": "Christopher Operi",
        "position": "Sağ Bek",
        "power": 63,
        "speed": 7,
        "age": 24,
        birthplace: "Marseille, Fransa", "teamId": "lehavre",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 598446,
        "name": "Oussama Targhalline",
        "position": "Sol Bek",
        "power": 67,
        "speed": 7,
        "age": 31,
        birthplace: "Marseille, Fransa", "teamId": "lehavre",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 978379,
        "name": "Daler Kuzyaev",
        "position": "Ön Libero",
        "power": 64,
        "speed": 5,
        "age": 20,
        birthplace: "Bordeaux, Fransa", "teamId": "lehavre",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 246725,
        "name": "Abdoulaye Toure",
        "position": "Merkez Orta Saha",
        "power": 66,
        "speed": 9,
        "age": 26,
        birthplace: "Nice, Fransa", "teamId": "lehavre",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 998614,
        "name": "Josue Casimir",
        "position": "Orta Saha",
        "power": 66,
        "speed": 8,
        "age": 23,
        birthplace: "Bordeaux, Fransa", "teamId": "lehavre",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 402012,
        "name": "Mohamed Bayo",
        "position": "Forvet Arkası",
        "power": 67,
        "speed": 6,
        "age": 24,
        birthplace: "Nantes, Fransa", "teamId": "lehavre",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 678267,
        "name": "Emmanuel Sabbi",
        "position": "Maestro",
        "power": 67,
        "speed": 6,
        "age": 21,
        birthplace: "Lille, Fransa", "teamId": "lehavre",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 683809,
        "name": "Yassine Kechta",
        "position": "Sağ Kanat",
        "power": 62,
        "speed": 5,
        "age": 23,
        birthplace: "Nantes, Fransa", "teamId": "lehavre",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 122857,
        "name": "Andre Ayew",
        "position": "Sol Kanat",
        "power": 66,
        "speed": 7,
        "age": 23,
        birthplace: "Marseille, Fransa", "teamId": "lehavre",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 631541,
        "name": "Loic Nego",
        "position": "Forvet",
        "power": 67,
        "speed": 5,
        "age": 19,
        birthplace: "Montpellier, Fransa", "teamId": "lehavre",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 560788,
        "name": "Alois Confais",
        "position": "Forvet",
        "power": 61,
        "speed": 6,
        "age": 32,
        birthplace: "Marseille, Fransa", "teamId": "lehavre",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 263674,
        "name": "Marco Bizot",
        "position": "Kaleci",
        "power": 68,
        "speed": 9,
        "age": 21,
        birthplace: "Lyon, Fransa", "teamId": "brest",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 759813,
        "name": "Brendan Chardonnet",
        "position": "Stoper",
        "power": 67,
        "speed": 6,
        "age": 31,
        birthplace: "Paris, Fransa", "teamId": "brest",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 229865,
        "name": "Lilian Brassier",
        "position": "Stoper",
        "power": 68,
        "speed": 5,
        "age": 30,
        birthplace: "Nantes, Fransa", "teamId": "brest",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 614248,
        "name": "Kenny Lala",
        "position": "Stoper",
        "power": 63,
        "speed": 5,
        "age": 26,
        birthplace: "Toulouse, Fransa", "teamId": "brest",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 356612,
        "name": "Bradley Locko",
        "position": "Sağ Bek",
        "power": 63,
        "speed": 9,
        "age": 26,
        birthplace: "Marseille, Fransa", "teamId": "brest",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 223075,
        "name": "Pierre Lees-Melou",
        "position": "Sol Bek",
        "power": 62,
        "speed": 6,
        "age": 20,
        birthplace: "Marseille, Fransa", "teamId": "brest",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 328515,
        "name": "Hugo Magnetti",
        "position": "Ön Libero",
        "power": 68,
        "speed": 9,
        "age": 30,
        birthplace: "Montpellier, Fransa", "teamId": "brest",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 958719,
        "name": "Mahdi Camara",
        "position": "Merkez Orta Saha",
        "power": 62,
        "speed": 5,
        "age": 22,
        birthplace: "Nantes, Fransa", "teamId": "brest",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 433439,
        "name": "Romain Del Castillo",
        "position": "Orta Saha",
        "power": 66,
        "speed": 6,
        "age": 25,
        birthplace: "Lille, Fransa", "teamId": "brest",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 527449,
        "name": "Steve Mounie",
        "position": "Forvet Arkası",
        "power": 63,
        "speed": 7,
        "age": 32,
        birthplace: "Nantes, Fransa", "teamId": "brest",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 696903,
        "name": "Martin Satriano",
        "position": "Maestro",
        "power": 68,
        "speed": 6,
        "age": 30,
        birthplace: "Lyon, Fransa", "teamId": "brest",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 230728,
        "name": "Kamory Doumbia",
        "position": "Sağ Kanat",
        "power": 66,
        "speed": 6,
        "age": 19,
        birthplace: "Strasbourg, Fransa", "teamId": "brest",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 196992,
        "name": "Jeremy Le Douaron",
        "position": "Sol Kanat",
        "power": 62,
        "speed": 9,
        "age": 22,
        birthplace: "Nice, Fransa", "teamId": "brest",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 833552,
        "name": "Mathias Pereira Lage",
        "position": "Forvet",
        "power": 67,
        "speed": 7,
        "age": 24,
        birthplace: "Montpellier, Fransa", "teamId": "brest",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 953562,
        "name": "Jonas Martin",
        "position": "Forvet",
        "power": 62,
        "speed": 5,
        "age": 20,
        birthplace: "Bordeaux, Fransa", "teamId": "brest",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    }
];
ligue1Players.forEach(p => window.leagueData.players.push(p));
