// js/data_eredivisie.js
// GERCEK EREDIVISIE VERILERI
window.leagueData = window.leagueData || { teams: [], players: [] };
const eredivisieTeams = [
    {
        "id": "psv",
        "name": "PSV Eindhoven",
        "budget": 70,
        "leagueId": "hollanda"
    },
    {
        "id": "feyenoord",
        "name": "Feyenoord",
        "budget": 65,
        "leagueId": "hollanda"
    },
    {
        "id": "ajax",
        "name": "Ajax Amsterdam",
        "budget": 65,
        "leagueId": "hollanda"
    },
    {
        "id": "az_alkmaar",
        "name": "AZ Alkmaar",
        "budget": 50,
        "leagueId": "hollanda"
    },
    {
        "id": "twente",
        "name": "FC Twente",
        "budget": 45,
        "leagueId": "hollanda"
    },
    {
        "id": "sparta_rotterdam",
        "name": "Sparta Rotterdam",
        "budget": 35,
        "leagueId": "hollanda"
    },
    {
        "id": "utrecht",
        "name": "FC Utrecht",
        "budget": 40,
        "leagueId": "hollanda"
    },
    {
        "id": "nec_nijmegen",
        "name": "NEC Nijmegen",
        "budget": 35,
        "leagueId": "hollanda"
    },
    {
        "id": "heerenveen",
        "name": "sc Heerenveen",
        "budget": 30,
        "leagueId": "hollanda"
    },
    {
        "id": "go_ahead_eagles",
        "name": "Go Ahead Eagles",
        "budget": 25,
        "leagueId": "hollanda"
    },
    {
        "id": "fortuna_sittard",
        "name": "Fortuna Sittard",
        "budget": 25,
        "leagueId": "hollanda"
    },
    {
        "id": "volendam",
        "name": "FC Volendam",
        "budget": 15,
        "leagueId": "hollanda"
    }
];
eredivisieTeams.forEach(t => window.leagueData.teams.push(t));
const eredivisiePlayers = [
    {
        "id": 279803,
        "name": "Walter Benitez",
        "position": "Kaleci",
        "power": 76,
        "speed": 6,
        "age": 20,
        birthplace: "The Hague, Hollanda", "teamId": "psv",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 397255,
        "name": "Olivier Boscagli",
        "position": "Stoper",
        "power": 77,
        "speed": 6,
        "age": 24,
        birthplace: "The Hague, Hollanda", "teamId": "psv",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 852499,
        "name": "Andre Ramalho",
        "position": "Stoper",
        "power": 77,
        "speed": 7,
        "age": 21,
        birthplace: "Amsterdam, Hollanda", "teamId": "psv",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 820687,
        "name": "Jordan Teze",
        "position": "Stoper",
        "power": 76,
        "speed": 7,
        "age": 32,
        birthplace: "Amsterdam, Hollanda", "teamId": "psv",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 322572,
        "name": "Sergino Dest",
        "position": "Sağ Bek",
        "power": 75,
        "speed": 6,
        "age": 25,
        birthplace: "Tilburg, Hollanda", "teamId": "psv",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 496301,
        "name": "Jerdy Schouten",
        "position": "Sol Bek",
        "power": 79,
        "speed": 5,
        "age": 32,
        birthplace: "Tilburg, Hollanda", "teamId": "psv",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 632106,
        "name": "Joey Veerman",
        "position": "Ön Libero",
        "power": 76,
        "speed": 9,
        "age": 28,
        birthplace: "Amsterdam, Hollanda", "teamId": "psv",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 357879,
        "name": "Ismael Saibari",
        "position": "Merkez Orta Saha",
        "power": 77,
        "speed": 9,
        "age": 32,
        birthplace: "Tilburg, Hollanda", "teamId": "psv",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 436251,
        "name": "Johan Bakayoko",
        "position": "Orta Saha",
        "power": 79,
        "speed": 5,
        "age": 26,
        birthplace: "Utrecht, Hollanda", "teamId": "psv",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 201596,
        "name": "Luuk de Jong",
        "position": "Forvet Arkası",
        "power": 73,
        "speed": 7,
        "age": 20,
        birthplace: "Amsterdam, Hollanda", "teamId": "psv",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 502948,
        "name": "Hirving Lozano",
        "position": "Maestro",
        "power": 77,
        "speed": 5,
        "age": 29,
        birthplace: "Utrecht, Hollanda", "teamId": "psv",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 415483,
        "name": "Malik Tillman",
        "position": "Sağ Kanat",
        "power": 73,
        "speed": 8,
        "age": 30,
        birthplace: "Eindhoven, Hollanda", "teamId": "psv",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 246740,
        "name": "Guus Til",
        "position": "Sol Kanat",
        "power": 78,
        "speed": 9,
        "age": 22,
        birthplace: "Eindhoven, Hollanda", "teamId": "psv",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 835822,
        "name": "Armando Obispo",
        "position": "Forvet",
        "power": 76,
        "speed": 5,
        "age": 26,
        birthplace: "Groningen, Hollanda", "teamId": "psv",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 514389,
        "name": "Patrick van Aanholt",
        "position": "Forvet",
        "power": 77,
        "speed": 9,
        "age": 24,
        birthplace: "Groningen, Hollanda", "teamId": "psv",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 849489,
        "name": "Justin Bijlow",
        "position": "Kaleci",
        "power": 79,
        "speed": 7,
        "age": 32,
        birthplace: "Amsterdam, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 291963,
        "name": "David Hancko",
        "position": "Stoper",
        "power": 77,
        "speed": 6,
        "age": 30,
        birthplace: "Utrecht, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 271669,
        "name": "Lutsharel Geertruida",
        "position": "Stoper",
        "power": 78,
        "speed": 6,
        "age": 27,
        birthplace: "Utrecht, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 852772,
        "name": "Gernot Trauner",
        "position": "Stoper",
        "power": 80,
        "speed": 9,
        "age": 21,
        birthplace: "The Hague, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 468907,
        "name": "Quilindschy Hartman",
        "position": "Sağ Bek",
        "power": 80,
        "speed": 5,
        "age": 20,
        birthplace: "The Hague, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 915215,
        "name": "Mats Wieffer",
        "position": "Sol Bek",
        "power": 80,
        "speed": 5,
        "age": 29,
        birthplace: "Tilburg, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 588616,
        "name": "Quinten Timber",
        "position": "Ön Libero",
        "power": 77,
        "speed": 7,
        "age": 24,
        birthplace: "Amsterdam, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 891451,
        "name": "Calvin Stengs",
        "position": "Merkez Orta Saha",
        "power": 76,
        "speed": 8,
        "age": 21,
        birthplace: "Amsterdam, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 846661,
        "name": "Igor Paixao",
        "position": "Orta Saha",
        "power": 75,
        "speed": 9,
        "age": 21,
        birthplace: "The Hague, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 983788,
        "name": "Santiago Gimenez",
        "position": "Forvet Arkası",
        "power": 79,
        "speed": 7,
        "age": 28,
        birthplace: "Rotterdam, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 498643,
        "name": "Yankuba Minteh",
        "position": "Maestro",
        "power": 79,
        "speed": 6,
        "age": 19,
        birthplace: "Amsterdam, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 449953,
        "name": "Luka Ivanusec",
        "position": "Sağ Kanat",
        "power": 76,
        "speed": 9,
        "age": 25,
        birthplace: "Eindhoven, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 540760,
        "name": "Ramiz Zerrouki",
        "position": "Sol Kanat",
        "power": 77,
        "speed": 6,
        "age": 22,
        birthplace: "The Hague, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 162997,
        "name": "Thomas Beelen",
        "position": "Forvet",
        "power": 79,
        "speed": 9,
        "age": 19,
        birthplace: "The Hague, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 722199,
        "name": "Bart Nieuwkoop",
        "position": "Forvet",
        "power": 79,
        "speed": 9,
        "age": 22,
        birthplace: "Rotterdam, Hollanda", "teamId": "feyenoord",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 291388,
        "name": "Diant Ramaj",
        "position": "Kaleci",
        "power": 75,
        "speed": 9,
        "age": 21,
        birthplace: "The Hague, Hollanda", "teamId": "ajax",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 649296,
        "name": "Jorrel Hato",
        "position": "Stoper",
        "power": 76,
        "speed": 5,
        "age": 21,
        birthplace: "The Hague, Hollanda", "teamId": "ajax",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 727809,
        "name": "Josip Sutalo",
        "position": "Stoper",
        "power": 78,
        "speed": 7,
        "age": 20,
        birthplace: "Utrecht, Hollanda", "teamId": "ajax",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 540186,
        "name": "Devyne Rensch",
        "position": "Stoper",
        "power": 75,
        "speed": 6,
        "age": 21,
        birthplace: "Utrecht, Hollanda", "teamId": "ajax",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 748788,
        "name": "Borna Sosa",
        "position": "Sağ Bek",
        "power": 74,
        "speed": 9,
        "age": 24,
        birthplace: "Eindhoven, Hollanda", "teamId": "ajax",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 664057,
        "name": "Jordan Henderson",
        "position": "Sol Bek",
        "power": 75,
        "speed": 5,
        "age": 26,
        birthplace: "Tilburg, Hollanda", "teamId": "ajax",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 217095,
        "name": "Kenneth Taylor",
        "position": "Ön Libero",
        "power": 77,
        "speed": 5,
        "age": 21,
        birthplace: "The Hague, Hollanda", "teamId": "ajax",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 805264,
        "name": "Steven Berghuis",
        "position": "Merkez Orta Saha",
        "power": 80,
        "speed": 7,
        "age": 25,
        birthplace: "Eindhoven, Hollanda", "teamId": "ajax",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 491044,
        "name": "Steven Bergwijn",
        "position": "Orta Saha",
        "power": 73,
        "speed": 5,
        "age": 27,
        birthplace: "Groningen, Hollanda", "teamId": "ajax",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 645416,
        "name": "Brian Brobbey",
        "position": "Forvet Arkası",
        "power": 77,
        "speed": 8,
        "age": 25,
        birthplace: "Groningen, Hollanda", "teamId": "ajax",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 872160,
        "name": "Chuba Akpom",
        "position": "Maestro",
        "power": 73,
        "speed": 9,
        "age": 20,
        birthplace: "Utrecht, Hollanda", "teamId": "ajax",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 712915,
        "name": "Mika Godts",
        "position": "Sağ Kanat",
        "power": 79,
        "speed": 6,
        "age": 24,
        birthplace: "Utrecht, Hollanda", "teamId": "ajax",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 568570,
        "name": "Branco van den Boomen",
        "position": "Sol Kanat",
        "power": 79,
        "speed": 6,
        "age": 30,
        birthplace: "Eindhoven, Hollanda", "teamId": "ajax",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 760039,
        "name": "Sivert Mannsverk",
        "position": "Forvet",
        "power": 74,
        "speed": 9,
        "age": 26,
        birthplace: "The Hague, Hollanda", "teamId": "ajax",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 105340,
        "name": "Anton Gaaei",
        "position": "Forvet",
        "power": 80,
        "speed": 9,
        "age": 29,
        birthplace: "Rotterdam, Hollanda", "teamId": "ajax",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 568994,
        "name": "Mathew Ryan",
        "position": "Kaleci",
        "power": 69,
        "speed": 8,
        "age": 31,
        birthplace: "Groningen, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 323279,
        "name": "Vangelis Pavlidis",
        "position": "Stoper",
        "power": 70,
        "speed": 8,
        "age": 23,
        birthplace: "The Hague, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 874515,
        "name": "Riechedly Bazoer",
        "position": "Stoper",
        "power": 73,
        "speed": 7,
        "age": 21,
        birthplace: "Groningen, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 282785,
        "name": "Yukinari Sugawara",
        "position": "Stoper",
        "power": 70,
        "speed": 6,
        "age": 19,
        birthplace: "Groningen, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 209732,
        "name": "David Moller Wolfe",
        "position": "Sağ Bek",
        "power": 71,
        "speed": 7,
        "age": 31,
        birthplace: "Eindhoven, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 416962,
        "name": "Jordy Clasie",
        "position": "Sol Bek",
        "power": 72,
        "speed": 8,
        "age": 19,
        birthplace: "Eindhoven, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 394900,
        "name": "Sven Mijnans",
        "position": "Ön Libero",
        "power": 72,
        "speed": 7,
        "age": 24,
        birthplace: "Groningen, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 299981,
        "name": "Dani de Wit",
        "position": "Merkez Orta Saha",
        "power": 72,
        "speed": 8,
        "age": 23,
        birthplace: "Eindhoven, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 633050,
        "name": "Ruben van Bommel",
        "position": "Orta Saha",
        "power": 68,
        "speed": 8,
        "age": 21,
        birthplace: "Rotterdam, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 995421,
        "name": "Mayckel Lahdo",
        "position": "Forvet Arkası",
        "power": 70,
        "speed": 6,
        "age": 19,
        birthplace: "Groningen, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 946654,
        "name": "Tiago Dantas",
        "position": "Maestro",
        "power": 68,
        "speed": 8,
        "age": 23,
        birthplace: "Amsterdam, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 596404,
        "name": "Myron van Brederode",
        "position": "Sağ Kanat",
        "power": 72,
        "speed": 7,
        "age": 24,
        birthplace: "Utrecht, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 589422,
        "name": "Alexandre Penetra",
        "position": "Sol Kanat",
        "power": 70,
        "speed": 5,
        "age": 19,
        birthplace: "Eindhoven, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 632637,
        "name": "Riechedly Bazoer II",
        "position": "Forvet",
        "power": 72,
        "speed": 7,
        "age": 32,
        birthplace: "Tilburg, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 507357,
        "name": "Jens Odgaard",
        "position": "Forvet",
        "power": 67,
        "speed": 5,
        "age": 28,
        birthplace: "The Hague, Hollanda", "teamId": "az_alkmaar",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 762029,
        "name": "Lars Unnerstall",
        "position": "Kaleci",
        "power": 69,
        "speed": 7,
        "age": 26,
        birthplace: "Eindhoven, Hollanda", "teamId": "twente",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 838990,
        "name": "Robin Propper",
        "position": "Stoper",
        "power": 70,
        "speed": 5,
        "age": 21,
        birthplace: "Groningen, Hollanda", "teamId": "twente",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 844693,
        "name": "Mees Hilgers",
        "position": "Stoper",
        "power": 73,
        "speed": 9,
        "age": 31,
        birthplace: "Utrecht, Hollanda", "teamId": "twente",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 457539,
        "name": "Joshua Brenet",
        "position": "Stoper",
        "power": 70,
        "speed": 6,
        "age": 19,
        birthplace: "The Hague, Hollanda", "teamId": "twente",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 834778,
        "name": "Gijs Smal",
        "position": "Sağ Bek",
        "power": 66,
        "speed": 6,
        "age": 29,
        birthplace: "Groningen, Hollanda", "teamId": "twente",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 862411,
        "name": "Michal Sadilek",
        "position": "Sol Bek",
        "power": 73,
        "speed": 9,
        "age": 23,
        birthplace: "Rotterdam, Hollanda", "teamId": "twente",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 931125,
        "name": "Mathias Kjolo",
        "position": "Ön Libero",
        "power": 70,
        "speed": 5,
        "age": 24,
        birthplace: "Rotterdam, Hollanda", "teamId": "twente",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 446382,
        "name": "Sem Steijn",
        "position": "Merkez Orta Saha",
        "power": 68,
        "speed": 7,
        "age": 20,
        birthplace: "Amsterdam, Hollanda", "teamId": "twente",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 533390,
        "name": "Daan Rots",
        "position": "Orta Saha",
        "power": 68,
        "speed": 7,
        "age": 22,
        birthplace: "Rotterdam, Hollanda", "teamId": "twente",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 663924,
        "name": "Ricky van Wolfswinkel",
        "position": "Forvet Arkası",
        "power": 66,
        "speed": 7,
        "age": 23,
        birthplace: "Eindhoven, Hollanda", "teamId": "twente",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 965025,
        "name": "Michel Vlap",
        "position": "Maestro",
        "power": 69,
        "speed": 5,
        "age": 20,
        birthplace: "Groningen, Hollanda", "teamId": "twente",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 758402,
        "name": "Manfred Ugalde",
        "position": "Sağ Kanat",
        "power": 70,
        "speed": 7,
        "age": 19,
        birthplace: "Rotterdam, Hollanda", "teamId": "twente",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 739131,
        "name": "Carel Eiting",
        "position": "Sol Kanat",
        "power": 73,
        "speed": 9,
        "age": 29,
        birthplace: "Amsterdam, Hollanda", "teamId": "twente",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 643457,
        "name": "Youri Regeer",
        "position": "Forvet",
        "power": 69,
        "speed": 9,
        "age": 30,
        birthplace: "Tilburg, Hollanda", "teamId": "twente",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 465071,
        "name": "Naci Unuvar",
        "position": "Forvet",
        "power": 71,
        "speed": 7,
        "age": 29,
        birthplace: "Utrecht, Hollanda", "teamId": "twente",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 699296,
        "name": "Nick Olij",
        "position": "Kaleci",
        "power": 65,
        "speed": 8,
        "age": 23,
        birthplace: "Tilburg, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 140202,
        "name": "Bart Vriends",
        "position": "Stoper",
        "power": 63,
        "speed": 8,
        "age": 23,
        birthplace: "Rotterdam, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 637029,
        "name": "Tijs Velthuis",
        "position": "Stoper",
        "power": 65,
        "speed": 9,
        "age": 21,
        birthplace: "Amsterdam, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 858961,
        "name": "Djevencio van der Kust",
        "position": "Stoper",
        "power": 62,
        "speed": 5,
        "age": 23,
        birthplace: "The Hague, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 686934,
        "name": "Said Bakari",
        "position": "Sağ Bek",
        "power": 64,
        "speed": 9,
        "age": 25,
        birthplace: "Rotterdam, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 773158,
        "name": "Jonathan de Guzman",
        "position": "Sol Bek",
        "power": 68,
        "speed": 7,
        "age": 32,
        birthplace: "Groningen, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 824234,
        "name": "Pelle Clement",
        "position": "Ön Libero",
        "power": 65,
        "speed": 7,
        "age": 25,
        birthplace: "Eindhoven, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 538281,
        "name": "Arno Verschueren",
        "position": "Merkez Orta Saha",
        "power": 65,
        "speed": 9,
        "age": 28,
        birthplace: "Groningen, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 375574,
        "name": "Koki Saito",
        "position": "Orta Saha",
        "power": 68,
        "speed": 8,
        "age": 32,
        birthplace: "The Hague, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 961840,
        "name": "Tobias Lauritsen",
        "position": "Forvet Arkası",
        "power": 62,
        "speed": 7,
        "age": 20,
        birthplace: "Tilburg, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 238916,
        "name": "Joshua Kitolano",
        "position": "Maestro",
        "power": 68,
        "speed": 9,
        "age": 25,
        birthplace: "Utrecht, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 569715,
        "name": "Charles-Andreas Brym",
        "position": "Sağ Kanat",
        "power": 62,
        "speed": 8,
        "age": 21,
        birthplace: "Rotterdam, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 820696,
        "name": "Camiel Neghli",
        "position": "Sol Kanat",
        "power": 63,
        "speed": 8,
        "age": 23,
        birthplace: "Groningen, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 769790,
        "name": "Metinho",
        "position": "Forvet",
        "power": 66,
        "speed": 6,
        "age": 28,
        birthplace: "The Hague, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 210163,
        "name": "Rick Meissen",
        "position": "Forvet",
        "power": 68,
        "speed": 6,
        "age": 31,
        birthplace: "The Hague, Hollanda", "teamId": "sparta_rotterdam",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 709101,
        "name": "Vasilis Barkas",
        "position": "Kaleci",
        "power": 72,
        "speed": 5,
        "age": 30,
        birthplace: "Groningen, Hollanda", "teamId": "utrecht",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 765706,
        "name": "Mike van der Hoorn",
        "position": "Stoper",
        "power": 68,
        "speed": 6,
        "age": 20,
        birthplace: "Eindhoven, Hollanda", "teamId": "utrecht",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 854905,
        "name": "Ryan Flamingo",
        "position": "Stoper",
        "power": 68,
        "speed": 6,
        "age": 25,
        birthplace: "Groningen, Hollanda", "teamId": "utrecht",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 160040,
        "name": "Hidde ter Avest",
        "position": "Stoper",
        "power": 71,
        "speed": 9,
        "age": 20,
        birthplace: "Amsterdam, Hollanda", "teamId": "utrecht",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 200396,
        "name": "Souffian El Karouani",
        "position": "Sağ Bek",
        "power": 67,
        "speed": 7,
        "age": 30,
        birthplace: "Amsterdam, Hollanda", "teamId": "utrecht",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 601918,
        "name": "Oscar Fraulo",
        "position": "Sol Bek",
        "power": 72,
        "speed": 8,
        "age": 25,
        birthplace: "The Hague, Hollanda", "teamId": "utrecht",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 332045,
        "name": "Can Bozdogan",
        "position": "Ön Libero",
        "power": 73,
        "speed": 9,
        "age": 30,
        birthplace: "The Hague, Hollanda", "teamId": "utrecht",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 764657,
        "name": "Jens Toornstra",
        "position": "Merkez Orta Saha",
        "power": 67,
        "speed": 7,
        "age": 30,
        birthplace: "Amsterdam, Hollanda", "teamId": "utrecht",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 213845,
        "name": "Taylor Booth",
        "position": "Orta Saha",
        "power": 72,
        "speed": 8,
        "age": 27,
        birthplace: "Eindhoven, Hollanda", "teamId": "utrecht",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 355951,
        "name": "Sam Lammers",
        "position": "Forvet Arkası",
        "power": 71,
        "speed": 6,
        "age": 22,
        birthplace: "Amsterdam, Hollanda", "teamId": "utrecht",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 922641,
        "name": "Victor Jensen",
        "position": "Maestro",
        "power": 67,
        "speed": 5,
        "age": 20,
        birthplace: "The Hague, Hollanda", "teamId": "utrecht",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 960836,
        "name": "Othman Boussaid",
        "position": "Sağ Kanat",
        "power": 66,
        "speed": 8,
        "age": 30,
        birthplace: "The Hague, Hollanda", "teamId": "utrecht",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 543697,
        "name": "Zidane Iqbal",
        "position": "Sol Kanat",
        "power": 73,
        "speed": 9,
        "age": 28,
        birthplace: "The Hague, Hollanda", "teamId": "utrecht",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 897724,
        "name": "Mark van der Maarel",
        "position": "Forvet",
        "power": 69,
        "speed": 9,
        "age": 31,
        birthplace: "Amsterdam, Hollanda", "teamId": "utrecht",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 943849,
        "name": "Ole Romeny",
        "position": "Forvet",
        "power": 66,
        "speed": 6,
        "age": 20,
        birthplace: "Rotterdam, Hollanda", "teamId": "utrecht",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 758983,
        "name": "Jasper Cillessen",
        "position": "Kaleci",
        "power": 64,
        "speed": 5,
        "age": 27,
        birthplace: "Rotterdam, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 410723,
        "name": "Philippe Sandler",
        "position": "Stoper",
        "power": 63,
        "speed": 5,
        "age": 30,
        birthplace: "Amsterdam, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 915550,
        "name": "Bram Nuytinck",
        "position": "Stoper",
        "power": 66,
        "speed": 9,
        "age": 24,
        birthplace: "Rotterdam, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 373136,
        "name": "Bart van Rooij",
        "position": "Stoper",
        "power": 61,
        "speed": 8,
        "age": 23,
        birthplace: "Rotterdam, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 710726,
        "name": "Calvin Verdonk",
        "position": "Sağ Bek",
        "power": 61,
        "speed": 8,
        "age": 30,
        birthplace: "Eindhoven, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 823084,
        "name": "Dirk Proper",
        "position": "Sol Bek",
        "power": 65,
        "speed": 7,
        "age": 28,
        birthplace: "Tilburg, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 474712,
        "name": "Lasse Schone",
        "position": "Ön Libero",
        "power": 64,
        "speed": 7,
        "age": 31,
        birthplace: "Utrecht, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 779762,
        "name": "Tjaronn Chery",
        "position": "Merkez Orta Saha",
        "power": 62,
        "speed": 8,
        "age": 23,
        birthplace: "Rotterdam, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 930333,
        "name": "Kodai Sano",
        "position": "Orta Saha",
        "power": 64,
        "speed": 9,
        "age": 25,
        birthplace: "Amsterdam, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "target_man",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 920166,
        "name": "Koki Ogawa",
        "position": "Forvet Arkası",
        "power": 61,
        "speed": 8,
        "age": 32,
        birthplace: "Utrecht, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 562610,
        "name": "Sontje Hansen",
        "position": "Maestro",
        "power": 64,
        "speed": 5,
        "age": 30,
        birthplace: "Groningen, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 451728,
        "name": "Rober Gonzalez",
        "position": "Sağ Kanat",
        "power": 62,
        "speed": 5,
        "age": 32,
        birthplace: "The Hague, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 214513,
        "name": "Sylla Sow",
        "position": "Sol Kanat",
        "power": 66,
        "speed": 8,
        "age": 24,
        birthplace: "Rotterdam, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 150239,
        "name": "Mees Hoedemakers",
        "position": "Forvet",
        "power": 62,
        "speed": 8,
        "age": 26,
        birthplace: "The Hague, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 979279,
        "name": "Brayann Pereira",
        "position": "Forvet",
        "power": 62,
        "speed": 8,
        "age": 32,
        birthplace: "Groningen, Hollanda", "teamId": "nec_nijmegen",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 833636,
        "name": "Mickey van der Hart",
        "position": "Kaleci",
        "power": 68,
        "speed": 9,
        "age": 27,
        birthplace: "The Hague, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 691003,
        "name": "Pawel Bochniewicz",
        "position": "Stoper",
        "power": 62,
        "speed": 6,
        "age": 27,
        birthplace: "The Hague, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 839385,
        "name": "Sven van Beek",
        "position": "Stoper",
        "power": 63,
        "speed": 7,
        "age": 23,
        birthplace: "Utrecht, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 823420,
        "name": "Mats Kohlert",
        "position": "Stoper",
        "power": 65,
        "speed": 6,
        "age": 24,
        birthplace: "Tilburg, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 943852,
        "name": "Oliver Braude",
        "position": "Sağ Bek",
        "power": 65,
        "speed": 8,
        "age": 31,
        birthplace: "Eindhoven, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 602277,
        "name": "Thom Haye",
        "position": "Sol Bek",
        "power": 66,
        "speed": 8,
        "age": 25,
        birthplace: "Eindhoven, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 910256,
        "name": "Simon Olsson",
        "position": "Ön Libero",
        "power": 61,
        "speed": 7,
        "age": 25,
        birthplace: "Amsterdam, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 809857,
        "name": "Luuk Brouwers",
        "position": "Merkez Orta Saha",
        "power": 63,
        "speed": 9,
        "age": 32,
        birthplace: "Utrecht, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 167969,
        "name": "Osame Sahraoui",
        "position": "Orta Saha",
        "power": 67,
        "speed": 6,
        "age": 20,
        birthplace: "Rotterdam, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 413724,
        "name": "Pelle van Amersfoort",
        "position": "Forvet Arkası",
        "power": 68,
        "speed": 9,
        "age": 30,
        birthplace: "Amsterdam, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 586572,
        "name": "Patrik Walemark",
        "position": "Maestro",
        "power": 61,
        "speed": 9,
        "age": 26,
        birthplace: "Utrecht, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 683450,
        "name": "Ion Nicolaescu",
        "position": "Sağ Kanat",
        "power": 66,
        "speed": 5,
        "age": 20,
        birthplace: "Rotterdam, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 406403,
        "name": "Che Nunnely",
        "position": "Sol Kanat",
        "power": 61,
        "speed": 9,
        "age": 27,
        birthplace: "The Hague, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 536592,
        "name": "Espen van Ee",
        "position": "Forvet",
        "power": 62,
        "speed": 5,
        "age": 31,
        birthplace: "Tilburg, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 217384,
        "name": "Denzel Hall",
        "position": "Forvet",
        "power": 67,
        "speed": 6,
        "age": 28,
        birthplace: "The Hague, Hollanda", "teamId": "heerenveen",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 232792,
        "name": "Jeffrey de Lange",
        "position": "Kaleci",
        "power": 61,
        "speed": 9,
        "age": 27,
        birthplace: "Eindhoven, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 485573,
        "name": "Joris Kramer",
        "position": "Stoper",
        "power": 64,
        "speed": 5,
        "age": 30,
        birthplace: "Groningen, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 767181,
        "name": "Gerrit Nauber",
        "position": "Stoper",
        "power": 66,
        "speed": 6,
        "age": 27,
        birthplace: "Utrecht, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 978028,
        "name": "Bas Kuipers",
        "position": "Stoper",
        "power": 62,
        "speed": 8,
        "age": 24,
        birthplace: "Groningen, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 462268,
        "name": "Mats Deijl",
        "position": "Sağ Bek",
        "power": 64,
        "speed": 9,
        "age": 28,
        birthplace: "Groningen, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 386739,
        "name": "Philippe Rommens",
        "position": "Sol Bek",
        "power": 67,
        "speed": 6,
        "age": 25,
        birthplace: "Groningen, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 120161,
        "name": "Evert Linthorst",
        "position": "Ön Libero",
        "power": 61,
        "speed": 9,
        "age": 26,
        birthplace: "The Hague, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 746295,
        "name": "Willum Willumsson",
        "position": "Merkez Orta Saha",
        "power": 63,
        "speed": 8,
        "age": 22,
        birthplace: "Rotterdam, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 498755,
        "name": "Victor Edvardsen",
        "position": "Orta Saha",
        "power": 62,
        "speed": 8,
        "age": 24,
        birthplace: "Rotterdam, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 335131,
        "name": "Oliver Edvardsen",
        "position": "Forvet Arkası",
        "power": 65,
        "speed": 6,
        "age": 27,
        birthplace: "Amsterdam, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 308874,
        "name": "Sybilla",
        "position": "Maestro",
        "power": 66,
        "speed": 9,
        "age": 22,
        birthplace: "The Hague, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 196290,
        "name": "Soren Tengstedt",
        "position": "Sağ Kanat",
        "power": 68,
        "speed": 8,
        "age": 22,
        birthplace: "Tilburg, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 347759,
        "name": "Finn Stokkers",
        "position": "Sol Kanat",
        "power": 68,
        "speed": 7,
        "age": 21,
        birthplace: "Utrecht, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 667886,
        "name": "Enric Llansana",
        "position": "Forvet",
        "power": 66,
        "speed": 5,
        "age": 30,
        birthplace: "Utrecht, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 982757,
        "name": "Jano Bax",
        "position": "Forvet",
        "power": 63,
        "speed": 5,
        "age": 23,
        birthplace: "Amsterdam, Hollanda", "teamId": "go_ahead_eagles",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 301015,
        "name": "Michael Verrips",
        "position": "Kaleci",
        "power": 61,
        "speed": 5,
        "age": 25,
        birthplace: "Groningen, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 374142,
        "name": "Rodrigo Guth",
        "position": "Stoper",
        "power": 68,
        "speed": 6,
        "age": 25,
        birthplace: "Amsterdam, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 879971,
        "name": "Dimitrios Siovas",
        "position": "Stoper",
        "power": 62,
        "speed": 6,
        "age": 20,
        birthplace: "The Hague, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 213970,
        "name": "Ivo Pinto",
        "position": "Stoper",
        "power": 63,
        "speed": 7,
        "age": 28,
        birthplace: "Utrecht, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 273638,
        "name": "Mitchell Dijks",
        "position": "Sağ Bek",
        "power": 68,
        "speed": 8,
        "age": 30,
        birthplace: "The Hague, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 508734,
        "name": "Deroy Duarte",
        "position": "Sol Bek",
        "power": 63,
        "speed": 5,
        "age": 23,
        birthplace: "Utrecht, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 239672,
        "name": "Alen Halilovic",
        "position": "Ön Libero",
        "power": 61,
        "speed": 5,
        "age": 22,
        birthplace: "Groningen, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 419571,
        "name": "Loreintz Rosier",
        "position": "Merkez Orta Saha",
        "power": 62,
        "speed": 5,
        "age": 29,
        birthplace: "Tilburg, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 417943,
        "name": "Inigo Cordoba",
        "position": "Orta Saha",
        "power": 63,
        "speed": 7,
        "age": 32,
        birthplace: "Eindhoven, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 872668,
        "name": "Kaj Sierhuis",
        "position": "Forvet Arkası",
        "power": 68,
        "speed": 5,
        "age": 22,
        birthplace: "The Hague, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 104118,
        "name": "Justin Lonwijk",
        "position": "Maestro",
        "power": 68,
        "speed": 8,
        "age": 29,
        birthplace: "Utrecht, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 898904,
        "name": "Arianit Ferati",
        "position": "Sağ Kanat",
        "power": 67,
        "speed": 7,
        "age": 22,
        birthplace: "Amsterdam, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 535247,
        "name": "Sadik Fofana",
        "position": "Sol Kanat",
        "power": 68,
        "speed": 5,
        "age": 20,
        birthplace: "The Hague, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 417690,
        "name": "Remy Vita",
        "position": "Forvet",
        "power": 67,
        "speed": 9,
        "age": 25,
        birthplace: "Tilburg, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 464106,
        "name": "Marko Lazetic",
        "position": "Forvet",
        "power": 67,
        "speed": 5,
        "age": 21,
        birthplace: "The Hague, Hollanda", "teamId": "fortuna_sittard",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 409854,
        "name": "Mio Backhaus",
        "position": "Kaleci",
        "power": 61,
        "speed": 5,
        "age": 22,
        birthplace: "Eindhoven, Hollanda", "teamId": "volendam",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 509608,
        "name": "Benaissa Benamar",
        "position": "Stoper",
        "power": 64,
        "speed": 6,
        "age": 21,
        birthplace: "The Hague, Hollanda", "teamId": "volendam",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 210545,
        "name": "Josh Flint",
        "position": "Stoper",
        "power": 62,
        "speed": 5,
        "age": 27,
        birthplace: "Utrecht, Hollanda", "teamId": "volendam",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 680183,
        "name": "Oskar Buur",
        "position": "Stoper",
        "power": 65,
        "speed": 7,
        "age": 22,
        birthplace: "Eindhoven, Hollanda", "teamId": "volendam",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 867283,
        "name": "Brian Plat",
        "position": "Sağ Bek",
        "power": 66,
        "speed": 9,
        "age": 28,
        birthplace: "Tilburg, Hollanda", "teamId": "volendam",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 884984,
        "name": "Damon Mirani",
        "position": "Sol Bek",
        "power": 64,
        "speed": 6,
        "age": 29,
        birthplace: "The Hague, Hollanda", "teamId": "volendam",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 734913,
        "name": "Milan de Haan",
        "position": "Ön Libero",
        "power": 63,
        "speed": 7,
        "age": 28,
        birthplace: "Eindhoven, Hollanda", "teamId": "volendam",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 256651,
        "name": "Calvin Twigt",
        "position": "Merkez Orta Saha",
        "power": 63,
        "speed": 6,
        "age": 28,
        birthplace: "Utrecht, Hollanda", "teamId": "volendam",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 413316,
        "name": "Robert Muhren",
        "position": "Orta Saha",
        "power": 65,
        "speed": 7,
        "age": 22,
        birthplace: "Eindhoven, Hollanda", "teamId": "volendam",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 642414,
        "name": "Vivaldo Semedo",
        "position": "Forvet Arkası",
        "power": 66,
        "speed": 7,
        "age": 20,
        birthplace: "The Hague, Hollanda", "teamId": "volendam",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 577980,
        "name": "Luke Le Roux",
        "position": "Maestro",
        "power": 62,
        "speed": 7,
        "age": 25,
        birthplace: "Eindhoven, Hollanda", "teamId": "volendam",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 272627,
        "name": "Garang Kuol",
        "position": "Sağ Kanat",
        "power": 64,
        "speed": 8,
        "age": 27,
        birthplace: "Groningen, Hollanda", "teamId": "volendam",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 937517,
        "name": "Darius Johnson",
        "position": "Sol Kanat",
        "power": 68,
        "speed": 7,
        "age": 32,
        birthplace: "The Hague, Hollanda", "teamId": "volendam",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 529402,
        "name": "Achraf Douiri",
        "position": "Forvet",
        "power": 63,
        "speed": 9,
        "age": 22,
        birthplace: "Amsterdam, Hollanda", "teamId": "volendam",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 282814,
        "name": "Bram van Driel",
        "position": "Forvet",
        "power": 68,
        "speed": 7,
        "age": 25,
        birthplace: "Amsterdam, Hollanda", "teamId": "volendam",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    }
];
eredivisiePlayers.forEach(p => window.leagueData.players.push(p));
