// js/data_world.js
// GERCEK 2026/2027 DUNYA YILDIZLARI VERILERI
window.leagueData = window.leagueData || { teams: [], players: [] };
window.leagueData.teams = window.leagueData.teams.filter(t => !["inter_miami", "al_nassr", "al_hilal", "al_ittihad", "al_ahli"].includes(t.id));
const worldTeams = [
    {
        "id": "inter_miami",
        "name": "Inter Miami CF",
        "budget": 150,
        "leagueId": "mls"
    },
    {
        "id": "al_nassr",
        "name": "Al Nassr",
        "budget": 400,
        "leagueId": "saudi"
    },
    {
        "id": "al_hilal",
        "name": "Al Hilal",
        "budget": 500,
        "leagueId": "saudi"
    },
    {
        "id": "al_ittihad",
        "name": "Al Ittihad",
        "budget": 350,
        "leagueId": "saudi"
    },
    {
        "id": "al_ahli",
        "name": "Al Ahli",
        "budget": 300,
        "leagueId": "saudi"
    }
];
worldTeams.forEach(t => window.leagueData.teams.push(t));
window.leagueData.players = window.leagueData.players.filter(p => !worldTeams.some(t => t.id === p.teamId));
const worldPlayers = [
    {
        "id": 71204059356,
        "name": "Lionel Messi",
        "position": "Sağ Kanat",
        "power": 88,
        "speed": 2.8,
        "age": 39,
        birthplace: "Mexico City, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 62288145603,
        "name": "Luis Suarez",
        "position": "Stoper",
        "power": 75,
        "speed": 6,
        "age": 25,
        birthplace: "Tokyo, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 34447116131,
        "name": "Sergio Busquets",
        "position": "Stoper",
        "power": 72,
        "speed": 8,
        "age": 23,
        birthplace: "Buenos Aires, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 13182554643,
        "name": "Jordi Alba",
        "position": "Sağ Bek",
        "power": 75,
        "speed": 5,
        "age": 29,
        birthplace: "Mexico City, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 93841862140,
        "name": "Drake Callender",
        "position": "Sol Bek",
        "power": 75,
        "speed": 6,
        "age": 25,
        birthplace: "Montevideo, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 72830256075,
        "name": "Tomas Aviles",
        "position": "Ön Libero",
        "power": 76,
        "speed": 5,
        "age": 21,
        birthplace: "Montevideo, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 14880003314,
        "name": "Federico Redondo",
        "position": "Merkez Orta Saha",
        "power": 75,
        "speed": 6,
        "age": 33,
        birthplace: "Tokyo, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 34243158682,
        "name": "Diego Gomez",
        "position": "Forvet Arkası",
        "power": 71,
        "speed": 7,
        "age": 24,
        birthplace: "Seoul, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 64402576424,
        "name": "Julian Gressel",
        "position": "Sağ Kanat",
        "power": 74,
        "speed": 7,
        "age": 28,
        birthplace: "Sydney, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 90432500722,
        "name": "Matías Rojas",
        "position": "Sol Kanat",
        "power": 73,
        "speed": 9,
        "age": 29,
        birthplace: "Mexico City, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 28590056017,
        "name": "Leonardo Campana",
        "position": "Forvet",
        "power": 72,
        "speed": 9,
        "age": 34,
        birthplace: "Mexico City, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 39023261385,
        "name": "Sergii Kryvtsov",
        "position": "Forvet",
        "power": 73,
        "speed": 9,
        "age": 24,
        birthplace: "Santiago, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 13122811934,
        "name": "Marcelo Weigandt",
        "position": "Orta Saha",
        "power": 75,
        "speed": 5,
        "age": 22,
        birthplace: "Cairo, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 20262149580,
        "name": "David Ruiz",
        "position": "Stoper",
        "power": 73,
        "speed": 5,
        "age": 26,
        birthplace: "Lagos, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 93471211949,
        "name": "Benjamin Cremaschi",
        "position": "Sol Bek",
        "power": 76,
        "speed": 6,
        "age": 31,
        birthplace: "Tokyo, İngiltere", nationality: "İngiltere", "teamId": "inter_miami",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 60858151033,
        "name": "Rastgele Kaleci",
        "position": "Kaleci",
        "power": 75,
        "speed": 5,
        "age": 30,
        birthplace: "Buenos Aires, Arjantin", nationality: "Arjantin", "teamId": "al_nassr",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 73000442160,
        "name": "Sadio Mane",
        "position": "Stoper",
        "power": 79,
        "speed": 7,
        "age": 22,
        birthplace: "Montevideo, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 20295284747,
        "name": "Talisca",
        "position": "Stoper",
        "power": 82,
        "speed": 9,
        "age": 27,
        birthplace: "Bogota, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 31204599064,
        "name": "Marcelo Brozovic",
        "position": "Sağ Bek",
        "power": 84,
        "speed": 7,
        "age": 27,
        birthplace: "Buenos Aires, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 47635744849,
        "name": "Otavio III",
        "position": "Sol Bek",
        "power": 82,
        "speed": 5,
        "age": 31,
        birthplace: "Buenos Aires, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 66672176495,
        "name": "Aymeric Laporte",
        "position": "Ön Libero",
        "power": 84,
        "speed": 5,
        "age": 29,
        birthplace: "Buenos Aires, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 96596671062,
        "name": "Bento II",
        "position": "Merkez Orta Saha",
        "power": 78,
        "speed": 7,
        "age": 23,
        birthplace: "Riyadh, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 11582709030,
        "name": "Sultan Al-Ghannam",
        "position": "Forvet Arkası",
        "power": 79,
        "speed": 9,
        "age": 32,
        birthplace: "Montevideo, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 92695584905,
        "name": "Alex Telles",
        "position": "Sağ Kanat",
        "power": 81,
        "speed": 7,
        "age": 33,
        birthplace: "Dakar, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 75681530179,
        "name": "Abdullah Al-Khaibari",
        "position": "Sol Kanat",
        "power": 84,
        "speed": 5,
        "age": 26,
        birthplace: "Bogota, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 72100805823,
        "name": "Sami Al-Najei",
        "position": "Forvet",
        "power": 85,
        "speed": 7,
        "age": 23,
        birthplace: "Seoul, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 69835353565,
        "name": "Ayman Yahya",
        "position": "Forvet",
        "power": 80,
        "speed": 7,
        "age": 28,
        birthplace: "Santiago, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 71163008085,
        "name": "Abdulrahman Ghareeb",
        "position": "Orta Saha",
        "power": 85,
        "speed": 9,
        "age": 32,
        birthplace: "Lagos, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 29634081957,
        "name": "Mohammed Maran",
        "position": "Stoper",
        "power": 78,
        "speed": 5,
        "age": 32,
        birthplace: "Buenos Aires, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 79103807672,
        "name": "Ali Lajami",
        "position": "Sol Bek",
        "power": 82,
        "speed": 7,
        "age": 24,
        birthplace: "Mexico City, İngiltere", nationality: "İngiltere", "teamId": "al_nassr",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 57241260122,
        "name": "Neymar",
        "position": "Sol Kanat",
        "power": 91,
        "speed": 3.9,
        "age": 34,
        birthplace: "Montevideo, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 72838739956,
        "name": "Aleksandar Mitrovic",
        "position": "Stoper",
        "power": 79,
        "speed": 8,
        "age": 31,
        birthplace: "Dakar, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 24529365176,
        "name": "Sergej Milinkovic-Savic",
        "position": "Stoper",
        "power": 81,
        "speed": 8,
        "age": 32,
        birthplace: "Dakar, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 44962116336,
        "name": "Ruben Neves",
        "position": "Sağ Bek",
        "power": 83,
        "speed": 5,
        "age": 32,
        birthplace: "Bogota, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 31740259066,
        "name": "Malcom",
        "position": "Sol Bek",
        "power": 79,
        "speed": 7,
        "age": 34,
        birthplace: "Riyadh, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 58627916343,
        "name": "Kalidou Koulibaly",
        "position": "Ön Libero",
        "power": 85,
        "speed": 7,
        "age": 25,
        birthplace: "Mexico City, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 21037344954,
        "name": "Yassine Bounou",
        "position": "Merkez Orta Saha",
        "power": 79,
        "speed": 6,
        "age": 33,
        birthplace: "Dakar, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 59786187766,
        "name": "Renan Lodi",
        "position": "Forvet Arkası",
        "power": 80,
        "speed": 6,
        "age": 30,
        birthplace: "Sydney, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 67568575901,
        "name": "Saud Abdulhamid",
        "position": "Sağ Kanat",
        "power": 80,
        "speed": 9,
        "age": 34,
        birthplace: "Cairo, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 19642447309,
        "name": "Salem Al-Dawsari",
        "position": "Sol Kanat",
        "power": 82,
        "speed": 6,
        "age": 24,
        birthplace: "Bogota, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 75303386406,
        "name": "Ali Al-Bulaihi",
        "position": "Forvet",
        "power": 78,
        "speed": 7,
        "age": 26,
        birthplace: "Dakar, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 14939063257,
        "name": "Hassan Tambakti",
        "position": "Forvet",
        "power": 78,
        "speed": 8,
        "age": 23,
        birthplace: "Cairo, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 83290605108,
        "name": "Michael",
        "position": "Orta Saha",
        "power": 83,
        "speed": 7,
        "age": 23,
        birthplace: "Bogota, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 89731971456,
        "name": "Yasser Al-Shahrani",
        "position": "Stoper",
        "power": 81,
        "speed": 6,
        "age": 23,
        birthplace: "Dakar, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 77272039934,
        "name": "Mohamed Kanno",
        "position": "Sol Bek",
        "power": 83,
        "speed": 7,
        "age": 21,
        birthplace: "Sydney, İngiltere", nationality: "İngiltere", "teamId": "al_hilal",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 23173092644,
        "name": "Karim Benzema",
        "position": "Kaleci",
        "power": 91,
        "speed": 6,
        "age": 25,
        birthplace: "Bogota, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 15553172064,
        "name": "N'Golo Kante",
        "position": "Stoper",
        "power": 77,
        "speed": 9,
        "age": 22,
        birthplace: "Sydney, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 55816747732,
        "name": "Fabinho",
        "position": "Stoper",
        "power": 79,
        "speed": 5,
        "age": 32,
        birthplace: "Riyadh, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 37108411878,
        "name": "Moussa Diaby",
        "position": "Sağ Bek",
        "power": 76,
        "speed": 6,
        "age": 26,
        birthplace: "Seoul, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 86648189552,
        "name": "Houssem Aouar",
        "position": "Sol Bek",
        "power": 76,
        "speed": 8,
        "age": 31,
        birthplace: "Tokyo, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 68581884999,
        "name": "Luiz Felipe",
        "position": "Ön Libero",
        "power": 81,
        "speed": 9,
        "age": 32,
        birthplace: "Bogota, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 18619462956,
        "name": "Predrag Rajkovic",
        "position": "Merkez Orta Saha",
        "power": 77,
        "speed": 9,
        "age": 28,
        birthplace: "Cairo, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 70850200515,
        "name": "Jota",
        "position": "Forvet Arkası",
        "power": 82,
        "speed": 5,
        "age": 32,
        birthplace: "Montevideo, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 58307635337,
        "name": "Ahmed Hegazi",
        "position": "Sağ Kanat",
        "power": 78,
        "speed": 6,
        "age": 25,
        birthplace: "Buenos Aires, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 66852318842,
        "name": "Muhannad Al-Shanqeeti",
        "position": "Sol Kanat",
        "power": 80,
        "speed": 7,
        "age": 29,
        birthplace: "Montevideo, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 15649566697,
        "name": "Faisal Al-Ghamdi",
        "position": "Forvet",
        "power": 75,
        "speed": 5,
        "age": 31,
        birthplace: "Riyadh, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 96214785883,
        "name": "Saleh Al-Amri",
        "position": "Forvet",
        "power": 78,
        "speed": 8,
        "age": 27,
        birthplace: "Tokyo, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 55807147472,
        "name": "Abderrazak Hamdallah",
        "position": "Orta Saha",
        "power": 81,
        "speed": 8,
        "age": 34,
        birthplace: "Dakar, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 75284697299,
        "name": "Romarinho",
        "position": "Stoper",
        "power": 78,
        "speed": 9,
        "age": 22,
        birthplace: "Sydney, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 66379316296,
        "name": "Hamed Allah",
        "position": "Sol Bek",
        "power": 76,
        "speed": 5,
        "age": 32,
        birthplace: "Lagos, İngiltere", nationality: "İngiltere", "teamId": "al_ittihad",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 60707827523,
        "name": "Riyad Mahrez",
        "position": "Kaleci",
        "power": 81,
        "speed": 9,
        "age": 22,
        birthplace: "Mexico City, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 69769027605,
        "name": "Roberto Firmino",
        "position": "Stoper",
        "power": 79,
        "speed": 6,
        "age": 29,
        birthplace: "Riyadh, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 12994297999,
        "name": "Edouard Mendy",
        "position": "Stoper",
        "power": 81,
        "speed": 8,
        "age": 30,
        birthplace: "Santiago, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 80539754428,
        "name": "Franck Kessie",
        "position": "Sağ Bek",
        "power": 82,
        "speed": 9,
        "age": 25,
        birthplace: "Bogota, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 87455344838,
        "name": "Gabri Veiga",
        "position": "Sol Bek",
        "power": 76,
        "speed": 8,
        "age": 24,
        birthplace: "Lagos, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 63199207328,
        "name": "Merih Demiral",
        "position": "Ön Libero",
        "power": 79,
        "speed": 7,
        "age": 25,
        birthplace: "Lagos, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 98519251591,
        "name": "Roger Ibanez",
        "position": "Merkez Orta Saha",
        "power": 77,
        "speed": 5,
        "age": 31,
        birthplace: "Tokyo, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 32672070245,
        "name": "Firas Al-Buraikan",
        "position": "Forvet Arkası",
        "power": 75,
        "speed": 7,
        "age": 25,
        birthplace: "Tokyo, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 12673794805,
        "name": "Allan Saint-Maximin",
        "position": "Sağ Kanat",
        "power": 76,
        "speed": 7,
        "age": 31,
        birthplace: "Bogota, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 19398113548,
        "name": "Ali Majrashi",
        "position": "Sol Kanat",
        "power": 77,
        "speed": 8,
        "age": 28,
        birthplace: "Lagos, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 16102722640,
        "name": "Ezgjan Alioski",
        "position": "Forvet",
        "power": 75,
        "speed": 7,
        "age": 32,
        birthplace: "Riyadh, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 83089973189,
        "name": "Bassam Al-Hurayji",
        "position": "Forvet",
        "power": 81,
        "speed": 5,
        "age": 25,
        birthplace: "Montevideo, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 18510319550,
        "name": "Mohammed Al-Majhad",
        "position": "Orta Saha",
        "power": 75,
        "speed": 5,
        "age": 30,
        birthplace: "Sydney, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 68296467874,
        "name": "Ziyad Al-Johani",
        "position": "Stoper",
        "power": 76,
        "speed": 6,
        "age": 30,
        birthplace: "Mexico City, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 35989115190,
        "name": "Sumayhan Al-Nabit",
        "position": "Sol Bek",
        "power": 82,
        "speed": 8,
        "age": 21,
        birthplace: "Montevideo, İngiltere", nationality: "İngiltere", "teamId": "al_ahli",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    }
];
worldPlayers.forEach(p => window.leagueData.players.push(p));
