// js/data_brazil.js
// GERCEK BREZILYA VERILERI
window.leagueData = window.leagueData || { teams: [], players: [] };
const brazilTeams = [
    {
        "id": "palmeiras",
        "name": "Palmeiras",
        "budget": 70,
        "leagueId": "brezilya"
    },
    {
        "id": "flamengo",
        "name": "Flamengo",
        "budget": 75,
        "leagueId": "brezilya"
    },
    {
        "id": "sao_paulo",
        "name": "Sao Paulo",
        "budget": 65,
        "leagueId": "brezilya"
    },
    {
        "id": "atletico_mineiro",
        "name": "Atletico Mineiro",
        "budget": 65,
        "leagueId": "brezilya"
    },
    {
        "id": "fluminense",
        "name": "Fluminense",
        "budget": 60,
        "leagueId": "brezilya"
    },
    {
        "id": "gremio",
        "name": "Gremio",
        "budget": 55,
        "leagueId": "brezilya"
    },
    {
        "id": "internacional",
        "name": "Internacional",
        "budget": 60,
        "leagueId": "brezilya"
    },
    {
        "id": "botafogo",
        "name": "Botafogo",
        "budget": 60,
        "leagueId": "brezilya"
    },
    {
        "id": "cruzeiro",
        "name": "Cruzeiro",
        "budget": 50,
        "leagueId": "brezilya"
    },
    {
        "id": "vasco",
        "name": "Vasco da Gama",
        "budget": 50,
        "leagueId": "brezilya"
    },
    {
        "id": "corinthians",
        "name": "Corinthians",
        "budget": 60,
        "leagueId": "brezilya"
    },
    {
        "id": "athletico_pr",
        "name": "Athletico Paranaense",
        "budget": 55,
        "leagueId": "brezilya"
    }
];
brazilTeams.forEach(t => window.leagueData.teams.push(t));
const brazilPlayers = [
    {
        "id": 461252,
        "name": "Weverton",
        "position": "Kaleci",
        "power": 80,
        "speed": 6,
        "age": 32,
        birthplace: "Manaus, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 584117,
        "name": "Gustavo Gomez",
        "position": "Stoper",
        "power": 77,
        "speed": 8,
        "age": 24,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 407363,
        "name": "Murilo",
        "position": "Stoper",
        "power": 73,
        "speed": 6,
        "age": 24,
        birthplace: "Curitiba, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 608275,
        "name": "Marcos Rocha",
        "position": "Stoper",
        "power": 74,
        "speed": 9,
        "age": 29,
        birthplace: "Salvador, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 732278,
        "name": "Joaquin Piquerez",
        "position": "Sağ Bek",
        "power": 77,
        "speed": 9,
        "age": 25,
        birthplace: "Salvador, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 294761,
        "name": "Ze Rafael",
        "position": "Sol Bek",
        "power": 76,
        "speed": 6,
        "age": 22,
        birthplace: "Bras�lia, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 476164,
        "name": "Richard Rios",
        "position": "Ön Libero",
        "power": 79,
        "speed": 5,
        "age": 27,
        birthplace: "S�o Paulo, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 817977,
        "name": "Raphael Veiga",
        "position": "Merkez Orta Saha",
        "power": 73,
        "speed": 7,
        "age": 25,
        birthplace: "Salvador, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 849450,
        "name": "Dudu",
        "position": "Orta Saha",
        "power": 79,
        "speed": 8,
        "age": 30,
        birthplace: "Curitiba, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 550302,
        "name": "Endrick",
        "position": "Forvet Arkası",
        "power": 74,
        "speed": 9,
        "age": 20,
        birthplace: "Curitiba, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 881071,
        "name": "Rony",
        "position": "Maestro",
        "power": 77,
        "speed": 8,
        "age": 27,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 319063,
        "name": "Jose Manuel Lopez",
        "position": "Sağ Kanat",
        "power": 76,
        "speed": 7,
        "age": 22,
        birthplace: "Manaus, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 534962,
        "name": "Mayke",
        "position": "Sol Kanat",
        "power": 74,
        "speed": 5,
        "age": 29,
        birthplace: "Bras�lia, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 901646,
        "name": "Luan",
        "position": "Forvet",
        "power": 80,
        "speed": 9,
        "age": 24,
        birthplace: "Manaus, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 798994,
        "name": "Gabriel Menino",
        "position": "Forvet",
        "power": 73,
        "speed": 8,
        "age": 28,
        birthplace: "Salvador, Brezilya", "teamId": "palmeiras",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 410168,
        "name": "Agustin Rossi",
        "position": "Kaleci",
        "power": 79,
        "speed": 8,
        "age": 31,
        birthplace: "Fortaleza, Brezilya", "teamId": "flamengo",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 899110,
        "name": "Fabricio Bruno",
        "position": "Stoper",
        "power": 77,
        "speed": 8,
        "age": 31,
        birthplace: "S�o Paulo, Brezilya", "teamId": "flamengo",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 848128,
        "name": "Leo Pereira",
        "position": "Stoper",
        "power": 77,
        "speed": 8,
        "age": 31,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "flamengo",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 897867,
        "name": "Guillermo Varela",
        "position": "Stoper",
        "power": 74,
        "speed": 9,
        "age": 27,
        birthplace: "Curitiba, Brezilya", "teamId": "flamengo",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 968729,
        "name": "Ayrton Lucas",
        "position": "Sağ Bek",
        "power": 78,
        "speed": 7,
        "age": 23,
        birthplace: "Curitiba, Brezilya", "teamId": "flamengo",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 432379,
        "name": "Erick Pulgar",
        "position": "Sol Bek",
        "power": 79,
        "speed": 5,
        "age": 27,
        birthplace: "Manaus, Brezilya", "teamId": "flamengo",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 774170,
        "name": "Gerson",
        "position": "Ön Libero",
        "power": 73,
        "speed": 6,
        "age": 30,
        birthplace: "Bras�lia, Brezilya", "teamId": "flamengo",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 407848,
        "name": "Nicolas de la Cruz",
        "position": "Merkez Orta Saha",
        "power": 78,
        "speed": 9,
        "age": 21,
        birthplace: "Bras�lia, Brezilya", "teamId": "flamengo",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 401488,
        "name": "Giorgian de Arrascaeta",
        "position": "Orta Saha",
        "power": 79,
        "speed": 9,
        "age": 30,
        birthplace: "Salvador, Brezilya", "teamId": "flamengo",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 499811,
        "name": "Everton Cebolinha",
        "position": "Forvet Arkası",
        "power": 78,
        "speed": 8,
        "age": 27,
        birthplace: "Bras�lia, Brezilya", "teamId": "flamengo",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 602245,
        "name": "Pedro",
        "position": "Maestro",
        "power": 73,
        "speed": 5,
        "age": 22,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "flamengo",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 936620,
        "name": "Gabriel Barbosa",
        "position": "Sağ Kanat",
        "power": 73,
        "speed": 9,
        "age": 24,
        birthplace: "Manaus, Brezilya", "teamId": "flamengo",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 150600,
        "name": "Matias Vina",
        "position": "Sol Kanat",
        "power": 80,
        "speed": 6,
        "age": 26,
        birthplace: "Fortaleza, Brezilya", "teamId": "flamengo",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 376541,
        "name": "Bruno Henrique",
        "position": "Forvet",
        "power": 77,
        "speed": 7,
        "age": 25,
        birthplace: "Salvador, Brezilya", "teamId": "flamengo",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 163083,
        "name": "Luiz Araujo",
        "position": "Forvet",
        "power": 79,
        "speed": 7,
        "age": 30,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "flamengo",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 412038,
        "name": "Rafael",
        "position": "Kaleci",
        "power": 68,
        "speed": 8,
        "age": 19,
        birthplace: "Bras�lia, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 485160,
        "name": "Robert Arboleda",
        "position": "Stoper",
        "power": 72,
        "speed": 8,
        "age": 28,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 480506,
        "name": "Diego Costa",
        "position": "Stoper",
        "power": 72,
        "speed": 6,
        "age": 24,
        birthplace: "Manaus, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 128005,
        "name": "Igor Vinicius",
        "position": "Stoper",
        "power": 75,
        "speed": 9,
        "age": 22,
        birthplace: "Salvador, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 172354,
        "name": "Welington",
        "position": "Sağ Bek",
        "power": 69,
        "speed": 6,
        "age": 24,
        birthplace: "S�o Paulo, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 524492,
        "name": "Pablo Maia",
        "position": "Sol Bek",
        "power": 68,
        "speed": 5,
        "age": 19,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 624634,
        "name": "Alisson",
        "position": "Kaleci",
        "power": 72,
        "speed": 6,
        "age": 27,
        birthplace: "Salvador, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 405718,
        "name": "James Rodriguez",
        "position": "Merkez Orta Saha",
        "power": 71,
        "speed": 8,
        "age": 29,
        birthplace: "Bras�lia, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 853075,
        "name": "Lucas Moura",
        "position": "Orta Saha",
        "power": 70,
        "speed": 5,
        "age": 21,
        birthplace: "Curitiba, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 655226,
        "name": "Wellington Rato",
        "position": "Forvet Arkası",
        "power": 73,
        "speed": 6,
        "age": 31,
        birthplace: "S�o Paulo, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 460961,
        "name": "Jonathan Calleri",
        "position": "Maestro",
        "power": 71,
        "speed": 9,
        "age": 23,
        birthplace: "Curitiba, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 334240,
        "name": "Giuliano Galoppo",
        "position": "Sağ Kanat",
        "power": 68,
        "speed": 8,
        "age": 29,
        birthplace: "Fortaleza, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 291146,
        "name": "Ferraresi",
        "position": "Sol Kanat",
        "power": 68,
        "speed": 7,
        "age": 30,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 341645,
        "name": "Luciano",
        "position": "Forvet",
        "power": 68,
        "speed": 5,
        "age": 30,
        birthplace: "Curitiba, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 886274,
        "name": "Rodrigo Nestor",
        "position": "Forvet",
        "power": 68,
        "speed": 9,
        "age": 25,
        birthplace: "Manaus, Brezilya", "teamId": "sao_paulo",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 913278,
        "name": "Everson",
        "position": "Kaleci",
        "power": 69,
        "speed": 8,
        "age": 29,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 192463,
        "name": "Jemerson",
        "position": "Stoper",
        "power": 73,
        "speed": 5,
        "age": 31,
        birthplace: "Bras�lia, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 653964,
        "name": "Bruno Fuchs",
        "position": "Stoper",
        "power": 73,
        "speed": 7,
        "age": 30,
        birthplace: "Salvador, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 684053,
        "name": "Renzo Saravia",
        "position": "Stoper",
        "power": 71,
        "speed": 6,
        "age": 26,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 106460,
        "name": "Guilherme Arana",
        "position": "Sağ Bek",
        "power": 69,
        "speed": 9,
        "age": 22,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 590214,
        "name": "Otavio",
        "position": "Sol Bek",
        "power": 75,
        "speed": 8,
        "age": 22,
        birthplace: "S�o Paulo, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 525835,
        "name": "Rodrigo Battaglia",
        "position": "Ön Libero",
        "power": 68,
        "speed": 8,
        "age": 22,
        birthplace: "Curitiba, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 490666,
        "name": "Matias Zaracho",
        "position": "Merkez Orta Saha",
        "power": 70,
        "speed": 7,
        "age": 27,
        birthplace: "Bras�lia, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 186418,
        "name": "Gustavo Scarpa",
        "position": "Orta Saha",
        "power": 72,
        "speed": 8,
        "age": 32,
        birthplace: "Fortaleza, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "anchor",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 941240,
        "name": "Paulinho",
        "position": "Forvet Arkası",
        "power": 72,
        "speed": 8,
        "age": 29,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 484533,
        "name": "Hulk",
        "position": "Maestro",
        "power": 75,
        "speed": 9,
        "age": 31,
        birthplace: "S�o Paulo, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 739259,
        "name": "Igor Gomes",
        "position": "Sağ Kanat",
        "power": 75,
        "speed": 7,
        "age": 27,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 268084,
        "name": "Eduardo Vargas",
        "position": "Sol Kanat",
        "power": 72,
        "speed": 6,
        "age": 32,
        birthplace: "Fortaleza, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 942064,
        "name": "Alan Franco",
        "position": "Forvet",
        "power": 74,
        "speed": 6,
        "age": 19,
        birthplace: "Bras�lia, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 586852,
        "name": "Mariano",
        "position": "Forvet",
        "power": 70,
        "speed": 9,
        "age": 27,
        birthplace: "Fortaleza, Brezilya", "teamId": "atletico_mineiro",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 244591,
        "name": "Fabio",
        "position": "Kaleci",
        "power": 69,
        "speed": 9,
        "age": 26,
        birthplace: "Bras�lia, Brezilya", "teamId": "fluminense",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 235561,
        "name": "Thiago Silva",
        "position": "Stoper",
        "power": 74,
        "speed": 6,
        "age": 27,
        birthplace: "Bras�lia, Brezilya", "teamId": "fluminense",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 375691,
        "name": "Felipe Melo",
        "position": "Stoper",
        "power": 68,
        "speed": 7,
        "age": 28,
        birthplace: "Curitiba, Brezilya", "teamId": "fluminense",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 683428,
        "name": "Samuel Xavier",
        "position": "Stoper",
        "power": 74,
        "speed": 5,
        "age": 27,
        birthplace: "Bras�lia, Brezilya", "teamId": "fluminense",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 158101,
        "name": "Marcelo",
        "position": "Sağ Bek",
        "power": 71,
        "speed": 5,
        "age": 30,
        birthplace: "Salvador, Brezilya", "teamId": "fluminense",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 297955,
        "name": "Andre",
        "position": "Sol Bek",
        "power": 69,
        "speed": 5,
        "age": 30,
        birthplace: "Manaus, Brezilya", "teamId": "fluminense",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 536224,
        "name": "Martinelli",
        "position": "Ön Libero",
        "power": 69,
        "speed": 5,
        "age": 28,
        birthplace: "Salvador, Brezilya", "teamId": "fluminense",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 543221,
        "name": "Paulo Henrique Ganso",
        "position": "Merkez Orta Saha",
        "power": 73,
        "speed": 6,
        "age": 23,
        birthplace: "Curitiba, Brezilya", "teamId": "fluminense",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 276226,
        "name": "Jhon Arias",
        "position": "Orta Saha",
        "power": 68,
        "speed": 9,
        "age": 27,
        birthplace: "Manaus, Brezilya", "teamId": "fluminense",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 826185,
        "name": "Keno",
        "position": "Forvet Arkası",
        "power": 74,
        "speed": 6,
        "age": 25,
        birthplace: "Salvador, Brezilya", "teamId": "fluminense",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 342604,
        "name": "German Cano",
        "position": "Maestro",
        "power": 71,
        "speed": 8,
        "age": 29,
        birthplace: "Manaus, Brezilya", "teamId": "fluminense",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 681267,
        "name": "John Kennedy",
        "position": "Sağ Kanat",
        "power": 74,
        "speed": 5,
        "age": 20,
        birthplace: "Bras�lia, Brezilya", "teamId": "fluminense",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 348290,
        "name": "Renato Augusto",
        "position": "Sol Kanat",
        "power": 69,
        "speed": 5,
        "age": 32,
        birthplace: "S�o Paulo, Brezilya", "teamId": "fluminense",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 169354,
        "name": "Douglas Costa",
        "position": "Forvet",
        "power": 71,
        "speed": 6,
        "age": 21,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "fluminense",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 455214,
        "name": "Guga",
        "position": "Forvet",
        "power": 75,
        "speed": 6,
        "age": 21,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "fluminense",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 852621,
        "name": "Agustin Marchesin",
        "position": "Kaleci",
        "power": 74,
        "speed": 7,
        "age": 22,
        birthplace: "S�o Paulo, Brezilya", "teamId": "gremio",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 342495,
        "name": "Walter Kannemann",
        "position": "Stoper",
        "power": 73,
        "speed": 6,
        "age": 23,
        birthplace: "S�o Paulo, Brezilya", "teamId": "gremio",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 339857,
        "name": "Pedro Geromel",
        "position": "Stoper",
        "power": 74,
        "speed": 6,
        "age": 23,
        birthplace: "Salvador, Brezilya", "teamId": "gremio",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 521842,
        "name": "Joao Pedro",
        "position": "Stoper",
        "power": 74,
        "speed": 7,
        "age": 30,
        birthplace: "Fortaleza, Brezilya", "teamId": "gremio",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 775214,
        "name": "Reinaldo",
        "position": "Sağ Bek",
        "power": 74,
        "speed": 7,
        "age": 22,
        birthplace: "S�o Paulo, Brezilya", "teamId": "gremio",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 567438,
        "name": "Mathias Villasanti",
        "position": "Sol Bek",
        "power": 68,
        "speed": 7,
        "age": 31,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "gremio",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 355072,
        "name": "Pepe",
        "position": "Ön Libero",
        "power": 70,
        "speed": 9,
        "age": 29,
        birthplace: "Curitiba, Brezilya", "teamId": "gremio",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 135070,
        "name": "Franco Cristaldo",
        "position": "Merkez Orta Saha",
        "power": 69,
        "speed": 7,
        "age": 28,
        birthplace: "Manaus, Brezilya", "teamId": "gremio",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 616537,
        "name": "Yeferson Soteldo",
        "position": "Orta Saha",
        "power": 75,
        "speed": 5,
        "age": 24,
        birthplace: "Manaus, Brezilya", "teamId": "gremio",
        "tacticalRole": "playmaker",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 618334,
        "name": "Cristian Pavon",
        "position": "Forvet Arkası",
        "power": 74,
        "speed": 6,
        "age": 29,
        birthplace: "Bras�lia, Brezilya", "teamId": "gremio",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 278312,
        "name": "Diego Costa II",
        "position": "Maestro",
        "power": 74,
        "speed": 5,
        "age": 23,
        birthplace: "Salvador, Brezilya", "teamId": "gremio",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 913139,
        "name": "Du Queiroz",
        "position": "Sağ Kanat",
        "power": 68,
        "speed": 6,
        "age": 32,
        birthplace: "S�o Paulo, Brezilya", "teamId": "gremio",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 736807,
        "name": "Dodi",
        "position": "Sol Kanat",
        "power": 75,
        "speed": 6,
        "age": 24,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "gremio",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 336844,
        "name": "Fábio",
        "position": "Forvet",
        "power": 70,
        "speed": 9,
        "age": 22,
        birthplace: "Fortaleza, Brezilya", "teamId": "gremio",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 720884,
        "name": "Ely",
        "position": "Forvet",
        "power": 73,
        "speed": 6,
        "age": 22,
        birthplace: "Bras�lia, Brezilya", "teamId": "gremio",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 125125,
        "name": "Sergio Rochet",
        "position": "Kaleci",
        "power": 73,
        "speed": 8,
        "age": 30,
        birthplace: "Salvador, Brezilya", "teamId": "internacional",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 740547,
        "name": "Vitao",
        "position": "Stoper",
        "power": 75,
        "speed": 8,
        "age": 27,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "internacional",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 775503,
        "name": "Gabriel Mercado",
        "position": "Stoper",
        "power": 73,
        "speed": 7,
        "age": 27,
        birthplace: "Bras�lia, Brezilya", "teamId": "internacional",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 140178,
        "name": "Fabricio Bustos",
        "position": "Stoper",
        "power": 73,
        "speed": 5,
        "age": 20,
        birthplace: "Salvador, Brezilya", "teamId": "internacional",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 407766,
        "name": "Rene",
        "position": "Sağ Bek",
        "power": 74,
        "speed": 5,
        "age": 20,
        birthplace: "Manaus, Brezilya", "teamId": "internacional",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 782819,
        "name": "Charles Aranguiz",
        "position": "Sol Bek",
        "power": 72,
        "speed": 5,
        "age": 24,
        birthplace: "Curitiba, Brezilya", "teamId": "internacional",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 287641,
        "name": "Thiago Maia",
        "position": "Ön Libero",
        "power": 70,
        "speed": 6,
        "age": 27,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "internacional",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 317946,
        "name": "Alan Patrick",
        "position": "Merkez Orta Saha",
        "power": 75,
        "speed": 7,
        "age": 24,
        birthplace: "Fortaleza, Brezilya", "teamId": "internacional",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 223145,
        "name": "Mauricio",
        "position": "Orta Saha",
        "power": 68,
        "speed": 8,
        "age": 21,
        birthplace: "S�o Paulo, Brezilya", "teamId": "internacional",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 314422,
        "name": "Wanderson",
        "position": "Forvet Arkası",
        "power": 70,
        "speed": 8,
        "age": 31,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "internacional",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 426060,
        "name": "Enner Valencia",
        "position": "Maestro",
        "power": 71,
        "speed": 7,
        "age": 24,
        birthplace: "Bras�lia, Brezilya", "teamId": "internacional",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 364405,
        "name": "Rafael Borre",
        "position": "Sağ Kanat",
        "power": 71,
        "speed": 5,
        "age": 25,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "internacional",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 429688,
        "name": "Bruno Henrique II",
        "position": "Sol Kanat",
        "power": 70,
        "speed": 8,
        "age": 21,
        birthplace: "Bras�lia, Brezilya", "teamId": "internacional",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 811943,
        "name": "Fernando",
        "position": "Forvet",
        "power": 73,
        "speed": 8,
        "age": 29,
        birthplace: "Bras�lia, Brezilya", "teamId": "internacional",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 661402,
        "name": "Lucas Alario",
        "position": "Forvet",
        "power": 69,
        "speed": 9,
        "age": 32,
        birthplace: "Bras�lia, Brezilya", "teamId": "internacional",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 282306,
        "name": "Gatito Fernandez",
        "position": "Kaleci",
        "power": 73,
        "speed": 9,
        "age": 24,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "botafogo",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 774910,
        "name": "Alexander Barboza",
        "position": "Stoper",
        "power": 75,
        "speed": 5,
        "age": 20,
        birthplace: "Fortaleza, Brezilya", "teamId": "botafogo",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 712875,
        "name": "Lucas Halter",
        "position": "Stoper",
        "power": 73,
        "speed": 7,
        "age": 27,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "botafogo",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 625857,
        "name": "Damian Suarez",
        "position": "Stoper",
        "power": 73,
        "speed": 8,
        "age": 29,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "botafogo",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 714511,
        "name": "Hugo",
        "position": "Sağ Bek",
        "power": 69,
        "speed": 7,
        "age": 30,
        birthplace: "Fortaleza, Brezilya", "teamId": "botafogo",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 406316,
        "name": "Marlon Freitas",
        "position": "Sol Bek",
        "power": 72,
        "speed": 7,
        "age": 24,
        birthplace: "Manaus, Brezilya", "teamId": "botafogo",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 982052,
        "name": "Tche Tche",
        "position": "Ön Libero",
        "power": 68,
        "speed": 6,
        "age": 22,
        birthplace: "Bras�lia, Brezilya", "teamId": "botafogo",
        "tacticalRole": "target_man",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 599140,
        "name": "Eduardo",
        "position": "Merkez Orta Saha",
        "power": 70,
        "speed": 9,
        "age": 25,
        birthplace: "Curitiba, Brezilya", "teamId": "botafogo",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 609229,
        "name": "Jefferson Savarino",
        "position": "Orta Saha",
        "power": 74,
        "speed": 7,
        "age": 23,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "botafogo",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 350479,
        "name": "Luiz Henrique",
        "position": "Forvet Arkası",
        "power": 74,
        "speed": 6,
        "age": 32,
        birthplace: "Manaus, Brezilya", "teamId": "botafogo",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 363870,
        "name": "Tiquinho Soares",
        "position": "Maestro",
        "power": 74,
        "speed": 6,
        "age": 20,
        birthplace: "Salvador, Brezilya", "teamId": "botafogo",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 848699,
        "name": "Junior Santos",
        "position": "Sağ Kanat",
        "power": 75,
        "speed": 8,
        "age": 26,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "botafogo",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 848636,
        "name": "Gret",
        "position": "Sol Kanat",
        "power": 74,
        "speed": 7,
        "age": 29,
        birthplace: "Bras�lia, Brezilya", "teamId": "botafogo",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 501192,
        "name": "Danilo Barbosa",
        "position": "Forvet",
        "power": 72,
        "speed": 7,
        "age": 32,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "botafogo",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 843341,
        "name": "Matias Segovia",
        "position": "Forvet",
        "power": 75,
        "speed": 7,
        "age": 32,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "botafogo",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 297388,
        "name": "Rafael Cabral",
        "position": "Kaleci",
        "power": 73,
        "speed": 7,
        "age": 31,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 184814,
        "name": "Neris",
        "position": "Stoper",
        "power": 71,
        "speed": 6,
        "age": 29,
        birthplace: "Curitiba, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 741939,
        "name": "Ze Ivaldo",
        "position": "Stoper",
        "power": 68,
        "speed": 9,
        "age": 25,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 141509,
        "name": "William",
        "position": "Stoper",
        "power": 69,
        "speed": 9,
        "age": 31,
        birthplace: "Salvador, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 686742,
        "name": "Marlon",
        "position": "Sağ Bek",
        "power": 74,
        "speed": 6,
        "age": 20,
        birthplace: "S�o Paulo, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 996782,
        "name": "Lucas Romero",
        "position": "Sol Bek",
        "power": 69,
        "speed": 6,
        "age": 31,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 441698,
        "name": "Lucas Silva",
        "position": "Ön Libero",
        "power": 72,
        "speed": 9,
        "age": 24,
        birthplace: "S�o Paulo, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 341552,
        "name": "Matheus Pereira",
        "position": "Merkez Orta Saha",
        "power": 68,
        "speed": 7,
        "age": 28,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 944037,
        "name": "Arthur Gomes",
        "position": "Orta Saha",
        "power": 68,
        "speed": 7,
        "age": 26,
        birthplace: "Fortaleza, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 153340,
        "name": "Juan Dinenno",
        "position": "Forvet Arkası",
        "power": 75,
        "speed": 7,
        "age": 23,
        birthplace: "Salvador, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 486429,
        "name": "Rafael Elias",
        "position": "Maestro",
        "power": 69,
        "speed": 9,
        "age": 24,
        birthplace: "Fortaleza, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "inside_forward",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 318157,
        "name": "Mateus Vital",
        "position": "Sağ Kanat",
        "power": 71,
        "speed": 6,
        "age": 22,
        birthplace: "Manaus, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 849766,
        "name": "Ramiro",
        "position": "Sol Kanat",
        "power": 72,
        "speed": 7,
        "age": 30,
        birthplace: "S�o Paulo, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 788401,
        "name": "Kaiki",
        "position": "Forvet",
        "power": 70,
        "speed": 5,
        "age": 25,
        birthplace: "Bras�lia, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 929482,
        "name": "Wesley Gasolina",
        "position": "Forvet",
        "power": 70,
        "speed": 6,
        "age": 29,
        birthplace: "Salvador, Brezilya", "teamId": "cruzeiro",
        "tacticalRole": "false_9",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 630779,
        "name": "Leo Jardim",
        "position": "Kaleci",
        "power": 70,
        "speed": 9,
        "age": 31,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "vasco",
        "tacticalRole": "classic",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 141403,
        "name": "Gary Medel",
        "position": "Stoper",
        "power": 72,
        "speed": 8,
        "age": 25,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "vasco",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 974385,
        "name": "Leo",
        "position": "Stoper",
        "power": 75,
        "speed": 8,
        "age": 28,
        birthplace: "Salvador, Brezilya", "teamId": "vasco",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 108149,
        "name": "Paulo Henrique",
        "position": "Stoper",
        "power": 68,
        "speed": 7,
        "age": 24,
        birthplace: "S�o Paulo, Brezilya", "teamId": "vasco",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 714574,
        "name": "Lucas Piton",
        "position": "Sağ Bek",
        "power": 71,
        "speed": 9,
        "age": 25,
        birthplace: "Bras�lia, Brezilya", "teamId": "vasco",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 720516,
        "name": "Ze Gabriel",
        "position": "Sol Bek",
        "power": 68,
        "speed": 8,
        "age": 19,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "vasco",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 720388,
        "name": "Galdames",
        "position": "Ön Libero",
        "power": 71,
        "speed": 7,
        "age": 31,
        birthplace: "S�o Paulo, Brezilya", "teamId": "vasco",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 292151,
        "name": "Dimitri Payet",
        "position": "Merkez Orta Saha",
        "power": 70,
        "speed": 5,
        "age": 27,
        birthplace: "Curitiba, Brezilya", "teamId": "vasco",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 165987,
        "name": "David",
        "position": "Orta Saha",
        "power": 71,
        "speed": 6,
        "age": 29,
        birthplace: "Salvador, Brezilya", "teamId": "vasco",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 186233,
        "name": "Adson",
        "position": "Forvet Arkası",
        "power": 74,
        "speed": 5,
        "age": 24,
        birthplace: "Fortaleza, Brezilya", "teamId": "vasco",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 616011,
        "name": "Pablo Vegetti",
        "position": "Maestro",
        "power": 68,
        "speed": 9,
        "age": 32,
        birthplace: "Curitiba, Brezilya", "teamId": "vasco",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 256114,
        "name": "Rayan",
        "position": "Sağ Kanat",
        "power": 68,
        "speed": 5,
        "age": 32,
        birthplace: "Bras�lia, Brezilya", "teamId": "vasco",
        "tacticalRole": "false_9",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 376569,
        "name": "Joao Victor",
        "position": "Sol Kanat",
        "power": 71,
        "speed": 7,
        "age": 31,
        birthplace: "S�o Paulo, Brezilya", "teamId": "vasco",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 174685,
        "name": "Praxedes",
        "position": "Forvet",
        "power": 69,
        "speed": 5,
        "age": 27,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "vasco",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 967039,
        "name": "Puma Rodriguez",
        "position": "Forvet",
        "power": 75,
        "speed": 6,
        "age": 22,
        birthplace: "Curitiba, Brezilya", "teamId": "vasco",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 124256,
        "name": "Cassio",
        "position": "Kaleci",
        "power": 74,
        "speed": 6,
        "age": 29,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "corinthians",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 235052,
        "name": "Felix Torres",
        "position": "Stoper",
        "power": 69,
        "speed": 9,
        "age": 25,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "corinthians",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 650653,
        "name": "Gustavo Henrique",
        "position": "Stoper",
        "power": 74,
        "speed": 7,
        "age": 20,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "corinthians",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 566265,
        "name": "Fagner",
        "position": "Stoper",
        "power": 72,
        "speed": 7,
        "age": 30,
        birthplace: "Fortaleza, Brezilya", "teamId": "corinthians",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 411467,
        "name": "Hugo II",
        "position": "Sağ Bek",
        "power": 71,
        "speed": 9,
        "age": 23,
        birthplace: "Manaus, Brezilya", "teamId": "corinthians",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 277501,
        "name": "Raniele",
        "position": "Sol Bek",
        "power": 71,
        "speed": 9,
        "age": 21,
        birthplace: "Fortaleza, Brezilya", "teamId": "corinthians",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 460689,
        "name": "Rodrigo Garro",
        "position": "Ön Libero",
        "power": 70,
        "speed": 9,
        "age": 28,
        birthplace: "Salvador, Brezilya", "teamId": "corinthians",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 169861,
        "name": "Maycon",
        "position": "Merkez Orta Saha",
        "power": 74,
        "speed": 5,
        "age": 27,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "corinthians",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 739706,
        "name": "Wesley",
        "position": "Orta Saha",
        "power": 71,
        "speed": 8,
        "age": 26,
        birthplace: "Fortaleza, Brezilya", "teamId": "corinthians",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 620235,
        "name": "Romero",
        "position": "Forvet Arkası",
        "power": 71,
        "speed": 6,
        "age": 29,
        birthplace: "S�o Paulo, Brezilya", "teamId": "corinthians",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 240901,
        "name": "Yuri Alberto",
        "position": "Maestro",
        "power": 68,
        "speed": 7,
        "age": 29,
        birthplace: "Salvador, Brezilya", "teamId": "corinthians",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 763166,
        "name": "Pedro Raul",
        "position": "Sağ Kanat",
        "power": 75,
        "speed": 7,
        "age": 27,
        birthplace: "Rio de Janeiro, Brezilya", "teamId": "corinthians",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 226866,
        "name": "Fausto Vera",
        "position": "Sol Kanat",
        "power": 75,
        "speed": 6,
        "age": 20,
        birthplace: "S�o Paulo, Brezilya", "teamId": "corinthians",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 189494,
        "name": "Matheus Bidu",
        "position": "Forvet",
        "power": 70,
        "speed": 5,
        "age": 29,
        birthplace: "Bras�lia, Brezilya", "teamId": "corinthians",
        "tacticalRole": "target_man",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 319373,
        "name": "Breno Bidon",
        "position": "Forvet",
        "power": 74,
        "speed": 5,
        "age": 22,
        birthplace: "Curitiba, Brezilya", "teamId": "corinthians",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 650336,
        "name": "Bento",
        "position": "Kaleci",
        "power": 69,
        "speed": 5,
        "age": 23,
        birthplace: "Salvador, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "poacher",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 709916,
        "name": "Thiago Heleno",
        "position": "Stoper",
        "power": 73,
        "speed": 8,
        "age": 29,
        birthplace: "Manaus, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 631336,
        "name": "Caca",
        "position": "Stoper",
        "power": 68,
        "speed": 7,
        "age": 22,
        birthplace: "Curitiba, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 574046,
        "name": "Madson",
        "position": "Stoper",
        "power": 68,
        "speed": 6,
        "age": 30,
        birthplace: "Belo Horizonte, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 880861,
        "name": "Esquivel",
        "position": "Sağ Bek",
        "power": 69,
        "speed": 8,
        "age": 19,
        birthplace: "Curitiba, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 462506,
        "name": "Fernandinho",
        "position": "Sol Bek",
        "power": 70,
        "speed": 8,
        "age": 25,
        birthplace: "Fortaleza, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 938911,
        "name": "Erick",
        "position": "Ön Libero",
        "power": 73,
        "speed": 7,
        "age": 30,
        birthplace: "Curitiba, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 428365,
        "name": "Bruno Zapelli",
        "position": "Merkez Orta Saha",
        "power": 75,
        "speed": 8,
        "age": 20,
        birthplace: "Fortaleza, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "false_9",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 430128,
        "name": "Canobbio",
        "position": "Orta Saha",
        "power": 72,
        "speed": 5,
        "age": 21,
        birthplace: "Fortaleza, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "regista",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 758208,
        "name": "Cuello",
        "position": "Forvet Arkası",
        "power": 69,
        "speed": 5,
        "age": 25,
        birthplace: "Curitiba, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 682301,
        "name": "Pablo",
        "position": "Maestro",
        "power": 74,
        "speed": 8,
        "age": 31,
        birthplace: "Curitiba, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "target_man",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 771320,
        "name": "Mastriani",
        "position": "Sağ Kanat",
        "power": 68,
        "speed": 5,
        "age": 31,
        birthplace: "Bras�lia, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 602652,
        "name": "Alex Santana",
        "position": "Sol Kanat",
        "power": 72,
        "speed": 9,
        "age": 22,
        birthplace: "Salvador, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 898739,
        "name": "Hugo Moura",
        "position": "Forvet",
        "power": 69,
        "speed": 7,
        "age": 23,
        birthplace: "Fortaleza, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 366805,
        "name": "Christian",
        "position": "Forvet",
        "power": 71,
        "speed": 8,
        "age": 32,
        birthplace: "Fortaleza, Brezilya", "teamId": "athletico_pr",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    }
];
brazilPlayers.forEach(p => window.leagueData.players.push(p));
