// js/data_laliga.js
// GERCEK 2026/2027 LA LIGA VERILERI
window.leagueData = window.leagueData || { teams: [], players: [] };
window.leagueData.teams = window.leagueData.teams.filter(t => t.leagueId !== 'laliga');
const laligaTeams = [
    {
        "id": "real_madrid",
        "name": "Real Madrid",
        "color": "#FFFFFF",
        "budget": 122,
        "leagueId": "laliga"
    },
    {
        "id": "barcelona",
        "name": "FC Barcelona",
        "color": "#A50044",
        "budget": 115,
        "leagueId": "laliga"
    },
    {
        "id": "atletico_madrid",
        "name": "Atlético Madrid",
        "color": "#CB3524",
        "budget": 58,
        "leagueId": "laliga"
    },
    {
        "id": "villarreal",
        "name": "Villarreal CF",
        "color": "#FCE300",
        "budget": 30,
        "leagueId": "laliga"
    },
    {
        "id": "real_sociedad",
        "name": "Real Sociedad",
        "color": "#0067B1",
        "budget": 26,
        "leagueId": "laliga"
    },
    {
        "id": "real_betis",
        "name": "Real Betis",
        "color": "#0BA35C",
        "budget": 25,
        "leagueId": "laliga"
    },
    {
        "id": "athletic_bilbao",
        "name": "Athletic Bilbao",
        "color": "#EE2523",
        "budget": 23,
        "leagueId": "laliga"
    },
    {
        "id": "celta_vigo",
        "name": "Celta Vigo",
        "color": "#ADD8E6",
        "budget": 19,
        "leagueId": "laliga"
    },
    {
        "id": "sevilla",
        "name": "Sevilla FC",
        "color": "#D01A22",
        "budget": 15,
        "leagueId": "laliga"
    },
    {
        "id": "girona",
        "name": "Girona FC",
        "color": "#ED1C24",
        "budget": 14,
        "leagueId": "laliga"
    },
    {
        "id": "valencia",
        "name": "Valencia CF",
        "color": "#000000",
        "budget": 14,
        "leagueId": "laliga"
    },
    {
        "id": "espanyol_barcelona",
        "name": "Espanyol Barcelona",
        "color": "#004B87",
        "budget": 12,
        "leagueId": "laliga"
    },
    {
        "id": "levante",
        "name": "Levante UD",
        "color": "#004B87",
        "budget": 11,
        "leagueId": "laliga"
    },
    {
        "id": "rayo_valleno",
        "name": "Rayo Vallecano",
        "color": "#FFFFFF",
        "budget": 11,
        "leagueId": "laliga"
    },
    {
        "id": "osasuna",
        "name": "CA Osasuna",
        "color": "#D0112B",
        "budget": 10,
        "leagueId": "laliga"
    },
    {
        "id": "elche",
        "name": "Elche CF",
        "color": "#FFFFFF",
        "budget": 10,
        "leagueId": "laliga"
    },
    {
        "id": "mallor",
        "name": "RCD Mallorca",
        "color": "#D82028",
        "budget": 8,
        "leagueId": "laliga"
    },
    {
        "id": "getafe",
        "name": "Getafe CF",
        "color": "#0044A1",
        "budget": 8,
        "leagueId": "laliga"
    },
    {
        "id": "deportivo_alaves",
        "name": "Deportivo Alavés",
        "color": "#00539C",
        "budget": 7,
        "leagueId": "laliga"
    },
    {
        "id": "real_oviedo",
        "name": "Real Oviedo",
        "color": "#004A99",
        "budget": 6,
        "leagueId": "laliga"
    }
];
laligaTeams.forEach(t => window.leagueData.teams.push(t));
window.leagueData.players = window.leagueData.players.filter(p => !laligaTeams.some(t => t.id === p.teamId));
const laligaPlayers = [
    {
        "id": 743870,
        "name": "Unai Simon",
        "position": "Kaleci",
        "power": 81,
        "speed": 6,
        "age": 26,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 856158,
        "name": "Daniel Vivian",
        "position": "Stoper",
        "power": 83,
        "speed": 5,
        "age": 32,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 634835,
        "name": "Yeray Alvarez",
        "position": "Stoper",
        "power": 79,
        "speed": 5,
        "age": 23,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 650219,
        "name": "Oscar de Marcos",
        "position": "Sağ Bek",
        "power": 77,
        "speed": 9,
        "age": 30,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "regista",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 265726,
        "name": "Yuri Berchiche",
        "position": "Sol Bek",
        "power": 76,
        "speed": 9,
        "age": 28,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 644062,
        "name": "Benat Prados",
        "position": "Ön Libero",
        "power": 82,
        "speed": 6,
        "age": 26,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "sweeper_keeper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 830121,
        "name": "Oihan Sancet",
        "position": "Merkez Orta Saha",
        "power": 81,
        "speed": 8,
        "age": 29,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 299699,
        "name": "Nico Williams",
        "position": "Forvet Arkası",
        "power": 77,
        "speed": 5,
        "age": 33,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 568758,
        "name": "Inaki Williams",
        "position": "Sağ Kanat",
        "power": 80,
        "speed": 9,
        "age": 34,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 936088,
        "name": "Gorka Guruzeta",
        "position": "Sol Kanat",
        "power": 77,
        "speed": 8,
        "age": 26,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 876027,
        "name": "Alex Berenguer",
        "position": "Forvet",
        "power": 77,
        "speed": 9,
        "age": 28,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 772250,
        "name": "Mikel Vesga",
        "position": "Forvet",
        "power": 77,
        "speed": 6,
        "age": 32,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "box_to_box",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 681014,
        "name": "Aitor Paredes",
        "position": "Orta Saha",
        "power": 79,
        "speed": 8,
        "age": 30,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "regista",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 855391,
        "name": "Julen Agirrezabala",
        "position": "Stoper",
        "power": 77,
        "speed": 5,
        "age": 25,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 530495,
        "name": "Alvaro Djalo",
        "position": "Sol Bek",
        "power": 79,
        "speed": 8,
        "age": 34,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "athletic_bilbao",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 804989,
        "name": "Alex Remiro",
        "position": "Kaleci",
        "power": 79,
        "speed": 9,
        "age": 28,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 269973,
        "name": "Igor Zubeldia",
        "position": "Stoper",
        "power": 76,
        "speed": 5,
        "age": 29,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "maestro",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 421454,
        "name": "Jon Pacheco",
        "position": "Stoper",
        "power": 76,
        "speed": 5,
        "age": 22,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 882825,
        "name": "Hamari Traore",
        "position": "Sağ Bek",
        "power": 77,
        "speed": 8,
        "age": 26,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 230837,
        "name": "Javi Lopez",
        "position": "Sol Bek",
        "power": 76,
        "speed": 7,
        "age": 28,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "stopper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 622644,
        "name": "Martin Zubimendi",
        "position": "Ön Libero",
        "power": 82,
        "speed": 7,
        "age": 33,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 336555,
        "name": "Brais Mendez",
        "position": "Merkez Orta Saha",
        "power": 79,
        "speed": 8,
        "age": 30,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "sweeper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 777237,
        "name": "Mikel Oyarzabal",
        "position": "Forvet Arkası",
        "power": 79,
        "speed": 9,
        "age": 22,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 875423,
        "name": "Takefusa Kubo",
        "position": "Sağ Kanat",
        "power": 79,
        "speed": 6,
        "age": 34,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "regista",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 171317,
        "name": "Sheraldo Becker",
        "position": "Sol Kanat",
        "power": 82,
        "speed": 9,
        "age": 27,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 873744,
        "name": "Ander Barrenetxea",
        "position": "Forvet",
        "power": 83,
        "speed": 8,
        "age": 31,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 296268,
        "name": "Luka Sucic",
        "position": "Forvet",
        "power": 78,
        "speed": 8,
        "age": 31,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 590257,
        "name": "Sergio Gomez",
        "position": "Orta Saha",
        "power": 79,
        "speed": 7,
        "age": 34,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 955561,
        "name": "Arsen Zakharyan",
        "position": "Stoper",
        "power": 83,
        "speed": 6,
        "age": 24,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 692685,
        "name": "Umar Sadiq",
        "position": "Sol Bek",
        "power": 83,
        "speed": 9,
        "age": 31,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "real_sociedad",
        "tacticalRole": "stopper",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 589000,
        "name": "Diego Conde",
        "position": "Kaleci",
        "power": 80,
        "speed": 9,
        "age": 30,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "inside_forward",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 546023,
        "name": "Eric Bailly",
        "position": "Stoper",
        "power": 78,
        "speed": 8,
        "age": 26,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "classic",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 431397,
        "name": "Raul Albiol",
        "position": "Stoper",
        "power": 78,
        "speed": 5,
        "age": 29,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "sweeper",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 561745,
        "name": "Kiko Femenia",
        "position": "Sağ Bek",
        "power": 79,
        "speed": 7,
        "age": 22,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "target_man",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 698692,
        "name": "Sergi Cardona",
        "position": "Sol Bek",
        "power": 83,
        "speed": 5,
        "age": 23,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 317448,
        "name": "Dani Parejo",
        "position": "Ön Libero",
        "power": 79,
        "speed": 6,
        "age": 24,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 185889,
        "name": "Santi Comesana",
        "position": "Merkez Orta Saha",
        "power": 78,
        "speed": 8,
        "age": 28,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 267481,
        "name": "Alex Baena",
        "position": "Forvet Arkası",
        "power": 79,
        "speed": 6,
        "age": 31,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 980949,
        "name": "Yeremy Pino",
        "position": "Sağ Kanat",
        "power": 80,
        "speed": 9,
        "age": 29,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 778532,
        "name": "Gerard Moreno",
        "position": "Sol Kanat",
        "power": 76,
        "speed": 9,
        "age": 32,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "sweeper",
        "mentalTrait": "aggressive",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 497448,
        "name": "Ayoze Perez",
        "position": "Forvet",
        "power": 82,
        "speed": 7,
        "age": 21,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 178248,
        "name": "Nicolas Pepe",
        "position": "Forvet",
        "power": 76,
        "speed": 8,
        "age": 30,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 354500,
        "name": "Juan Foyth",
        "position": "Orta Saha",
        "power": 82,
        "speed": 5,
        "age": 26,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "poacher",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 240889,
        "name": "Thierno Barry",
        "position": "Stoper",
        "power": 82,
        "speed": 7,
        "age": 33,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "maestro",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 748112,
        "name": "Ilias Akhomach",
        "position": "Sol Bek",
        "power": 79,
        "speed": 6,
        "age": 22,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "villarreal",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 344541,
        "name": "Rui Silva",
        "position": "Kaleci",
        "power": 77,
        "speed": 6,
        "age": 33,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "box_to_box",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 676856,
        "name": "Marc Bartra",
        "position": "Stoper",
        "power": 76,
        "speed": 5,
        "age": 34,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "classic",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 986920,
        "name": "Diego Llorente",
        "position": "Stoper",
        "power": 79,
        "speed": 6,
        "age": 23,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "playmaker",
        "mentalTrait": "classic",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 554622,
        "name": "Hector Bellerin",
        "position": "Sağ Bek",
        "power": 81,
        "speed": 9,
        "age": 31,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 706496,
        "name": "Ricardo Rodriguez",
        "position": "Sol Bek",
        "power": 77,
        "speed": 5,
        "age": 31,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 180432,
        "name": "Johnny Cardoso",
        "position": "Ön Libero",
        "power": 82,
        "speed": 8,
        "age": 24,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 629865,
        "name": "Marc Roca",
        "position": "Merkez Orta Saha",
        "power": 82,
        "speed": 9,
        "age": 26,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "box_to_box",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 206579,
        "name": "Isco",
        "position": "Forvet Arkası",
        "power": 78,
        "speed": 9,
        "age": 22,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "false_9",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 502805,
        "name": "Nabil Fekir",
        "position": "Sağ Kanat",
        "power": 82,
        "speed": 5,
        "age": 21,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "inside_forward",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 862968,
        "name": "Pablo Fornals",
        "position": "Sol Kanat",
        "power": 82,
        "speed": 6,
        "age": 33,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "poacher",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 572924,
        "name": "Abde Ezzalzouli",
        "position": "Forvet",
        "power": 76,
        "speed": 7,
        "age": 33,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 678710,
        "name": "Vitor Roque",
        "position": "Forvet",
        "power": 78,
        "speed": 6,
        "age": 25,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "classic",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 802375,
        "name": "William Carvalho",
        "position": "Orta Saha",
        "power": 83,
        "speed": 8,
        "age": 21,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "inside_forward",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 852161,
        "name": "Giovani Lo Celso",
        "position": "Stoper",
        "power": 83,
        "speed": 8,
        "age": 21,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "playmaker",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 164097,
        "name": "Chimy Avila",
        "position": "Sol Bek",
        "power": 82,
        "speed": 6,
        "age": 34,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "real_betis",
        "tacticalRole": "target_man",
        "mentalTrait": "fragile",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 906798,
        "name": "Orjan Nyland",
        "position": "Kaleci",
        "power": 80,
        "speed": 7,
        "age": 21,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 454464,
        "name": "Loic Bade",
        "position": "Stoper",
        "power": 78,
        "speed": 9,
        "age": 21,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 494661,
        "name": "Nemanja Gudelj",
        "position": "Stoper",
        "power": 83,
        "speed": 9,
        "age": 23,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "maestro",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 350529,
        "name": "Jesus Navas",
        "position": "Sağ Bek",
        "power": 77,
        "speed": 6,
        "age": 22,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "sweeper",
        "mentalTrait": "classic",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 284126,
        "name": "Adria Pedrosa",
        "position": "Sol Bek",
        "power": 78,
        "speed": 9,
        "age": 25,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 684088,
        "name": "Djibril Sow",
        "position": "Ön Libero",
        "power": 79,
        "speed": 5,
        "age": 28,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 361152,
        "name": "Albert Sambi Lokonga",
        "position": "Merkez Orta Saha",
        "power": 83,
        "speed": 6,
        "age": 25,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "anchor",
        "mentalTrait": "fragile",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 952372,
        "name": "Saul Niguez",
        "position": "Forvet Arkası",
        "power": 81,
        "speed": 9,
        "age": 27,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "anchor",
        "mentalTrait": "elite",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 519930,
        "name": "Lucas Ocampos",
        "position": "Sağ Kanat",
        "power": 77,
        "speed": 5,
        "age": 28,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "stopper",
        "mentalTrait": "aggressive",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 816021,
        "name": "Isaac Romero",
        "position": "Sol Kanat",
        "power": 78,
        "speed": 5,
        "age": 21,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "box_to_box",
        "mentalTrait": "classic",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 498529,
        "name": "Kelechi Iheanacho",
        "position": "Forvet",
        "power": 77,
        "speed": 9,
        "age": 25,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "poacher",
        "mentalTrait": "classic",
        "contractYears": 3,
        "isListed": false
    },
    {
        "id": 368740,
        "name": "Dodi Lukebakio",
        "position": "Forvet",
        "power": 76,
        "speed": 9,
        "age": 28,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "playmaker",
        "mentalTrait": "fragile",
        "contractYears": 4,
        "isListed": false
    },
    {
        "id": 631713,
        "name": "Suso",
        "position": "Orta Saha",
        "power": 78,
        "speed": 8,
        "age": 25,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "maestro",
        "mentalTrait": "elite",
        "contractYears": 2,
        "isListed": false
    },
    {
        "id": 748850,
        "name": "Kike Salas",
        "position": "Stoper",
        "power": 80,
        "speed": 9,
        "age": 29,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "stopper",
        "mentalTrait": "elite",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 586888,
        "name": "Chidera Ejuke",
        "position": "Sol Bek",
        "power": 79,
        "speed": 6,
        "age": 22,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "sevilla",
        "tacticalRole": "anchor",
        "mentalTrait": "aggressive",
        "contractYears": 1,
        "isListed": false
    },
    {
        "id": 290938,
        "name": "Thibaut Courtois",
        "position": "Kaleci",
        "age": 36,
        "power": 66,
        "speed": 4.8,
        "mentalTrait": "classic",
        "tacticalRole": "sweeper_keeper",
        "price": 4,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 391414,
        "name": "Andriy Lunin",
        "position": "Kaleci",
        "age": 29,
        "power": 64.5,
        "speed": 4.8,
        "mentalTrait": "classic",
        "tacticalRole": "sweeper_keeper",
        "price": 3,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 544040,
        "name": "Fran González",
        "position": "Kaleci",
        "age": 23,
        "power": 61.5,
        "speed": 4.1,
        "mentalTrait": "fragile",
        "tacticalRole": "sweeper_keeper",
        "price": 1,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 600018,
        "name": "Dean Huijsen",
        "position": "Stoper",
        "age": 23,
        "power": 85.5,
        "speed": 3.6,
        "mentalTrait": "elite",
        "tacticalRole": "stopper",
        "price": 17,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 585540,
        "name": "Éder Militão",
        "position": "Stoper",
        "age": 30,
        "power": 69,
        "speed": 4.3,
        "mentalTrait": "classic",
        "tacticalRole": "stopper",
        "price": 6,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 715070,
        "name": "Raúl Asencio",
        "position": "Stoper",
        "age": 25,
        "power": 69,
        "speed": 4.1,
        "mentalTrait": "classic",
        "tacticalRole": "stopper",
        "price": 6,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 562797,
        "name": "Antonio Rüdiger",
        "position": "Stoper",
        "age": 35,
        "power": 63,
        "speed": 4.7,
        "mentalTrait": "fragile",
        "tacticalRole": "stopper",
        "price": 2,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 126863,
        "name": "David Alaba",
        "position": "Stoper",
        "age": 36,
        "power": 61.5,
        "speed": 4.7,
        "mentalTrait": "fragile",
        "tacticalRole": "stopper",
        "price": 1,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 472139,
        "name": "Álvaro Carreras",
        "position": "Sol Bek",
        "age": 25,
        "power": 81,
        "speed": 3.5,
        "mentalTrait": "elite",
        "tacticalRole": "wing_back",
        "price": 14,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 128489,
        "name": "Fran García",
        "position": "Sol Bek",
        "age": 28,
        "power": 64.5,
        "speed": 3.7,
        "mentalTrait": "classic",
        "tacticalRole": "wing_back",
        "price": 3,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 562804,
        "name": "Ferland Mendy",
        "position": "Sol Bek",
        "age": 33,
        "power": 61.5,
        "speed": 3.8,
        "mentalTrait": "fragile",
        "tacticalRole": "wing_back",
        "price": 1,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 628702,
        "name": "Trent Alexander-Arnold",
        "position": "Sağ Bek",
        "age": 29,
        "power": 85.5,
        "speed": 4.5,
        "mentalTrait": "elite",
        "tacticalRole": "wing_back",
        "price": 17,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 421055,
        "name": "Daniel Carvajal",
        "position": "Sağ Bek",
        "age": 36,
        "power": 61.5,
        "speed": 4.7,
        "mentalTrait": "fragile",
        "tacticalRole": "wing_back",
        "price": 1,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 687934,
        "name": "Aurélien Tchouaméni",
        "position": "Ön Libero",
        "age": 28,
        "power": 90,
        "speed": 3.9,
        "mentalTrait": "elite",
        "tacticalRole": "box_to_box",
        "price": 20,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 370150,
        "name": "Federico Valverde",
        "position": "Merkez Orta Saha",
        "age": 29,
        "power": 99,
        "speed": 4.3,
        "mentalTrait": "elite",
        "tacticalRole": "box_to_box",
        "price": 26,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 681825,
        "name": "Eduardo Camavinga",
        "position": "Merkez Orta Saha",
        "age": 25,
        "power": 81,
        "speed": 4.7,
        "mentalTrait": "elite",
        "tacticalRole": "box_to_box",
        "price": 14,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 767524,
        "name": "Thiago Pitarch",
        "position": "Merkez Orta Saha",
        "age": 20,
        "power": 69,
        "speed": 4.4,
        "mentalTrait": "classic",
        "tacticalRole": "box_to_box",
        "price": 6,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 826162,
        "name": "Jorge Cestero",
        "position": "Merkez Orta Saha",
        "age": 22,
        "power": 63,
        "speed": 3.9,
        "mentalTrait": "fragile",
        "tacticalRole": "box_to_box",
        "price": 2,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 770991,
        "name": "Dani Ceballos",
        "position": "Merkez Orta Saha",
        "age": 31,
        "power": 63,
        "speed": 4.1,
        "mentalTrait": "fragile",
        "tacticalRole": "box_to_box",
        "price": 2,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 866768,
        "name": "Manuel Ángel",
        "position": "Merkez Orta Saha",
        "age": 24,
        "power": 61.5,
        "speed": 4.4,
        "mentalTrait": "fragile",
        "tacticalRole": "box_to_box",
        "price": 1,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 524928,
        "name": "Jude Bellingham",
        "position": "Orta Saha",
        "age": 23,
        "power": 99,
        "speed": 4,
        "mentalTrait": "elite",
        "tacticalRole": "playmaker",
        "price": 37,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 716400,
        "name": "Arda Güler",
        "position": "Maestro",
        "age": 21,
        "power": 99,
        "speed": 3.5,
        "mentalTrait": "elite",
        "tacticalRole": "playmaker",
        "price": 26,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 619579,
        "name": "César Palacios",
        "position": "On Numara",
        "age": 23,
        "power": 63,
        "speed": 4.6,
        "mentalTrait": "fragile",
        "tacticalRole": "playmaker",
        "price": 2,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 159868,
        "name": "Vinicius Junior",
        "position": "Sol Kanat",
        "age": 27,
        "power": 99,
        "speed": 3.9,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 40,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 840454,
        "name": "Rodrygo",
        "position": "Sağ Kanat",
        "age": 27,
        "power": 79.5,
        "speed": 4.4,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 13,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 423459,
        "name": "Franco Mastantuono",
        "position": "Sağ Kanat",
        "age": 20,
        "power": 79.5,
        "speed": 4,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 13,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 729686,
        "name": "Brahim Díaz",
        "position": "Sağ Kanat",
        "age": 28,
        "power": 75,
        "speed": 3.6,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 10,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 419110,
        "name": "Kylian Mbappé",
        "position": "Santrfor",
        "age": 28,
        "power": 99,
        "speed": 4.8,
        "mentalTrait": "elite",
        "tacticalRole": "poacher",
        "price": 51,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 539871,
        "name": "Gonzalo García",
        "position": "Santrafor",
        "age": 24,
        "power": 73.5,
        "speed": 4.6,
        "mentalTrait": "elite",
        "tacticalRole": "poacher",
        "price": 9,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "real_madrid"
    },
    {
        "id": 431410,
        "name": "Joan García",
        "position": "Kaleci",
        "age": 27,
        "power": 79.5,
        "speed": 4.1,
        "mentalTrait": "elite",
        "tacticalRole": "sweeper_keeper",
        "price": 13,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 775523,
        "name": "Diego Kochen",
        "position": "Kaleci",
        "age": 22,
        "power": 60,
        "speed": 3.5,
        "mentalTrait": "fragile",
        "tacticalRole": "sweeper_keeper",
        "price": 1,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 233177,
        "name": "Wojciech Szczesny",
        "position": "Kaleci",
        "age": 38,
        "power": 61.5,
        "speed": 4.2,
        "mentalTrait": "fragile",
        "tacticalRole": "sweeper_keeper",
        "price": 1,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 494755,
        "name": "Pau Cubarsí",
        "position": "Stoper",
        "age": 21,
        "power": 94.5,
        "speed": 3.5,
        "mentalTrait": "elite",
        "tacticalRole": "stopper",
        "price": 23,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 502367,
        "name": "Eric García",
        "position": "Stoper",
        "age": 27,
        "power": 76.5,
        "speed": 3.5,
        "mentalTrait": "elite",
        "tacticalRole": "stopper",
        "price": 11,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 162031,
        "name": "Gerard Martín",
        "position": "Stoper",
        "age": 26,
        "power": 75,
        "speed": 5,
        "mentalTrait": "elite",
        "tacticalRole": "stopper",
        "price": 10,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 535580,
        "name": "Ronald Araujo",
        "position": "Stoper",
        "age": 29,
        "power": 69,
        "speed": 4.6,
        "mentalTrait": "classic",
        "tacticalRole": "stopper",
        "price": 6,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 660787,
        "name": "Andreas Christensen",
        "position": "Stoper",
        "age": 32,
        "power": 63,
        "speed": 3.9,
        "mentalTrait": "fragile",
        "tacticalRole": "stopper",
        "price": 2,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 495214,
        "name": "Alejandro Balde",
        "position": "Sol Bek",
        "age": 24,
        "power": 81,
        "speed": 4.7,
        "mentalTrait": "elite",
        "tacticalRole": "wing_back",
        "price": 14,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 902786,
        "name": "Jules Koundé",
        "position": "Sağ Bek",
        "age": 29,
        "power": 85.5,
        "speed": 4.6,
        "mentalTrait": "elite",
        "tacticalRole": "wing_back",
        "price": 17,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 978901,
        "name": "João Cancelo",
        "position": "Sağ Bek",
        "age": 34,
        "power": 63,
        "speed": 5,
        "mentalTrait": "fragile",
        "tacticalRole": "wing_back",
        "price": 2,
        birthplace: "Alicante, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 638369,
        "name": "Marc Bernal",
        "position": "Ön Libero",
        "age": 21,
        "power": 73.5,
        "speed": 4.9,
        "mentalTrait": "elite",
        "tacticalRole": "box_to_box",
        "price": 9,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 162647,
        "name": "Marc Casadó",
        "position": "Ön Libero",
        "age": 24,
        "power": 67.5,
        "speed": 4.8,
        "mentalTrait": "classic",
        "tacticalRole": "box_to_box",
        "price": 5,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 918588,
        "name": "Pedri",
        "position": "Merkez Orta Saha",
        "age": 25,
        "power": 99,
        "speed": 4.2,
        "mentalTrait": "elite",
        "tacticalRole": "box_to_box",
        "price": 43,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 586616,
        "name": "Frenkie de Jong",
        "position": "Merkez Orta Saha",
        "age": 31,
        "power": 75,
        "speed": 4.6,
        "mentalTrait": "elite",
        "tacticalRole": "box_to_box",
        "price": 10,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 792328,
        "name": "Gavi",
        "position": "Merkez Orta Saha",
        "age": 23,
        "power": 73.5,
        "speed": 3.9,
        "mentalTrait": "elite",
        "tacticalRole": "box_to_box",
        "price": 9,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 239295,
        "name": "Fermín López",
        "position": "On Numara",
        "age": 25,
        "power": 99,
        "speed": 4.1,
        "mentalTrait": "elite",
        "tacticalRole": "playmaker",
        "price": 29,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 200053,
        "name": "Dani Olmo II",
        "position": "On Numara",
        "age": 30,
        "power": 85.5,
        "speed": 3.6,
        "mentalTrait": "elite",
        "tacticalRole": "playmaker",
        "price": 17,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 719489,
        "name": "Raphinha",
        "position": "Sol Kanat",
        "age": 31,
        "power": 90,
        "speed": 4.1,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 20,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 238921,
        "name": "Marcus Rashford",
        "position": "Sol Kanat",
        "age": 30,
        "power": 76.5,
        "speed": 3.6,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 11,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 363811,
        "name": "Lamine Yamal",
        "position": "Sağ Kanat",
        "age": 19,
        "power": 99,
        "speed": 4.5,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 57,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 435202,
        "name": "Roony Bardghji",
        "position": "Sağ Kanat",
        "age": 22,
        "power": 66,
        "speed": 4.3,
        "mentalTrait": "classic",
        "tacticalRole": "winger",
        "price": 4,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 107945,
        "name": "Ferran Torres",
        "position": "Santrafor",
        "age": 28,
        "power": 81,
        "speed": 4.1,
        "mentalTrait": "elite",
        "tacticalRole": "poacher",
        "price": 14,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 560269,
        "name": "Robert Lewandowski",
        "position": "Santrafor",
        "age": 39,
        "power": 63,
        "speed": 4.3,
        "mentalTrait": "fragile",
        "tacticalRole": "poacher",
        "price": 2,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "barcelona"
    },
    {
        "id": 812147,
        "name": "Jan Oblak",
        "position": "Kaleci",
        "age": 35,
        "power": 66,
        "speed": 3.5,
        "mentalTrait": "classic",
        "tacticalRole": "sweeper_keeper",
        "price": 4,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 689027,
        "name": "Juan Musso",
        "position": "Kaleci",
        "age": 34,
        "power": 61.5,
        "speed": 3.6,
        "mentalTrait": "fragile",
        "tacticalRole": "sweeper_keeper",
        "price": 1,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 205961,
        "name": "Dávid Hancko",
        "position": "Stoper",
        "age": 30,
        "power": 75,
        "speed": 4.3,
        "mentalTrait": "elite",
        "tacticalRole": "stopper",
        "price": 10,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 470556,
        "name": "Marc Pubill",
        "position": "Stoper",
        "age": 25,
        "power": 75,
        "speed": 3.8,
        "mentalTrait": "elite",
        "tacticalRole": "stopper",
        "price": 10,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 992169,
        "name": "Robin Le Normand",
        "position": "Stoper",
        "age": 31,
        "power": 69,
        "speed": 4.3,
        "mentalTrait": "classic",
        "tacticalRole": "stopper",
        "price": 6,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 393648,
        "name": "José María Giménez",
        "position": "Stoper",
        "age": 33,
        "power": 64.5,
        "speed": 4.4,
        "mentalTrait": "classic",
        "tacticalRole": "stopper",
        "price": 3,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 210870,
        "name": "Clément Lenglet",
        "position": "Stoper",
        "age": 33,
        "power": 61.5,
        "speed": 4,
        "mentalTrait": "fragile",
        "tacticalRole": "stopper",
        "price": 1,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 466166,
        "name": "Matteo Ruggeri",
        "position": "Sol Bek",
        "age": 25,
        "power": 72,
        "speed": 4.5,
        "mentalTrait": "elite",
        "tacticalRole": "wing_back",
        "price": 8,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 448282,
        "name": "Marcos Llorente",
        "position": "Sağ Bek",
        "age": 33,
        "power": 69,
        "speed": 3.8,
        "mentalTrait": "classic",
        "tacticalRole": "wing_back",
        "price": 6,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 920708,
        "name": "Nahuel Molina",
        "position": "Sağ Bek",
        "age": 30,
        "power": 66,
        "speed": 4.3,
        "mentalTrait": "classic",
        "tacticalRole": "wing_back",
        "price": 4,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 928528,
        "name": "Pablo Barrios",
        "position": "Merkez Orta Saha",
        "age": 25,
        "power": 84,
        "speed": 4.6,
        "mentalTrait": "elite",
        "tacticalRole": "box_to_box",
        "price": 16,
        birthplace: "Barcelona, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 728294,
        "name": "Rodrigo Mendoza",
        "position": "Merkez Orta Saha",
        "age": 23,
        "power": 69,
        "speed": 4.8,
        "mentalTrait": "classic",
        "tacticalRole": "box_to_box",
        "price": 6,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 630179,
        "name": "Johnny Cardoso II",
        "position": "Merkez Orta Saha",
        "age": 26,
        "power": 69,
        "speed": 4.2,
        "mentalTrait": "classic",
        "tacticalRole": "box_to_box",
        "price": 6,
        birthplace: "Seville, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 758355,
        "name": "Obed Vargas",
        "position": "Merkez Orta Saha",
        "age": 22,
        "power": 64.5,
        "speed": 3.7,
        "mentalTrait": "classic",
        "tacticalRole": "box_to_box",
        "price": 3,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 573555,
        "name": "Koke",
        "position": "Merkez Orta Saha",
        "age": 36,
        "power": 61.5,
        "speed": 4.3,
        "mentalTrait": "fragile",
        "tacticalRole": "box_to_box",
        "price": 1,
        birthplace: "Bilbao, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 659052,
        "name": "Álex Baena",
        "position": "Sol Kanat",
        "age": 26,
        "power": 76.5,
        "speed": 3.7,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 11,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 299598,
        "name": "Ademola Lookman",
        "position": "Sol Kanat",
        "age": 30,
        "power": 76.5,
        "speed": 4.4,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 11,
        birthplace: "Valencia, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 769915,
        "name": "Nico González",
        "position": "Sol Kanat",
        "age": 30,
        "power": 69,
        "speed": 4.9,
        "mentalTrait": "classic",
        "tacticalRole": "winger",
        "price": 6,
        birthplace: "Zaragoza, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 784564,
        "name": "Thiago Almada",
        "position": "Sol Kanat",
        "age": 27,
        "power": 66,
        "speed": 4.8,
        "mentalTrait": "classic",
        "tacticalRole": "winger",
        "price": 4,
        birthplace: "Malaga, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 319574,
        "name": "Giuliano Simeone",
        "position": "Sağ Kanat",
        "age": 25,
        "power": 76.5,
        "speed": 3.8,
        "mentalTrait": "elite",
        "tacticalRole": "winger",
        "price": 11,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 994931,
        "name": "Antoine Griezmann",
        "position": "Forvet Arkası",
        "age": 37,
        "power": 63,
        "speed": 4,
        "mentalTrait": "fragile",
        "tacticalRole": "poacher",
        "price": 2,
        birthplace: "Palma, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 702418,
        "name": "Julián Alvarez",
        "position": "Santrafor",
        "age": 28,
        "power": 99,
        "speed": 3.7,
        "mentalTrait": "elite",
        "tacticalRole": "poacher",
        "price": 29,
        birthplace: "Madrid, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    },
    {
        "id": 597198,
        "name": "Alexander Sørloth",
        "position": "Santrafor",
        "age": 32,
        "power": 67.5,
        "speed": 4,
        "mentalTrait": "classic",
        "tacticalRole": "poacher",
        "price": 5,
        birthplace: "Murcia, Ispanya", nationality: "Ispanya", "teamId": "atletico_madrid"
    }
];
laligaPlayers.forEach(p => window.leagueData.players.push(p));

