// js/data_world_stars.js

const worldStarsRaw = [
    {"name":"Enzo Fernández","position":"Merkez Orta Saha","age":25,birthplace: "Buenos Aires, Arjantin", "teamId":"chelsea","value":90,"role":"maestro","trait":"elite"},
    {"name":"Rayan Cherki","position":"10 Numara","age":22,birthplace: "Lyon, Fransa", "teamId":"mancity","value":90,"role":"playmaker","trait":"playmaker"},
    {"name":"Morgan Rogers","position":"10 Numara","age":23,birthplace: "Halesowen, Ingiltere", "teamId":"astonvilla","value":90,"role":"playmaker","trait":"aggressive"},
    {"name":"Federico Valverde","position":"Merkez Orta Saha","age":27,birthplace: "Montevideo, Uruguay", "teamId":"real_madrid","value":90,"role":"box_to_box","trait":"elite"},
    {"name":"Lautaro Martínez","position":"Santrafor","age":28,birthplace: "Prag, �ekya", "teamId":"inter","value":85,"role":"poacher","trait":"elite"},
    {"name":"Alexander Isak","position":"Santrafor","age":26,birthplace: "Solna, 0sve�", "teamId":"liverpool","value":85,"role":"poacher","trait":"aggressive"},
    {"name":"Estêvão","position":"Sağ Açık","age":19,birthplace: "Lizbon, Portekiz", "teamId":"chelsea","value":80,"role":"winger","trait":"elite"},
    {"name":"Pau Cubarsí","position":"Stoper","age":19,birthplace: "Zagreb, Hirvatistan", "teamId":"barcelona","value":80,"role":"playmaker","trait":"elite"},
    {"name":"Nico Paz","position":"10 Numara","age":21,birthplace: "Tenerife, Ispanya", "teamId":"como","value":80,"role":"maestro","trait":"playmaker"},
    {"name":"Warren Zaïre-Emery","position":"Merkez Orta Saha","age":20,birthplace: "Zagreb, Hirvatistan", "teamId":"psg","value":80,"role":"box_to_box","trait":"elite"},
    {"name":"Hugo Ekitiké","position":"Santrafor","age":24,birthplace: "Roma, Italya", "teamId":"liverpool","value":80,"role":"target_man","trait":"playmaker"},
    {"name":"Willian Pacho","position":"Stoper","age":24,birthplace: "Quinind�, Ekvador", "teamId":"psg","value":80,"role":"stopper","trait":"aggressive"},
    {"name":"João Pedro","position":"Santrafor","age":24,birthplace: "Ribeir�o Preto, Brezilya", "teamId":"chelsea","value":80,"role":"poacher","trait":"elite"},
    {"name":"Willian Pacho","position":"Stoper","age":24,birthplace: "Quinind, Ekvador", "teamId":"psg","value":80,"role":"stopper","trait":"aggressive"},
    {"name":"João Pedro","position":"Santrafor","age":24,birthplace: "Ribeiro Preto, Brezilya", "teamId":"chelsea","value":80,"role":"poacher","trait":"elite"},
    {"name":"Nuno Mendes","position":"Sol Bek","age":24,birthplace: "Sintra, Portekiz", "teamId":"psg","value":80,"role":"wing_back","trait":"aggressive"},
    {"name":"Antoine Semenyo","position":"Sağ Açık","age":26,birthplace: "Londra, Ingiltere", "teamId":"bournemouth","value":80,"role":"inside_forward","trait":"aggressive"},
    {"name":"Ryan Gravenberch","position":"Ön Libero","age":24,birthplace: "Amsterdam, Hollanda", "teamId":"liverpool","value":80,"role":"anchor","trait":"playmaker"},
    {"name":"Achraf Hakimi","position":"Sağ Bek","age":27,birthplace: "Madrid, Ispanya", "teamId":"psg","value":80,"role":"wing_back","trait":"elite"},
    {"name":"Sandro Tonali","position":"Ön Libero","age":26,birthplace: "Lodi, Italya", "teamId":"newcastle","value":80,"role":"anchor","trait":"aggressive"},
    {"name":"Kenan Yıldız","position":"Sol Açık","age":21,birthplace: "Kopenhag, Danimarka", "teamId":"juventus","value":75,"role":"inside_forward","trait":"elite"},
    {"name":"Benjamin Sesko","position":"Santrafor","age":23,birthplace: "Radece, Slovenya", "teamId":"manutd","value":75,"role":"target_man","trait":"aggressive"},
    {"name":"Elliot Anderson","position":"Merkez Orta Saha","age":23,birthplace: "Whitley Bay, Ingiltere", "teamId":"nforest","value":75,"role":"box_to_box","trait":"playmaker"},
    {"name":"Matheus Cunha","position":"Santrafor","age":27,birthplace: "Joo Pessoa, Brezilya", "teamId":"manutd","value":75,"role":"poacher","trait":"aggressive"},
    {"name":"Jérémy Doku","position":"Sol Açık","age":24,birthplace: "Zagreb, Hirvatistan", "teamId":"mancity","value":75,"role":"winger","trait":"aggressive"},
    {"name":"Gabriel","position":"Stoper","age":28,birthplace: "So Paulo, Brezilya", "teamId":"arsenal","value":75,"role":"stopper","trait":"aggressive"},
    {"name":"Martín Zubimendi","position":"Ön Libero","age":27,birthplace: "Kopenhag, Danimarka", "teamId":"arsenal","value":75,"role":"anchor","trait":"playmaker"},
    { name: "Lamine Yamal", position: "Sağ Açık", age: 18, birthplace: "Esplugues de Llobregat, Ispanya", teamId: "barcelona", value: 200, role: "inside_forward", trait: "elite" },
    { name: "Erling Haaland", position: "Santrafor", age: 25, birthplace: "Leeds, Ingiltere", teamId: "mancity", value: 200, role: "poacher", trait: "elite" },
    { name: "Kylian Mbappé", position: "Santrafor", age: 27, birthplace: "Roma, Italya", teamId: "realmadrid", value: 180, role: "poacher", trait: "elite" },
    { name: "Pedri", position: "Merkez Orta Saha", age: 23, birthplace: "Tegueste, Ispanya", teamId: "barcelona", value: 150, role: "playmaker", trait: "elite" },
    { name: "Michael Olise", position: "Sağ Açık", age: 24, birthplace: "Prag, �ekya", teamId: "bayern", value: 150, role: "inside_forward", trait: "elite" },
    { name: "João Neves", position: "Merkez Orta Saha", age: 21, birthplace: "Prag, �ekya", teamId: "psg", value: 140, role: "maestro", trait: "elite" },
    { name: "Khvicha Kvaratskhelia", position: "Sol Açık", age: 25, birthplace: "Br�ksel, Bel�ika", teamId: "psg", value: 140, role: "inside_forward", trait: "elite" },
    { name: "Vitinha", position: "Ön Libero", age: 26, birthplace: "Zagreb, Hirvatistan", teamId: "psg", value: 140, role: "playmaker", trait: "elite" },
    { name: "Vinicius Junior", position: "Sol Açık", age: 25, birthplace: "S�o Gon�alo, Brezilya", teamId: "realmadrid", value: 140, role: "inside_forward", trait: "elite" },
    { name: "Jude Bellingham", position: "10 Numara", age: 22, birthplace: "Stourbridge, Ingiltere", teamId: "realmadrid", value: 130, role: "maestro", trait: "elite" },
    { name: "Désiré Doué", position: "Sağ Açık", age: 21, birthplace: "Lizbon, Portekiz", teamId: "psg", value: 120, role: "winger", trait: "elite" },
    { name: "Declan Rice", position: "Merkez Orta Saha", age: 27, birthplace: "Londra, Ingiltere", teamId: "arsenal", value: 120, role: "anchor", trait: "elite" },
    { name: "Bukayo Saka", position: "Sağ Açık", age: 24, birthplace: "Londra, Ingiltere", teamId: "arsenal", value: 110, role: "inside_forward", trait: "elite" },
    { name: "Moisés Caicedo", position: "Ön Libero", age: 24, birthplace: "Zagreb, Hirvatistan", teamId: "chelsea", value: 100, role: "anchor", trait: "elite" },
    { name: "Fermín López", position: "10 Numara", age: 23, birthplace: "Kopenhag, Danimarka", teamId: "barcelona", value: 100, role: "playmaker", trait: "elite" },
    { name: "Florian Wirtz", position: "10 Numara", age: 23, birthplace: "Pulheim, Almanya", teamId: "liverpool", value: 100, role: "maestro", trait: "elite" },
    { name: "Jamal Musiala", position: "10 Numara", age: 23, birthplace: "Stuttgart, Almanya", teamId: "bayern", value: 100, role: "maestro", trait: "elite" },
    { name: "Julián Alvarez", position: "Santrafor", age: 26, birthplace: "Calch�n, Arjantin", teamId: "atleticomadrid", value: 100, role: "target_man", trait: "elite" },
    { name: "Cole Palmer", position: "10 Numara", age: 24, birthplace: "Manchester, Ingiltere", teamId: "chelsea", value: 100, role: "maestro", trait: "elite" },
    { name: "William Saliba", position: "Stoper", age: 25, birthplace: "Bondy, Fransa", teamId: "arsenal", value: 100, role: "stopper", trait: "elite" },
    { name: "Dominik Szoboszlai", position: "10 Numara", age: 25, birthplace: "Prag, �ekya", teamId: "liverpool", value: 100, role: "playmaker", trait: "elite" },
    { name: "Ousmane Dembélé", position: "Santrafor", age: 29, birthplace: "Zagreb, Hirvatistan", teamId: "psg", value: 100, role: "inside_forward", trait: "elite" },
    { name: "Yan Diomande", position: "Sol Açık", age: 19, birthplace: "Br�ksel, Bel�ika", teamId: "rbleipzig", value: 90, role: "winger", trait: "elite" },
    { name: "Arda Güler", position: "10 Numara", age: 21, birthplace: "Lizbon, Portekiz", teamId: "realmadrid", value: 90, role: "maestro", trait: "elite" },
    { name: "Aleksandar Pavlovic", position: "Ön Libero", age: 22, birthplace: "M�nih, Almanya", teamId: "bayern", value: 90, role: "anchor", trait: "elite" }
,
    {"name":"Lucas Bergvall","position":"Merkez Orta Saha","age":20,birthplace: "Zagreb, Hirvatistan", "teamId":"tottenhamhotspur","value":10,"role":"box_to_box","trait":"elite"},
    {"name":"Marc Pubill","position":"Stoper","age":23,birthplace: "Br�ksel, Bel�ika", "teamId":"atletico_madrid","value":10,"role":"stopper","trait":"elite"},
    {"name":"Ange-Yoan Bonny","position":"Santrafor","age":22,birthplace: "Zagreb, Hirvatistan", "teamId":"intermilan","value":10,"role":"poacher","trait":"elite"},
    {"name":"Dango Ouattara","position":"Sağ Kanat","age":24,birthplace: "Kopenhag, Danimarka", "teamId":"brentford","value":10,"role":"winger","trait":"elite"},
    {"name":"Mika Godts","position":"Sol Kanat","age":21,birthplace: "Kopenhag, Danimarka", "teamId":"ajaxamsterdam","value":10,"role":"winger","trait":"elite"},
    {"name":"Savinho","position":"Sol Kanat","age":22,birthplace: "Lizbon, Portekiz", "teamId":"mancity","value":10,"role":"winger","trait":"elite"},
    {"name":"Milos Kerkez","position":"Sol Bek","age":22,birthplace: "Br�ksel, Bel�ika", "teamId":"liverpool","value":10,"role":"wing_back","trait":"elite"},
    {"name":"Noah Sadiki","position":"Merkez Orta Saha","age":21,birthplace: "Prag, �ekya", "teamId":"sunderlanda","value":10,"role":"box_to_box","trait":"elite"},
    {"name":"Matias Fernandez-Pardo","position":"Santrafor","age":21,birthplace: "Br�ksel, Bel�ika", "teamId":"losclille","value":10,"role":"poacher","trait":"elite"},
    {"name":"Evanilson","position":"Santrafor","age":26,birthplace: "Roma, Italya", "teamId":"abournemouth","value":10,"role":"poacher","trait":"elite"},
    {"name":"Gerard Martín","position":"Stoper","age":24,birthplace: "Prag, �ekya", "teamId":"barcelona","value":10,"role":"stopper","trait":"elite"},
    {"name":"Matías Soulé","position":"Sağ Kanat","age":23,birthplace: "Prag, �ekya", "teamId":"asroma","value":10,"role":"winger","trait":"elite"},
    {"name":"Máximo Perrone","position":"Ön Libero","age":23,birthplace: "Br�ksel, Bel�ika", "teamId":"como","value":10,"role":"box_to_box","trait":"elite"},
    {"name":"Yasin Ayari","position":"Merkez Orta Saha","age":22,birthplace: "Prag, �ekya", "teamId":"brighton&hovealbion","value":10,"role":"box_to_box","trait":"elite"},
    {"name":"Bilal El Khannouss","position":"On Numara","age":22,birthplace: "Br�ksel, Bel�ika", "teamId":"vfbstuttgart","value":10,"role":"box_to_box","trait":"elite"},
    {"name":"Igor Paixão","position":"Sol Kanat","age":25,birthplace: "Br�ksel, Bel�ika", "teamId":"olympiquemarsilya","value":10,"role":"winger","trait":"elite"},
    {"name":"Malo Gusto","position":"Sağ Bek","age":23,birthplace: "Zagreb, Hirvatistan", "teamId":"chelsea","value":10,"role":"wing_back","trait":"elite"},
    {"name":"Maxi Araújo","position":"Sol Bek","age":26,birthplace: "Lizbon, Portekiz", "teamId":"sportinglizbon","value":10,"role":"wing_back","trait":"elite"},
    {"name":"Edmond Tapsoba","position":"Stoper","age":27,birthplace: "Br�ksel, Bel�ika", "teamId":"bayer04leverkusen","value":10,"role":"stopper","trait":"elite"},
    {"name":"Pedro Porro","position":"Sağ Bek","age":26,birthplace: "Kopenhag, Danimarka", "teamId":"tottenhamhotspur","value":10,"role":"wing_back","trait":"elite"},
    {"name":"Fisnik Asllani","position":"Santrafor","age":23,birthplace: "Lizbon, Portekiz", "teamId":"tsg1899hoffenheim","value":10,"role":"poacher","trait":"elite"},
    {"name":"Bremer","position":"Stoper","age":29,birthplace: "Roma, Italya", "teamId":"juventus","value":10,"role":"stopper","trait":"elite"},
    {"name":"Senne Lammens","position":"Kaleci","age":23,birthplace: "Br�ksel, Bel�ika", "teamId":"manutd","value":10,"role":"sweeper_keeper","trait":"elite"},
    {"name":"Jacob Ramsey","position":"Merkez Orta Saha","age":25,birthplace: "Prag, �ekya", "teamId":"newcastleunited","value":10,"role":"box_to_box","trait":"elite"},
    {"name":"Jeremie Frimpong","position":"Sağ Bek","age":25,birthplace: "Lizbon, Portekiz", "teamId":"liverpool","value":10,"role":"wing_back","trait":"elite"}
,
    {"name":"Lamine Yamal","position":"Sağ Açık","age":17,birthplace: "Esplugues de Llobregat, Ispanya", "teamId":"barcelona","value":150,"role":"winger","trait":"playmaker"},
    {"name":"Erling Haaland","position":"Santrafor","age":24,birthplace: "Leeds, Ingiltere", "teamId":"mancity","value":180,"role":"target_man","trait":"aggressive"},
    {"name":"Phil Foden","position":"10 Numara","age":24,birthplace: "Stockport, Ingiltere", "teamId":"mancity","value":130,"role":"inside_forward","trait":"playmaker"},
    {"name":"Rodri","position":"Ön Libero","age":28,birthplace: "Madrid, Ispanya", "teamId":"mancity","value":110,"role":"anchor","trait":"maestro"},
    {"name":"Aurelien Tchouameni","position":"Ön Libero","age":24,birthplace: "Roma, Italya", "teamId":"realmadrid","value":100,"role":"anchor","trait":"stopper"},
    {"name":"Eduardo Camavinga","position":"Merkez Orta Saha","age":21,birthplace: "Kopenhag, Danimarka", "teamId":"realmadrid","value":100,"role":"box_to_box","trait":"elite"},
    {"name":"Rafael Leão","position":"Sol Açık","age":25,birthplace: "Almada, Portekiz", "teamId":"milan","value":90,"role":"winger","trait":"aggressive"},
    {"name":"Victor Osimhen","position":"Santrafor","age":25,birthplace: "Lagos, Nijerya", "teamId":"napoli","value":110,"role":"poacher","trait":"aggressive"},
    {"name":"Gavi","position":"Merkez Orta Saha","age":20,birthplace: "Los Palacios y Villafranca, Ispanya", "teamId":"barcelona","value":90,"role":"box_to_box","trait":"aggressive"},
    {"name":"Ronald Araujo","position":"Stoper","age":25,birthplace: "Zagreb, Hirvatistan", "teamId":"barcelona","value":75,"role":"stopper","trait":"aggressive"},
    {"name":"Trent Alexander-Arnold","position":"Sağ Bek","age":26,birthplace: "Prag, �ekya", "teamId":"liverpool","value":70,"role":"wing_back","trait":"playmaker"},
    {"name":"Bruno Guimarães","position":"Ön Libero","age":26,birthplace: "Br�ksel, Bel�ika", "teamId":"newcastle","value":85,"role":"playmaker","trait":"aggressive"},
    {"name":"Alexander Isak","position":"Santrafor","age":25,birthplace: "Solna, 0sve�", "teamId":"newcastle","value":75,"role":"poacher","trait":"elite"},
    {"name":"Sven Botman","position":"Stoper","age":24,birthplace: "Roma, Italya", "teamId":"newcastle","value":45,"role":"stopper","trait":"stopper"},
    {"name":"Marcus Rashford","position":"Sol Açık","age":26,birthplace: "Roma, Italya", "teamId":"manutd","value":60,"role":"inside_forward","trait":"winger"},
    {"name":"Bruno Fernandes","position":"10 Numara","age":30,birthplace: "Kopenhag, Danimarka", "teamId":"manutd","value":70,"role":"playmaker","trait":"maestro"},
    {"name":"Lisandro Martinez","position":"Stoper","age":26,birthplace: "Kopenhag, Danimarka", "teamId":"manutd","value":45,"role":"stopper","trait":"aggressive"},
    {"name":"Martin Odegaard","position":"10 Numara","age":25,birthplace: "Drammen, Norve�", "teamId":"arsenal","value":110,"role":"maestro","trait":"playmaker"},
    {"name":"Gabriel Martinelli","position":"Sol Açık","age":23,birthplace: "S�o Paulo, Brezilya", "teamId":"arsenal","value":80,"role":"winger","trait":"aggressive"},
    {"name":"Gabriel Magalhaes","position":"Stoper","age":26,birthplace: "S�o Paulo, Brezilya", "teamId":"arsenal","value":65,"role":"stopper","trait":"stopper"},
    {"name":"Bernardo Silva","position":"Merkez Orta Saha","age":30,birthplace: "Br�ksel, Bel�ika", "teamId":"mancity","value":70,"role":"playmaker","trait":"maestro"},
    {"name":"Ruben Dias","position":"Stoper","age":27,birthplace: "Roma, Italya", "teamId":"mancity","value":80,"role":"stopper","trait":"elite"},
    {"name":"Kevin De Bruyne","position":"10 Numara","age":33,birthplace: "Drongen, Bel�ika", "teamId":"mancity","value":60,"role":"maestro","trait":"playmaker"},
    {"name":"Luis Diaz","position":"Sol Açık","age":27,birthplace: "Prag, �ekya", "teamId":"liverpool","value":75,"role":"winger","trait":"aggressive"},
    {"name":"Alexis Mac Allister","position":"Merkez Orta Saha","age":25,birthplace: "Zagreb, Hirvatistan", "teamId":"liverpool","value":75,"role":"playmaker","trait":"elite"},
    {"name":"Virgil van Dijk","position":"Stoper","age":33,birthplace: "Zagreb, Hirvatistan", "teamId":"liverpool","value":30,"role":"stopper","trait":"leader"},
    {"name":"Alisson","position":"Kaleci","age":32,birthplace: "Kopenhag, Danimarka", "teamId":"liverpool","value":30,"role":"sweeper_keeper","trait":"elite"},
    {"name":"Ederson","position":"Kaleci","age":31,birthplace: "Br�ksel, Bel�ika", "teamId":"mancity","value":40,"role":"sweeper_keeper","trait":"elite"},
    {"name":"Thibaut Courtois","position":"Kaleci","age":32,birthplace: "Zagreb, Hirvatistan", "teamId":"realmadrid","value":30,"role":"sweeper_keeper","trait":"elite"},
    {"name":"Jan Oblak","position":"Kaleci","age":31,birthplace: "Lizbon, Portekiz", "teamId":"atleticomadrid","value":30,"role":"sweeper_keeper","trait":"elite"},
    {"name":"Mike Maignan","position":"Kaleci","age":29,birthplace: "Prag, �ekya", "teamId":"milan","value":40,"role":"sweeper_keeper","trait":"elite"},
    {"name":"Alessandro Bastoni","position":"Stoper","age":25,birthplace: "Zagreb, Hirvatistan", "teamId":"inter","value":70,"role":"stopper","trait":"playmaker"},
    {"name":"Nicolo Barella","position":"Merkez Orta Saha","age":27,birthplace: "Zagreb, Hirvatistan", "teamId":"inter","value":80,"role":"box_to_box","trait":"elite"},
    {"name":"Federico Dimarco","position":"Sol Bek","age":26,birthplace: "Br�ksel, Bel�ika", "teamId":"inter","value":50,"role":"wing_back","trait":"aggressive"},
    {"name":"Theo Hernandez","position":"Sol Bek","age":27,birthplace: "Br�ksel, Bel�ika", "teamId":"milan","value":60,"role":"wing_back","trait":"aggressive"},
    {"name":"Fikayo Tomori","position":"Stoper","age":26,birthplace: "Prag, �ekya", "teamId":"milan","value":40,"role":"stopper","trait":"stopper"},
    {"name":"Dusan Vlahovic","position":"Santrafor","age":24,birthplace: "Br�ksel, Bel�ika", "teamId":"juventus","value":65,"role":"target_man","trait":"poacher"},
    {"name":"Federico Chiesa","position":"Sağ Açık","age":26,birthplace: "Br�ksel, Bel�ika", "teamId":"juventus","value":40,"role":"winger","trait":"aggressive"},
    {"name":"Gleison Bremer","position":"Stoper","age":27,birthplace: "Br�ksel, Bel�ika", "teamId":"juventus","value":60,"role":"stopper","trait":"stopper"},
    {"name":"Manuel Locatelli","position":"Ön Libero","age":26,birthplace: "Kopenhag, Danimarka", "teamId":"juventus","value":30,"role":"anchor","trait":"playmaker"},
    {"name":"Lois Openda","position":"Santrafor","age":24,birthplace: "Br�ksel, Bel�ika", "teamId":"rbleipzig","value":60,"role":"poacher","trait":"aggressive"},
    {"name":"Xavi Simons","position":"10 Numara","age":21,birthplace: "Prag, �ekya", "teamId":"rbleipzig","value":80,"role":"playmaker","trait":"elite"},
    {"name":"Dani Olmo","position":"10 Numara","age":26,birthplace: "Lizbon, Portekiz", "teamId":"rbleipzig","value":50,"role":"maestro","trait":"playmaker"},
    {"name":"Benjamin Sesko","position":"Santrafor","age":21,birthplace: "Radee, Slovenya", "teamId":"rbleipzig","value":50,"role":"target_man","trait":"poacher"},
    {"name":"Harry Kane","position":"Santrafor","age":31,birthplace: "Londra, Ingiltere", "teamId":"bayern","value":100,"role":"target_man","trait":"playmaker"},
    {"name":"Leroy Sane","position":"Sağ Açık","age":28,birthplace: "Prag, �ekya", "teamId":"bayern","value":70,"role":"inside_forward","trait":"winger"},
    {"name":"Alphonso Davies","position":"Sol Bek","age":23,birthplace: "Prag, �ekya", "teamId":"bayern","value":50,"role":"wing_back","trait":"aggressive"},
    {"name":"Dayot Upamecano","position":"Stoper","age":26,birthplace: "Br�ksel, Bel�ika", "teamId":"bayern","value":45,"role":"stopper","trait":"stopper"},
    {"name":"Mathys Tel","position":"Santrafor","age":19,birthplace: "Lizbon, Portekiz", "teamId":"bayern","value":40,"role":"poacher","trait":"elite"},
    {"name":"Jeremie Frimpong","position":"Sağ Bek","age":23,birthplace: "Zagreb, Hirvatistan", "teamId":"leverkusen","value":50,"role":"wing_back","trait":"aggressive"},
    {"name":"Victor Boniface","position":"Santrafor","age":23,birthplace: "Br�ksel, Bel�ika", "teamId":"leverkusen","value":40,"role":"target_man","trait":"poacher"},
    {"name":"Alex Grimaldo","position":"Sol Bek","age":29,birthplace: "Kopenhag, Danimarka", "teamId":"leverkusen","value":45,"role":"wing_back","trait":"playmaker"},
    {"name":"Exequiel Palacios","position":"Merkez Orta Saha","age":26,birthplace: "Lizbon, Portekiz", "teamId":"leverkusen","value":40,"role":"box_to_box","trait":"playmaker"},
    {"name":"Marquinhos","position":"Stoper","age":30,birthplace: "Br�ksel, Bel�ika", "teamId":"psg","value":50,"role":"stopper","trait":"leader"},
    {"name":"Gianluigi Donnarumma","position":"Kaleci","age":25,birthplace: "Prag, �ekya", "teamId":"psg","value":40,"role":"sweeper_keeper","trait":"elite"},
    {"name":"Randal Kolo Muani","position":"Santrafor","age":25,birthplace: "Roma, Italya", "teamId":"psg","value":45,"role":"poacher","trait":"aggressive"},
    {"name":"Ousmane Dembele","position":"Sağ Açık","age":27,birthplace: "Vernon, Fransa", "teamId":"psg","value":60,"role":"winger","trait":"playmaker"},
    {"name":"Manuel Ugarte","position":"Ön Libero","age":23,birthplace: "Kopenhag, Danimarka", "teamId":"psg","value":45,"role":"anchor","trait":"stopper"},
    {"name":"Evan Ferguson","position":"Santrafor","age":19,birthplace: "Lizbon, Portekiz", "teamId":"brighton","value":50,"role":"target_man","trait":"elite"},
    {"name":"Kaoru Mitoma","position":"Sol Açık","age":27,birthplace: "Lizbon, Portekiz", "teamId":"brighton","value":45,"role":"winger","trait":"aggressive"},
    {"name":"Pervis Estupinan","position":"Sol Bek","age":26,birthplace: "Br�ksel, Bel�ika", "teamId":"brighton","value":35,"role":"wing_back","trait":"aggressive"},
    {"name":"Joao Pedro","position":"Santrafor","age":23,birthplace: "Ribeir�o Preto, Brezilya", "teamId":"brighton","value":35,"role":"poacher","trait":"playmaker"},
    {"name":"Mohammed Kudus","position":"Sağ Açık","age":24,birthplace: "Zagreb, Hirvatistan", "teamId":"westham","value":50,"role":"inside_forward","trait":"aggressive"},
    {"name":"Lucas Paqueta","position":"10 Numara","age":27,birthplace: "Prag, �ekya", "teamId":"westham","value":65,"role":"playmaker","trait":"maestro"},
    {"name":"Jarrod Bowen","position":"Sağ Açık","age":27,birthplace: "Prag, �ekya", "teamId":"westham","value":50,"role":"inside_forward","trait":"poacher"},
    {"name":"Edson Alvarez","position":"Ön Libero","age":26,birthplace: "Zagreb, Hirvatistan", "teamId":"westham","value":35,"role":"anchor","trait":"stopper"},
    {"name":"Eberechi Eze","position":"10 Numara","age":26,birthplace: "Br�ksel, Bel�ika", "teamId":"crystalpalace","value":55,"role":"playmaker","trait":"maestro"},
    {"name":"Marc Guehi","position":"Stoper","age":24,birthplace: "Kopenhag, Danimarka", "teamId":"crystalpalace","value":38,"role":"stopper","trait":"stopper"},
    {"name":"Michael Olise","position":"Sağ Açık","age":22,birthplace: "Prag, �ekya", "teamId":"crystalpalace","value":55,"role":"inside_forward","trait":"playmaker"},
    {"name":"Dominic Solanke","position":"Santrafor","age":27,birthplace: "Roma, Italya", "teamId":"bournemouth","value":40,"role":"target_man","trait":"poacher"},
    {"name":"Milos Kerkez","position":"Sol Bek","age":20,birthplace: "Zagreb, Hirvatistan", "teamId":"bournemouth","value":20,"role":"wing_back","trait":"aggressive"},
    {"name":"Bryan Mbeumo","position":"Sağ Açık","age":25,birthplace: "Kopenhag, Danimarka", "teamId":"brentford","value":40,"role":"inside_forward","trait":"playmaker"},
    {"name":"Ivan Toney","position":"Santrafor","age":28,birthplace: "Kopenhag, Danimarka", "teamId":"brentford","value":50,"role":"target_man","trait":"poacher"},
    {"name":"Ollie Watkins","position":"Santrafor","age":28,birthplace: "Zagreb, Hirvatistan", "teamId":"astonvilla","value":65,"role":"poacher","trait":"aggressive"},
    {"name":"Douglas Luiz","position":"Merkez Orta Saha","age":26,birthplace: "Lizbon, Portekiz", "teamId":"astonvilla","value":70,"role":"box_to_box","trait":"playmaker"},
    {"name":"Moussa Diaby","position":"Sağ Açık","age":25,birthplace: "Roma, Italya", "teamId":"astonvilla","value":55,"role":"winger","trait":"aggressive"},
    {"name":"Pau Torres","position":"Stoper","age":27,birthplace: "Lizbon, Portekiz", "teamId":"astonvilla","value":45,"role":"stopper","trait":"playmaker"},
    {"name":"Pedro Neto","position":"Sol Açık","age":24,birthplace: "Roma, Italya", "teamId":"wolves","value":55,"role":"winger","trait":"aggressive"},
    {"name":"Matheus Cunha","position":"Santrafor","age":25,birthplace: "Jo�o Pessoa, Brezilya", "teamId":"wolves","value":45,"role":"poacher","trait":"playmaker"},
    {"name":"Joao Gomes","position":"Ön Libero","age":23,birthplace: "Kopenhag, Danimarka", "teamId":"wolves","value":35,"role":"anchor","trait":"stopper"},
    {"name":"Hwang Hee-chan","position":"Santrafor","age":28,birthplace: "Kopenhag, Danimarka", "teamId":"wolves","value":25,"role":"poacher","trait":"aggressive"},
    {"name":"Antonee Robinson","position":"Sol Bek","age":27,birthplace: "Br�ksel, Bel�ika", "teamId":"fulham","value":20,"role":"wing_back","trait":"aggressive"},
    {"name":"Joao Palhinha","position":"Ön Libero","age":29,birthplace: "Prag, �ekya", "teamId":"fulham","value":55,"role":"anchor","trait":"stopper"},
    {"name":"Alex Iwobi","position":"Merkez Orta Saha","age":28,birthplace: "Prag, �ekya", "teamId":"fulham","value":25,"role":"box_to_box","trait":"playmaker"},
    {"name":"Jarrad Branthwaite","position":"Stoper","age":22,birthplace: "Zagreb, Hirvatistan", "teamId":"everton","value":42,"role":"stopper","trait":"stopper"},
    {"name":"Amadou Onana","position":"Ön Libero","age":23,birthplace: "Roma, Italya", "teamId":"everton","value":50,"role":"anchor","trait":"stopper"},
    {"name":"Dwight McNeil","position":"Sol Açık","age":24,birthplace: "Lizbon, Portekiz", "teamId":"everton","value":22,"role":"winger","trait":"playmaker"},
    {"name":"Anthony Gordon","position":"Sol Açık","age":23,birthplace: "Kopenhag, Danimarka", "teamId":"newcastle","value":60,"role":"inside_forward","trait":"aggressive"},
    {"name":"Kieran Trippier","position":"Sağ Bek","age":34,birthplace: "Roma, Italya", "teamId":"newcastle","value":10,"role":"wing_back","trait":"playmaker"},
    {"name":"Morgan Gibbs-White","position":"10 Numara","age":24,birthplace: "Prag, �ekya", "teamId":"nottmforest","value":40,"role":"playmaker","trait":"maestro"},
    {"name":"Murillo","position":"Stoper","age":22,birthplace: "Br�ksel, Bel�ika", "teamId":"nottmforest","value":35,"role":"stopper","trait":"stopper"},
    {"name":"Taiwo Awoniyi","position":"Santrafor","age":27,birthplace: "Lizbon, Portekiz", "teamId":"nottmforest","value":28,"role":"target_man","trait":"poacher"},
    {"name":"Enes Ünal","position":"Santrafor","age":27,birthplace: "Lizbon, Portekiz", "teamId":"bournemouth","value":18,"role":"target_man","trait":"poacher"},
    {"name":"Çağlar Söyüncü","position":"Stoper","age":28,birthplace: "Roma, Italya", "teamId":"fenerbahce","value":15,"role":"stopper","trait":"aggressive"},
    {"name":"Orkun Kökçü","position":"Merkez Orta Saha","age":23,birthplace: "Roma, Italya", "teamId":"benfica","value":27,"role":"playmaker","trait":"maestro"},
    {"name":"Kerem Aktürkoğlu","position":"Sol Açık","age":25,birthplace: "Zagreb, Hirvatistan", "teamId":"galatasaray","value":15,"role":"inside_forward","trait":"aggressive"},
    {name:"Lesley Ugochukwu",position:"Orta Saha",age:22,birthplace: "Rennes, Fransa", teamId:"galatasaray",value:15,role:"box_to_box",trait:"aggressive"},
    {"name":"Barış Alper Yılmaz","position":"Sağ Açık","age":24,birthplace: "Prag, �ekya", "teamId":"galatasaray","value":20,"role":"winger","trait":"elite"},
    {"name":"İsmail Yüksek","position":"Ön Libero","age":25,birthplace: "Br�ksel, Bel�ika", "teamId":"fenerbahce","value":14,"role":"anchor","trait":"stopper"},
    {"name":"Sebastian Szymanski","position":"10 Numara","age":25,birthplace: "Roma, Italya", "teamId":"fenerbahce","value":19,"role":"playmaker","trait":"maestro"},
    {"name":"Mauro Icardi","position":"Santrafor","age":31,birthplace: "Zagreb, Hirvatistan", "teamId":"galatasaray","value":17,"role":"poacher","trait":"elite"}
];

const newWorldStars = worldStarsRaw.map(p => {
    let power = 90;
    if (p.value >= 200) power = 96;
    else if (p.value >= 180) power = 95;
    else if (p.value >= 150) power = 94;
    else if (p.value >= 140) power = 93;
    else if (p.value >= 120) power = 92;
    else if (p.value >= 100) power = 91;

    let scaledPrice = Math.max(1, Math.round(p.value / 3.5));
    return {
        id: p.name.replace(/\W+/g, '').toLowerCase() + '_' + p.teamId,
        name: p.name,
        position: p.position,
        power: power,
        speed: 5, // Hepsi üst düzey
        age: p.age,
        price: Math.max(1, Math.round(p.value / 3.5)),
        birthplace: "Br�ksel, Bel�ika", teamId: p.teamId,
        tacticalRole: p.role,
        mentalTrait: p.trait,
        contractYears: 4,
        isListed: false
    };
});

// Eski kopyaları temizlemek için isim benzerliği veya ID eşleştirmesi yapalım
window.leagueData.players = window.leagueData.players.filter(p => {
    return !worldStarsRaw.some(s => {
        let lastName = s.name.split(' ').pop();
        return p.name.includes(lastName) && p.teamId === s.teamId;
    });
});

window.leagueData.players.push(...newWorldStars);
