const wordList = [
    { en: "I'd like...", tr: "...istiyorum veya almak istiyorum." },
    { en: "Can I get a...? veya Can I have a...?", tr: "...alabilir miyim?" },
    { en: "Black tea", tr: "Siyah çay." },
    { en: "Weak tea", tr: "Açık çay." },
    { en: "Strong tea", tr: "Demli çay." },
    { en: "Tea with lemon", tr: "Limon ve çay." },
    { en: "Herbal tea", tr: "Bitki çayı." },
    { en: "Green tea", tr: "Yeşil çay." },
    { en: "Mint tea", tr: "Nane çayı." },
    { en: "Chamomile tea", tr: "Papatya çayı." },
    { en: "Turkish coffee", tr: "Türk kahvesi." },
    { en: "Filter coffee veya Drip coffee", tr: "Filtre kahve." },
    { en: "Espresso veya Double espresso", tr: "Espresso veya çift shot espresso." },
    { en: "Latte veya Caffe latte", tr: "Sütlü kahve veya latte." },
    { en: "Cappuccino", tr: "Kapuçino." },
    { en: "Flat white", tr: "Köpüğü az sütlü kahve." },
    { en: "Decaf veya Decaf coffee", tr: "Kafeinsiz kahve." },
    { en: "Hot chocolate", tr: "Sıcak çikolata." },
    { en: "Still water veya Plain water", tr: "Durgun su veya gazsız normal su." },
    { en: "Sparkling water veya Mineral water", tr: "Maden suyu, gazlı su veya soda." },
    { en: "Iced coffee", tr: "Buzlu kahve." },
    { en: "Iced latte", tr: "Buzlu latte." },
    { en: "Orange juice veya Freshly squeezed orange juice", tr: "Portakal suyu veya taze sıkılmış portakal suyu." },
    { en: "Lemonade", tr: "Limonata." },
    { en: "Smoothie", tr: "Meyve püreli soğuk içecek veya smoothie." },
    { en: "Milkshake", tr: "Sütlü soğuk içecek veya milkshake." },
    { en: "Whole milk veya Regular milk", tr: "Tam yağlı süt ve normal süt." },
    { en: "Low-fat milk", tr: "Yarım yağlı süt veya az yağlı süt." },
    { en: "Skimmed milk", tr: "Yağsız süt." },
    { en: "Oat milk", tr: "Yulaf sütü." },
    { en: "Almond milk", tr: "Badem sütü." },
    { en: "Soy milk", tr: "Soya sütü." },
    { en: "Lactose-free milk", tr: "Laktozsuz süt." },
    { en: "Sugar", tr: "Şeker veya beyaz şeker." },
    { en: "Brown sugar", tr: "Esmer şeker veya kahverengi şeker." },
    { en: "Sweetener veya Artificial sweetener", tr: "Tatlandırıcı ve yapay tatlandırıcı." },
    { en: "Syrup", tr: "Şurup." },
    { en: "Vanilla", tr: "Vanilya." },
    { en: "Hazelnut", tr: "Fındık." },
    { en: "Caramel", tr: "Karamel." },
    { en: "To go veya Take away", tr: "Paket yaptırmak veya yanında götürmek." },
    { en: "For here veya Dine in", tr: "Burada yemek, burada içmek veya mekanda tüketmek." },
    { en: "Is this sugar free?", tr: "Bu şekersiz mi?" },
    { en: "Does it contain...?", tr: "İçinde ... var mı veya ... içeriyor mu?" },
    { en: "Dairy", tr: "Süt ürünü." },
    { en: "Nuts", tr: "Kuruyemiş veya fındık fıstık türleri." },
    { en: "Sugar-free", tr: "Şekersiz." },
    { en: "Gluten-free", tr: "Glütensiz." },
    { en: "Dairy-free", tr: "Süt ürünü içermeyen." },
    { en: "Lactose-free", tr: "Laktozsuz." },
    { en: "Vegetarian", tr: "Vejetaryen." },
    { en: "Vegan", tr: "Vegan veya hiçbir hayvansal gıda içermeyen." },
    { en: "Nut-free", tr: "Kuruyemiş içermeyen veya fıstıksız." },
    { en: "Low-calorie", tr: "Düşük kalorili veya az kalorili." },
    { en: "Soup veya A bowl of soup", tr: "Çorba veya bir kase çorba." },
    { en: "Soup of the day", tr: "Günün çorbası." },
    { en: "Bill veya Check", tr: "Hesap veya fatura." },
    { en: "Split the bill", tr: "Hesabı bölüşmek." },
    { en: "Do you take credit cards?", tr: "Kredi kartı geçiyor mu?" },
    { en: "In cash", tr: "Nakit olarak veya nakit ödemek." },
    { en: "By credit card veya With credit card", tr: "Kredi kartı ile." },
    { en: "It's on me", tr: "Hesap benden veya ben ödüyorum." },
    { en: "Let's go Dutch", tr: "Alman usulü ödeyelim veya herkes kendi yediğini ödesin. (Ek Not: İngilizlerin Hollandalılardan öğrenmesinden dolayı buradaki 'Dutch', Almancadaki alman anlamına gelen 'Deutsch' ile karıştırılmamalıdır.)" },
    { en: "Keep the change", tr: "Üstü kalsın." },
    { en: "about", tr: "hakkında, yaklaşık" },
    { en: "add", tr: "eklemek" },
    { en: "after", tr: "sonra" },
    { en: "again", tr: "tekrar, yeniden" },
    { en: "all", tr: "tümü, hepsi" },
    { en: "almost", tr: "neredeyse" },
    { en: "also", tr: "ayrıca, de/da" },
    { en: "always", tr: "her zaman" },
    { en: "and", tr: "ve" },
    { en: "animal", tr: "hayvan" },
    { en: "answer", tr: "cevap, cevap vermek" },
    { en: "any", tr: "hiç, herhangi bir" },
    { en: "ask", tr: "sormak, istemek" },
    { en: "baby", tr: "bebek" },
    { en: "back", tr: "geri, sırt" },
    { en: "bad", tr: "kötü" },
    { en: "ball", tr: "top" },
    { en: "be", tr: "olmak" },
    { en: "beautiful", tr: "güzel" },
    { en: "because", tr: "çünkü" },
    { en: "before", tr: "önce" },
    { en: "begin", tr: "başlamak" },
    { en: "behind", tr: "arkasında" },
    { en: "believe", tr: "inanmak" },
    { en: "best", tr: "en iyi" },
    { en: "better", tr: "daha iyi" },
    { en: "big", tr: "büyük" },
    { en: "bird", tr: "kuş" },
    { en: "black", tr: "siyah" },
    { en: "blue", tr: "mavi" },
    { en: "boat", tr: "tekne" },
    { en: "body", tr: "vücut" },
    { en: "book", tr: "kitap" },
    { en: "boy", tr: "erkek çocuk" },
    { en: "bread", tr: "ekmek" },
    { en: "break", tr: "kırmak, mola" },
    { en: "bring", tr: "getirmek" },
    { en: "brother", tr: "erkek kardeş" },
    { en: "brown", tr: "kahverengi" },
    { en: "build", tr: "inşa etmek" },
    { en: "bus", tr: "otobüs" },
    { en: "buy", tr: "satın almak" },
    { en: "call", tr: "aramak, seslenmek" },
    { en: "can", tr: "yapabilmek (yetenek)" },
    { en: "car", tr: "araba" },
    { en: "cat", tr: "kedi" },
    { en: "catch", tr: "yakalamak" },
    { en: "chair", tr: "sandalye" },
    { en: "change", tr: "değiştirmek, değişim" },
    { en: "child", tr: "çocuk" },
    { en: "city", tr: "şehir" },
    { en: "class", tr: "sınıf, ders" },
    { en: "clean", tr: "temiz, temizlemek" },
    { en: "clear", tr: "açık, net" },
    { en: "close", tr: "kapatmak, yakın" },
    { en: "cold", tr: "soğuk" },
    { en: "color", tr: "renk" },
    { en: "come", tr: "gelmek" },
    { en: "computer", tr: "bilgisayar" },
    { en: "cook", tr: "pişirmek" },
    { en: "cool", tr: "serin, harika" },
    { en: "copy", tr: "kopyalamak" },
    { en: "country", tr: "ülke" },
    { en: "cow", tr: "inek" },
    { en: "cry", tr: "ağlamak" },
    { en: "cut", tr: "kesmek" },
    { en: "dance", tr: "dans etmek" },
    { en: "dark", tr: "karanlık" },
    { en: "day", tr: "gün" },
    { en: "decide", tr: "karar vermek" },
    { en: "deep", tr: "derin" },
    { en: "desk", tr: "çalışma masası" },
    { en: "dictionary", tr: "sözlük" },
    { en: "die", tr: "ölmek" },
    { en: "difficult", tr: "zor" },
    { en: "do", tr: "yapmak" },
    { en: "doctor", tr: "doktor" },
    { en: "dog", tr: "köpek" },
    { en: "door", tr: "kapı" },
    { en: "down", tr: "aşağı" },
    { en: "draw", tr: "çizmek" },
    { en: "dream", tr: "rüya, hayal" },
    { en: "drink", tr: "içmek, içecek" },
    { en: "drive", tr: "sürmek" },
    { en: "dry", tr: "kuru" },
    { en: "early", tr: "erken" },
    { en: "earth", tr: "dünya, toprak" },
    { en: "easy", tr: "kolay" },
    { en: "eat", tr: "yemek yemek" },
    { en: "egg", tr: "yumurta" },
    { en: "eight", tr: "sekiz" },
    { en: "end", tr: "son" },
    { en: "english", tr: "İngilizce" },
    { en: "enough", tr: "yeterli" },
    { en: "even", tr: "bile, hatta" },
    { en: "evening", tr: "akşam" },
    { en: "every", tr: "her" },
    { en: "eye", tr: "göz" },
    { en: "face", tr: "yüz (surat)" },
    { en: "fall", tr: "düşmek, sonbahar" },
    { en: "family", tr: "aile" },
    { en: "far", tr: "uzak" },
    { en: "fast", tr: "hızlı" },
    { en: "father", tr: "baba" },
    { en: "feel", tr: "hissetmek" },
    { en: "find", tr: "bulmak" },
    { en: "fine", tr: "iyi" },
    { en: "fire", tr: "ateş, yangın" },
    { en: "first", tr: "birinci, ilk" },
    { en: "fish", tr: "balık" },
    { en: "five", tr: "beş" },
    { en: "fly", tr: "uçmak" },
    { en: "food", tr: "yiyecek" },
    { en: "foot", tr: "ayak" },
    { en: "for", tr: "için" },
    { en: "four", tr: "dört" },
    { en: "friend", tr: "arkadaş" },
    { en: "from", tr: "-den, -dan" },
    { en: "front", tr: "ön" },
    { en: "full", tr: "dolu, tok" },
    { en: "game", tr: "oyun" },
    { en: "garden", tr: "bahçe" },
    { en: "girl", tr: "kız çocuk" },
    { en: "give", tr: "vermek" },
    { en: "glass", tr: "bardak, cam" },
    { en: "go", tr: "gitmek" },
    { en: "good", tr: "iyi" },
    { en: "great", tr: "harika, büyük" },
    { en: "green", tr: "yeşil" },
    { en: "grow", tr: "büyümek, yetiştirmek" },
    { en: "hair", tr: "saç" },
    { en: "half", tr: "yarım" },
    { en: "hand", tr: "el" },
    { en: "happy", tr: "mutlu" },
    { en: "hard", tr: "sert, zor" },
    { en: "hat", tr: "şapka" },
    { en: "have", tr: "sahip olmak" },
    { en: "he", tr: "o (erkek)" },
    { en: "head", tr: "baş, kafa" },
    { en: "hear", tr: "duymak" },
    { en: "heart", tr: "kalp" },
    { en: "heavy", tr: "ağır" },
    { en: "hello", tr: "merhaba" },
    { en: "help", tr: "yardım, yardım etmek" },
    { en: "here", tr: "burada" },
    { en: "high", tr: "yüksek" },
    { en: "history", tr: "tarih" },
    { en: "home", tr: "ev (yuva)" },
    { en: "horse", tr: "at" },
    { en: "hot", tr: "sıcak" },
    { en: "hour", tr: "saat (süre)" },
    { en: "house", tr: "ev (bina)" },
    { en: "how", tr: "nasıl" },
    { en: "i", tr: "ben" },
    { en: "ice", tr: "buz" },
    { en: "idea", tr: "fikir" },
    { en: "if", tr: "eğer" },
    { en: "important", tr: "önemli" },
    { en: "in", tr: "içinde" },
    { en: "into", tr: "içine" },
    { en: "is", tr: "dır/dir (olmak)" },
    { en: "it", tr: "o (cansız/hayvan)" },
    { en: "job", tr: "iş, meslek" },
    { en: "jump", tr: "zıplamak" },
    { en: "just", tr: "sadece, az önce" },
    { en: "keep", tr: "tutmak, saklamak" },
    { en: "key", tr: "anahtar" },
    { en: "kind", tr: "kibar, tür" },
    { en: "know", tr: "bilmek" },
    { en: "land", tr: "kara, arazi" },
    { en: "language", tr: "dil" },
    { en: "large", tr: "geniş, büyük" },
    { en: "last", tr: "son, sonuncu" },
    { en: "late", tr: "geç" },
    { en: "laugh", tr: "gülmek" },
    { en: "learn", tr: "öğrenmek" },
    { en: "leave", tr: "ayrılmak, bırakmak" },
    { en: "left", tr: "sol" },
    { en: "letter", tr: "mektup, harf" },
    { en: "life", tr: "hayat" },
    { en: "light", tr: "ışık, hafif" },
    { en: "like", tr: "hoşlanmak, gibi" },
    { en: "line", tr: "çizgi, sıra" },
    { en: "list", tr: "liste" },
    { en: "listen", tr: "dinlemek" },
    { en: "little", tr: "küçük, biraz" },
    { en: "live", tr: "yaşamak" },
    { en: "long", tr: "uzun" },
    { en: "look", tr: "bakmak, görünmek" },
    { en: "love", tr: "aşk, sevmek" },
    { en: "make", tr: "yapmak (üretmek)" },
    { en: "man", tr: "adam" },
    { en: "many", tr: "çok (sayılabilen)" },
    { en: "map", tr: "harita" },
    { en: "meat", tr: "et" },
    { en: "meet", tr: "buluşmak, tanışmak" },
    { en: "milk", tr: "süt" },
    { en: "mind", tr: "zihin, akıl" },
    { en: "minute", tr: "dakika" },
    { en: "money", tr: "para" },
    { en: "month", tr: "ay (takvim)" },
    { en: "moon", tr: "ay (gökyüzü)" },
    { en: "morning", tr: "sabah" },
    { en: "mother", tr: "anne" },
    { en: "mountain", tr: "dağ" },
    { en: "mouth", tr: "ağız" },
    { en: "move", tr: "hareket etmek" },
    { en: "much", tr: "çok (sayılamayan)" },
    { en: "music", tr: "müzik" },
    { en: "must", tr: "-meli/-malı (zorunluluk)" },
    { en: "name", tr: "isim, ad" },
    { en: "near", tr: "yakın" },
    { en: "need", tr: "ihtiyaç, ihtiyaç duymak" },
    { en: "never", tr: "asla" },
    { en: "new", tr: "yeni" },
    { en: "next", tr: "sonraki, yanındaki" },
    { en: "night", tr: "gece" },
    { en: "no", tr: "hayır" },
    { en: "north", tr: "kuzey" },
    { en: "nose", tr: "burun" },
    { en: "not", tr: "değil" },
    { en: "now", tr: "şimdi" },
    { en: "number", tr: "numara, sayı" },
    { en: "often", tr: "sık sık" },
    { en: "old", tr: "eski, yaşlı" },
    { en: "on", tr: "üzerinde" },
    { en: "one", tr: "bir" },
    { en: "only", tr: "sadece" },
    { en: "open", tr: "açık, açmak" },
    { en: "or", tr: "veya" },
    { en: "other", tr: "diğer" },
    { en: "our", tr: "bizim" },
    { en: "out", tr: "dışarı" },
    { en: "over", tr: "üzerinden, bitti" },
    { en: "page", tr: "sayfa" },
    { en: "paper", tr: "kağıt" },
    { en: "part", tr: "bölüm, parça" },
    { en: "people", tr: "insanlar" },
    { en: "person", tr: "kişi" },
    { en: "picture", tr: "resim" },
    { en: "place", tr: "yer, mekan" },
    { en: "play", tr: "oynamak" },
    { en: "please", tr: "lütfen" },
    { en: "point", tr: "puan, nokta" },
    { en: "poor", tr: "fakir, zavallı" },
    { en: "problem", tr: "sorun, problem" },
    { en: "put", tr: "koymak" },
    { en: "question", tr: "soru" },
    { en: "quick", tr: "hızlı, çabuk" },
    { en: "quiet", tr: "sessiz" },
    { en: "rain", tr: "yağmur" },
    { en: "read", tr: "okumak" },
    { en: "ready", tr: "hazır" },
    { en: "red", tr: "kırmızı" },
    { en: "remember", tr: "hatırlamak" },
    { en: "rest", tr: "dinlenmek, geri kalan" },
    { en: "rich", tr: "zengin" },
    { en: "right", tr: "sağ, doğru" },
    { en: "river", tr: "nehir" },
    { en: "road", tr: "yol" },
    { en: "room", tr: "oda" },
    { en: "run", tr: "koşmak" },
    { en: "sad", tr: "üzgün" },
    { en: "same", tr: "aynı" },
    { en: "say", tr: "söylemek" },
    { en: "school", tr: "okul" },
    { en: "sea", tr: "deniz" },
    { en: "second", tr: "saniye, ikinci" },
    { en: "see", tr: "görmek" },
    { en: "sentence", tr: "cümle" },
    { en: "she", tr: "o (kadın)" },
    { en: "short", tr: "kısa" },
    { en: "show", tr: "göstermek" },
    { en: "side", tr: "yan, taraf" },
    { en: "simple", tr: "basit" },
    { en: "sister", tr: "kız kardeş" },
    { en: "sit", tr: "oturmak" },
    { en: "six", tr: "altı" },
    { en: "sky", tr: "gökyüzü" },
    { en: "sleep", tr: "uyumak" },
    { en: "slow", tr: "yavaş" },
    { en: "small", tr: "küçük" },
    { en: "smile", tr: "gülümsemek" },
    { en: "some", tr: "bazı, biraz" },
    { en: "son", tr: "erkek evlat" },
    { en: "soon", tr: "yakında" },
    { en: "sound", tr: "ses" },
    { en: "south", tr: "güney" },
    { en: "space", tr: "boşluk, uzay" },
    { en: "speak", tr: "konuşmak" },
    { en: "spell", tr: "hecelemek" },
    { en: "spring", tr: "ilkbahar" },
    { en: "stand", tr: "ayakta durmak" },
    { en: "star", tr: "yıldız" },
    { en: "start", tr: "başlamak" },
    { en: "stay", tr: "kalmak" },
    { en: "step", tr: "adım" },
    { en: "stop", tr: "durmak" },
    { en: "story", tr: "hikaye" },
    { en: "street", tr: "sokak, cadde" },
    { en: "strong", tr: "güçlü" },
    { en: "student", tr: "öğrenci" },
    { en: "study", tr: "ders çalışmak" },
    { en: "summer", tr: "yaz" },
    { en: "sun", tr: "güneş" },
    { en: "table", tr: "masa, tablo" },
    { en: "take", tr: "almak, götürmek" },
    { en: "talk", tr: "konuşmak" },
    { en: "tall", tr: "uzun (boy)" },
    { en: "teach", tr: "öğretmek" },
    { en: "teacher", tr: "öğretmen" },
    { en: "tell", tr: "anlatmak, söylemek" },
    { en: "ten", tr: "on" },
    { en: "test", tr: "test, sınav" },
    { en: "than", tr: "-den, -dan (karşılaştırma)" },
    { en: "that", tr: "şu, o" },
    { en: "the", tr: "(belirteç)" },
    { en: "their", tr: "onların" },
    { en: "them", tr: "onları, onlara" },
    { en: "then", tr: "sonra, o zaman" },
    { en: "there", tr: "orada" },
    { en: "these", tr: "bunlar" },
    { en: "they", tr: "onlar" },
    { en: "thing", tr: "şey, eşya" },
    { en: "think", tr: "düşünmek" },
    { en: "this", tr: "bu" },
    { en: "those", tr: "şunlar" },
    { en: "three", tr: "üç" },
    { en: "time", tr: "zaman" },
    { en: "to", tr: "-e, -a (yönelme)" },
    { en: "today", tr: "bugün" },
    { en: "together", tr: "birlikte" },
    { en: "too", tr: "de/da, çok" },
    { en: "top", tr: "üst, zirve" },
    { en: "town", tr: "kasaba" },
    { en: "tree", tr: "ağaç" },
    { en: "true", tr: "doğru, gerçek" },
    { en: "try", tr: "denemek" },
    { en: "two", tr: "iki" },
    { en: "under", tr: "altında" },
    { en: "understand", tr: "anlamak" },
    { en: "until", tr: "kadar" },
    { en: "up", tr: "yukarı" },
    { en: "us", tr: "bizi, bize" },
    { en: "use", tr: "kullanmak" },
    { en: "very", tr: "çok" },
    { en: "wait", tr: "beklemek" },
    { en: "walk", tr: "yürümek" },
    { en: "want", tr: "istemek" },
    { en: "warm", tr: "ılık, sıcak" },
    { en: "watch", tr: "izlemek, saat" },
    { en: "water", tr: "su" },
    { en: "way", tr: "yol, yöntem" },
    { en: "we", tr: "biz" },
    { en: "weather", tr: "hava (durumu)" },
    { en: "week", tr: "hafta" },
    { en: "well", tr: "iyi" },
    { en: "what", tr: "ne" },
    { en: "when", tr: "ne zaman" },
    { en: "where", tr: "nerede, nereye" },
    { en: "which", tr: "hangi" },
    { en: "white", tr: "beyaz" },
    { en: "who", tr: "kim" },
    { en: "why", tr: "neden" },
    { en: "will", tr: "ecek/acak (gelecek)" },
    { en: "wind", tr: "rüzgar" },
    { en: "window", tr: "pencere" },
    { en: "winter", tr: "kış" },
    { en: "with", tr: "ile" },
    { en: "woman", tr: "kadın" },
    { en: "wood", tr: "odun, ahşap" },
    { en: "word", tr: "kelime" },
    { en: "work", tr: "çalışmak, iş" },
    { en: "world", tr: "dünya" },
    { en: "write", tr: "yazmak" },
    { en: "year", tr: "yıl" },
    { en: "yellow", tr: "sarı" },
    { en: "yes", tr: "evet" },
    { en: "you", tr: "sen, siz" },
    { en: "young", tr: "genç" },
    { en: "your", tr: "senin, sizin" },
    { en: "go out", tr: "dışarı çıkmak" },
    { en: "hi", tr: "selam" },
    { en: "years old", tr: "yaşında" },
    { en: "age", tr: "yaş" },
    { en: "windows", tr: "pencereler" },
    { en: "turn on", tr: "açmak (elektronik eşyalar)" },
    { en: "turn off", tr: "kapatmak (elektronik eşyalar)" },
    { en: "I know", tr: "biliyorum" },
    { en: "I don't know", tr: "bilmiyorum" },
    { en: "thank you", tr: "teşekkür ederim" },
    { en: "thanks", tr: "teşekkürler" },
    { en: "I am fine", tr: "iyiyim" },
    { en: "wake up", tr: "uyanmak" },
    { en: "goodbye", tr: "hoşça kal" },
    { en: "sorry", tr: "üzgünüm" },
    { en: "ok", tr: "tamam" },
    { en: "pay", tr: "ödemek" },
    { en: "price", tr: "fiyat" },
    { en: "shop", tr: "mağaza" },
    { en: "come back", tr: "geri dönmek" },
    { en: "Monday", tr: "Pazartesi" },
    { en: "Tuesday", tr: "Salı" },
    { en: "Wednesday", tr: "Çarşamba" },
    { en: "Thursday", tr: "Perşembe" },
    { en: "Friday", tr: "Cuma" },
    { en: "Saturday", tr: "Cumartesi" },
    { en: "Sunday", tr: "Pazar" },
    { en: "January", tr: "Ocak" },
    { en: "February", tr: "Şubat" },
    { en: "March", tr: "Mart" },
    { en: "April", tr: "Nisan" },
    { en: "May", tr: "Mayıs" },
    { en: "June", tr: "Haziran" },
    { en: "July", tr: "Temmuz" },
    { en: "August", tr: "Ağustos" },
    { en: "September", tr: "Eylül" },
    { en: "October", tr: "Ekim" },
    { en: "November", tr: "Kasım" },
    { en: "December", tr: "Aralık" },
    { en: "Autumn / Fall", tr: "Sonbahar" },
    { en: "bed", tr: "yatak" },
    { en: "orange", tr: "turuncu, portakal" },
    { en: "purple", tr: "mor" },
    { en: "pink", tr: "pembe" },
    { en: "gray", tr: "gri" },
    { en: "tea", tr: "çay" },
    { en: "coffee", tr: "kahve" },
    { en: "I don't understand", tr: "anlamıyorum" },
    { en: "I'm fine", tr: "iyiyim" },
    { en: "okay", tr: "tamam" },
    { en: "between", tr: "arasında" },
    { en: "in front of", tr: "önünde" },
    { en: "next to", tr: "bitişiğinde" },
    { en: "you're welcome", tr: "rica ederim" },
    { en: "how are you", tr: "nasılsın" },
    { en: "Can you repeat?", tr: "Tekrar edebilir misin?" }
];
